CREATE TABLE PROJUDI.ARQ_CEPH (
    ID_ARQ                    NUMBER(24)      NOT NULL, 
	ID_USU                    NUMBER(24)      NOT NULL, 
    CAMINHO_CEPH              VARCHAR2(250)   NOT NULL,
	DATA_INCLUSAO             DATE            NOT NULL
);

CREATE UNIQUE INDEX PROJUDI.ARQ_CEPH_IDXPK ON PROJUDI.ARQ_CEPH (ID_ARQ);

ALTER TABLE PROJUDI.ARQ_CEPH ADD CONSTRAINT PK_ARQ_CEPH PRIMARY KEY(ID_ARQ);

CREATE INDEX PROJUDI.ARQ_CEPH_IDXIDX ON PROJUDI.ARQ_CEPH (ID_USU);

