
package br.gov.caixa.jaxws.sibar.manutencao_cobranca_bancaria.boleto.externo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "manutencao_cobranca_bancaria", targetNamespace = "http://caixa.gov.br/sibar/manutencao_cobranca_bancaria/boleto/externo")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    br.gov.caixa.jaxws.sibar.manutencao_cobranca_bancaria.boleto.externo.ObjectFactory.class,
    br.gov.caixa.jaxws.sibar.ObjectFactory.class
})
public interface ManutencaoCobrancaBancaria {


    /**
     * 
     * @param parameters
     * @return
     *     returns br.gov.caixa.axis.sibar.manutencao_cobranca_bancaria.boleto.externo.ServicoSaidaNegocialType
     */
    @WebMethod(operationName = "INCLUI_BOLETO", action = "IncluiBoleto")
    @WebResult(name = "SERVICO_SAIDA", targetNamespace = "http://caixa.gov.br/sibar/manutencao_cobranca_bancaria/boleto/externo", partName = "parameters")
    public ServicoSaidaNegocialType incluiBOLETO(
        @WebParam(name = "SERVICO_ENTRADA", targetNamespace = "http://caixa.gov.br/sibar/manutencao_cobranca_bancaria/boleto/externo", partName = "parameters")
        ServicoEntradaNegocialType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns br.gov.caixa.axis.sibar.manutencao_cobranca_bancaria.boleto.externo.ServicoSaidaNegocialType
     */
    @WebMethod(operationName = "BAIXA_BOLETO", action = "BaixaBoleto")
    @WebResult(name = "SERVICO_SAIDA", targetNamespace = "http://caixa.gov.br/sibar/manutencao_cobranca_bancaria/boleto/externo", partName = "parameters")
    public ServicoSaidaNegocialType baixaBOLETO(
        @WebParam(name = "SERVICO_ENTRADA", targetNamespace = "http://caixa.gov.br/sibar/manutencao_cobranca_bancaria/boleto/externo", partName = "parameters")
        ServicoEntradaNegocialType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns br.gov.caixa.axis.sibar.manutencao_cobranca_bancaria.boleto.externo.ServicoSaidaNegocialType
     */
    @WebMethod(operationName = "ALTERA_BOLETO", action = "AlteraBoleto")
    @WebResult(name = "SERVICO_SAIDA", targetNamespace = "http://caixa.gov.br/sibar/manutencao_cobranca_bancaria/boleto/externo", partName = "parameters")
    public ServicoSaidaNegocialType alteraBOLETO(
        @WebParam(name = "SERVICO_ENTRADA", targetNamespace = "http://caixa.gov.br/sibar/manutencao_cobranca_bancaria/boleto/externo", partName = "parameters")
        ServicoEntradaNegocialType parameters);

}
