
package br.gov.caixa.jaxws.sibar.manutencao_cobranca_bancaria.boleto.externo;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "manutencao_cobranca_bancaria", targetNamespace = "http://caixa.gov.br/sibar/manutencao_cobranca_bancaria/boleto/externo", wsdlLocation = "https://barramento.caixa.gov.br/sibar/ManutencaoCobrancaBancaria/BoletoDt/Externo?wsdl")
public class ManutencaoCobrancaBancaria_Service
    extends Service
{

    private final static URL MANUTENCAOCOBRANCABANCARIA_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.gov.caixa.jaxws.sibar.manutencao_cobranca_bancaria.boleto.externo.ManutencaoCobrancaBancaria_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.gov.caixa.jaxws.sibar.manutencao_cobranca_bancaria.boleto.externo.ManutencaoCobrancaBancaria_Service.class.getResource(".");
            url = new URL(baseUrl, "https://barramento.caixa.gov.br/sibar/ManutencaoCobrancaBancaria/BoletoDt/Externo?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://barramento.caixa.gov.br/sibar/ManutencaoCobrancaBancaria/BoletoDt/Externo?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MANUTENCAOCOBRANCABANCARIA_WSDL_LOCATION = url;
    }

    public ManutencaoCobrancaBancaria_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ManutencaoCobrancaBancaria_Service() {
        super(MANUTENCAOCOBRANCABANCARIA_WSDL_LOCATION, new QName("http://caixa.gov.br/sibar/manutencao_cobranca_bancaria/boleto/externo", "manutencao_cobranca_bancaria"));
    }

    /**
     * 
     * @return
     *     returns ManutencaoCobrancaBancaria
     */
    @WebEndpoint(name = "manutencao_cobranca_bancariaSOAP")
    public ManutencaoCobrancaBancaria getManutencaoCobrancaBancariaSOAP() {
        return super.getPort(new QName("http://caixa.gov.br/sibar/manutencao_cobranca_bancaria/boleto/externo", "manutencao_cobranca_bancariaSOAP"), ManutencaoCobrancaBancaria.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ManutencaoCobrancaBancaria
     */
    @WebEndpoint(name = "manutencao_cobranca_bancariaSOAP")
    public ManutencaoCobrancaBancaria getManutencaoCobrancaBancariaSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://caixa.gov.br/sibar/manutencao_cobranca_bancaria/boleto/externo", "manutencao_cobranca_bancariaSOAP"), ManutencaoCobrancaBancaria.class, features);
    }

}
