ALTER TABLE PROJUDI.AUDI_PROC ADD ACORDO NUMBER(3);

ALTER TABLE PROJUDI.AUDI_PROC ADD VALOR_ACORDO NUMBER(20,2);

CREATE TABLE PROJUDI.AUDI_PROC_FISICO (
    ID_AUDI_PROC_FISICO       NUMBER(24,0)  NOT NULL,
    ID_AUDI_PROC              NUMBER(24,0)  NOT NULL, 
    PROC_NUMERO_COMPLETO      VARCHAR2(20)  NOT NULL, 
    PROMOVENTE                VARCHAR2(255),
    PROMOVIDO                 VARCHAR2(255),
    SERVENTIA                 VARCHAR2(255),
    SERVENTIA_CODIGO          NUMBER(9)    
);

CREATE UNIQUE INDEX PROJUDI.AUDI_PROC_FISICO_IDXPK ON PROJUDI.AUDI_PROC_FISICO (ID_AUDI_PROC_FISICO);

ALTER TABLE PROJUDI.AUDI_PROC_FISICO ADD CONSTRAINT PK_AUDI_PROC_FISICO PRIMARY KEY(ID_AUDI_PROC_FISICO);

ALTER TABLE PROJUDI.AUDI_PROC_FISICO ADD CONSTRAINT AUDIPROC_AUDIPROCFISICO_FK FOREIGN KEY (ID_AUDI_PROC) REFERENCES PROJUDI.AUDI_PROC (ID_AUDI_PROC);

CREATE SEQUENCE PROJUDI.AUDI_PROC_FISICO_ID_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

CREATE OR REPLACE TRIGGER PROJUDI.AUDI_PROC_FISICO_TRG BEFORE INSERT OR UPDATE ON AUDI_PROC_FISICO
FOR EACH ROW
DECLARE
v_newVal NUMBER(12) := 0;
v_incval NUMBER(12) := 0;
BEGIN
  IF INSERTING AND :new.ID_AUDI_PROC_FISICO IS NULL THEN
    SELECT AUDI_PROC_FISICO_ID_SEQ.NEXTVAL INTO v_newVal FROM DUAL;
   
   :new.ID_AUDI_PROC_FISICO := v_newVal;
  END IF;
END;

ALTER TRIGGER PROJUDI.AUDI_PROC_FISICO_TRG ENABLE;

CREATE OR REPLACE FORCE VIEW PROJUDI.VIEW_AUDI_PROC_FISICO AS 
  SELECT
    APF.ID_AUDI_PROC_FISICO AS ID_AUDI_PROC_FISICO,
    APF.ID_AUDI_PROC AS ID_AUDI_PROC,
    APF.PROC_NUMERO_COMPLETO AS PROC_NUMERO_COMPLETO,
    APF.PROMOVENTE AS PROMOVENTE,
    APF.PROMOVIDO AS PROMOVIDO,
    APF.SERVENTIA AS SERVENTIA,
    APF.SERVENTIA_CODIGO AS SERVENTIA_CODIGO,
    AP.ID_AUDI AS ID_AUDI, 
    AT.AUDI_TIPO AS AUDI_TIPO,
    AP.ID_AUDI_PROC_STATUS AS ID_AUDI_PROC_STATUS,
    APS.AUDI_PROC_STATUS AS AUDI_PROC_STATUS,
    AP.ID_SERV_CARGO AS ID_SERV_CARGO,
    SC.SERV_CARGO AS SERV_CARGO,
    AP.DATA_MOVI AS DATA_MOVI,
    AP.CODIGO_TEMP AS CODIGO_TEMP,
    AT.AUDI_TIPO_CODIGO AS AUDI_TIPO_CODIGO,
    APS.AUDI_PROC_STATUS_CODIGO AS AUDI_PROC_STATUS_CODIGO
  FROM 
   PROJUDI.AUDI_PROC_FISICO APF INNER JOIN PROJUDI.AUDI_PROC AP ON AP.ID_AUDI_PROC = APF.ID_AUDI_PROC
   INNER JOIN PROJUDI.AUDI A ON A.ID_AUDI = AP.ID_AUDI
   INNER JOIN AUDI_TIPO AT ON A.ID_AUDI_TIPO = AT.ID_AUDI_TIPO
   LEFT JOIN SERV_CARGO SC ON AP.ID_SERV_CARGO = SC.ID_SERV_CARGO
   LEFT JOIN AUDI_PROC_STATUS APS ON AP.ID_AUDI_PROC_STATUS = APS.ID_AUDI_PROC_STATUS;  
   
INSERT INTO PROJUDI.PROPRIEDADE (PROPRIEDADE, PROPRIEDADE_CODIGO, VALOR) VALUES ('quantidadeDiasMarcarAudienciaAutomaticaCejusc',57,'30');

INSERT INTO PROJUDI.PROPRIEDADE (PROPRIEDADE, PROPRIEDADE_CODIGO, VALOR) VALUES ('quantidadeDiasMarcarMediacaoAutomaticaCejusc',58,'60');

CREATE TABLE PROJUDI.CEJUSC_DISPONIBILIDADE (
	ID_CEJUSC_DISPONIBILIDADE NUMBER(20,0) NOT NULL ENABLE, 
	ID_USU_CEJUSC             NUMBER(20,0), 
	ID_AUDI_TIPO              NUMBER(10,0), 
	ID_SERV                   NUMBER(10,0) NOT NULL ENABLE,  
	DOMINGO                   NUMBER(4,0), 
	SEGUNDA                   NUMBER(4,0), 
	TERCA                     NUMBER(4,0), 
	QUARTA                    NUMBER(4,0), 
	QUINTA                    NUMBER(4,0), 
	SEXTA                     NUMBER(4,0), 
	SABADO                    NUMBER(4,0)
);

CREATE UNIQUE INDEX PROJUDI.CEJUSC_DISPONIBILIDADE_IDXPK ON PROJUDI.CEJUSC_DISPONIBILIDADE (ID_CEJUSC_DISPONIBILIDADE);

ALTER TABLE PROJUDI.CEJUSC_DISPONIBILIDADE ADD CONSTRAINT PK_CEJUSC_DISPONIBILIDADE PRIMARY KEY(ID_CEJUSC_DISPONIBILIDADE);

ALTER TABLE PROJUDI.CEJUSC_DISPONIBILIDADE ADD CONSTRAINT FK_CD_USU_CEJUSC_ID_USU_CEJUSC FOREIGN KEY (ID_USU_CEJUSC) REFERENCES PROJUDI.USU_CEJUSC (ID_USU_CEJUSC);

ALTER TABLE PROJUDI.CEJUSC_DISPONIBILIDADE ADD CONSTRAINT FK_CD_AUDI_TIPO_ID_AUDI_TIPO FOREIGN KEY (ID_AUDI_TIPO) REFERENCES PROJUDI.AUDI_TIPO (ID_AUDI_TIPO);
	 
ALTER TABLE PROJUDI.CEJUSC_DISPONIBILIDADE ADD CONSTRAINT FK_CD_SERV_ID_SERV FOREIGN KEY (ID_SERV) REFERENCES PROJUDI.SERV (ID_SERV);	 

CREATE SEQUENCE PROJUDI.SEQ_CEJUSC_DISPONIBILIDADE  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

CREATE OR REPLACE TRIGGER PROJUDI.TRG_CEJUSC_DISPONIBILIDADE BEFORE INSERT  ON CEJUSC_DISPONIBILIDADE
FOR EACH ROW
DECLARE
v_newVal NUMBER(12) := 0;
BEGIN
  IF INSERTING AND :new.ID_CEJUSC_DISPONIBILIDADE IS NULL THEN
    SELECT  SEQ_CEJUSC_DISPONIBILIDADE.NEXTVAL INTO v_newVal FROM DUAL;
    :new.ID_CEJUSC_DISPONIBILIDADE := v_newVal;
  END IF;
END;

ALTER TRIGGER PROJUDI.TRG_CEJUSC_DISPONIBILIDADE ENABLE;
	
CREATE OR REPLACE FORCE VIEW PROJUDI.VIEW_CEJUSC_DISPONIBILIDADE AS 
  SELECT CD.ID_CEJUSC_DISPONIBILIDADE,
    CD.ID_SERV,
    S.SERV,
    CD.ID_USU_CEJUSC,
    U.NOME,
    CD.DOMINGO,
    CD.SEGUNDA,
    CD.TERCA,
    CD.QUARTA,
    CD.QUINTA,
    CD.SEXTA,
    CD.SABADO,
    CD.ID_AUDI_TIPO,
    AT.AUDI_TIPO
  FROM CEJUSC_DISPONIBILIDADE CD
      INNER JOIN SERV S ON CD.ID_SERV = S.ID_SERV
      INNER JOIN USU_CEJUSC UC ON CD.ID_USU_CEJUSC = UC.ID_USU_CEJUSC
      INNER JOIN USU U ON UC.ID_USU = U.ID_USU
      INNER JOIN AUDI_TIPO AT ON AT.ID_AUDI_TIPO = CD.ID_AUDI_TIPO;