CREATE OR REPLACE VIEW PROJUDI.VIEW_PROX_AUDI_LIVREAUTOCEJUSC
AS SELECT 
    VUS.ID_AUDI AS ID_AUDI,
    VUS.ID_AUDI_TIPO AS ID_AUDI_TIPO,
    AT.AUDI_TIPO AS AUDI_TIPO,
    AT.AUDI_TIPO_CODIGO AS AUDI_TIPO_CODIGO,
    VUS.DATA_AGENDADA AS DATA_AGENDADA,
    VUS.DATA_MOVI AS DATA_MOVI_AUDI,
    VUS.RESERVADA AS RESERVADA,
    VUS.ID_SERV AS ID_SERV,
    AP.ID_AUDI_PROC AS ID_AUDI_PROC,
    AP.ID_AUDI_PROC_STATUS AS ID_AUDI_PROC_STATUS,
    AP.ID_SERV_CARGO AS ID_SERV_CARGO,
    SC.SERV_CARGO AS SERV_CARGO,
    AP.ID_PROC AS ID_PROC,
    AP.DATA_MOVI AS DATA_MOVI_AUDI_PROC,
    VUS.CODIGO_TEMP AS CODIGO_TEMP,
    AP.ACORDO AS ACORDO,
    AP.VALOR_ACORDO AS VALOR_ACORDO 
  FROM 
    (((AUDI VUS JOIN AUDI_TIPO AT ON((VUS.ID_AUDI_TIPO = AT.ID_AUDI_TIPO))) JOIN AUDI_PROC AP ON((VUS.ID_AUDI = AP.ID_AUDI))) JOIN SERV_CARGO SC ON((AP.ID_SERV_CARGO = SC.ID_SERV_CARGO))) 
  WHERE 
    ((AT.AUDI_TIPO_CODIGO <> 12) AND (VUS.RESERVADA <> 1) AND (AP.ID_AUDI_PROC_STATUS = 8) AND (VUS.DATA_MOVI IS NULL) AND (AP.DATA_MOVI IS NULL) AND (AP.ID_PROC IS NULL) AND (AP.CODIGO_TEMP IS NULL)) 
  ORDER BY TO_NUMBER(TO_CHAR(VUS.DATA_AGENDADA, 'YYYYMMDD')), SC.SERV_CARGO
