ALTER TABLE PROJUDI.CERT ADD NUMERO_GUIA_COMPLETO  NUMBER(24);

ALTER TABLE PROJUDI.CERT ADD FINALIDADE NUMBER(3);

ALTER TABLE PROJUDI.CERT ADD ID_MODELO  NUMBER(10);

ALTER TABLE PROJUDI.CERT ADD CONSTRAINT CERT_MODELO_FK FOREIGN KEY (ID_MODELO) REFERENCES PROJUDI.MODELO (ID_MODELO);

ALTER TABLE PROJUDI.CERT ADD ID_COMARCA  NUMBER(10);

ALTER TABLE PROJUDI.CERT ADD CONSTRAINT CERT_COMARCA_FK FOREIGN KEY (ID_COMARCA) REFERENCES PROJUDI.COMARCA (ID_COMARCA);

ALTER TABLE PROJUDI.CERT ADD DOCUMENTO BLOB;

CREATE OR REPLACE VIEW VIEW_CERT AS 
SELECT C.ID_CERT,
       C.CERT,
       C.DATA_VALIDADE, 
       C.DATA_EMISSAO,
       C.CODIGO_TEMP,
       C.NUMERO_GUIA_COMPLETO, 
       C.ID_MODELO,
       M.MODELO,
       C.FINALIDADE,
       C.ID_COMARCA,
       C2.COMARCA,
       C.DOCUMENTO	   
FROM CERT C
LEFT JOIN MODELO M ON M.ID_MODELO = C.ID_MODELO
LEFT JOIN COMARCA C2 ON C2.ID_COMARCA = C.ID_COMARCA;

INSERT INTO PROJUDI.PROPRIEDADE (PROPRIEDADE, PROPRIEDADE_CODIGO, VALOR) VALUES ('SPG_NOME_SERVICO', 60,'FORPSPGI');
