CREATE TABLE PROJUDI.USU_ULTIMO_LOGIN (
    ID_USU                    NUMBER(24,0)  NOT NULL, 
    ID_SERV                   VARCHAR2(24), 
    GRUPO_CODIGO              VARCHAR2(24), 
    ID_SERV_CARGO             VARCHAR2(24), 
    ID_SERV_CARGO_USU_CHEFE   VARCHAR2(24), 
    ID_USU_SERV_CHEFE         VARCHAR2(24)
);

CREATE UNIQUE INDEX PROJUDI.USU_ULTIMO_LOGIN_IDXPK ON PROJUDI.USU_ULTIMO_LOGIN (ID_USU);

ALTER TABLE PROJUDI.USU_ULTIMO_LOGIN ADD CONSTRAINT PK_USU_ULTIMO_LOGIN PRIMARY KEY(ID_USU);

ALTER TABLE PROJUDI.USU_ULTIMO_LOGIN ADD CONSTRAINT USUULTIMOLOGIN_USU_FK FOREIGN KEY (ID_USU) REFERENCES PROJUDI.USU (ID_USU);
