select 'insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (' || id_guia_modelo || ',''' || guia_modelo || ''',' || id_guia_tipo || ',' || id_proc_tipo || ',' || codigo_temp || ');' from projudi.guia_modelo 
where id_proc_tipo in (
        select id_proc_tipo from projudi.proc_tipo
        where id_proc_tipo in (215,216,361,217,1303,295,374,375,294,218,331,357,1232,1237,1264,388,1265,118,117,99,57,330,158,383,327,301,193,376,1233,347,130,100,349,344,358,157,1261,1260,156,1316,
        1238,1273,1229,1294,380,1236,306,1239,1262,132,138,131,112,1257,1226,234,64,1240,155,368,153,93,151,150,152,148,149,147,305,1291,1317,341,1235,144,167,237,111,865,121,284,240,1330,1331,1327,1324,
        1325,1326,1323,303,1297,1292,1140,52,309,97,241,129,304,1278,352,1266,116,1269,354,142,1137,362,978,242,340,298,1293,187,124,127,293,126,145,1279,1275,146,299,297,175,355,162,139,140,141,176,346,
        350,382,296,336,86,321,161,1241,377,378,381,1242,348,143,1274,1289,125,106,134,1270,185,386,325,353,1250,300,1250,98,332,256,128,95,319,328,329,1329,1328,1322,1321,318)
)
and id_guia_tipo = 1
and codigo_temp = 1







insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20191,'INICIAL - INDENIZACAO POR ACIDENTE DE TRABALHO',1,52,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20196,'INICIAL - ALVARA JUDICIAL',1,57,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20203,'INICIAL - EMBARGOS',1,64,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20232,'INICIAL - EXCECAO DE COISA JULGADA',1,93,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20234,'INICIAL - TERMO CIRCUNSTANCIADO DE OCORRENCIA',1,95,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20236,'INICIAL - INFORMACAO',1,97,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20237,'INICIAL - SOLICITACAO',1,98,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20238,'INICIAL - ALVARA DE LIBERACAO',1,99,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20239,'INICIAL - AUTORIZACAO JUDICIAL',1,100,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20245,'INICIAL - RESTAURAÇÃO DE AUTOS ( CPC )',1,106,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20250,'INICIAL - HOMOLOGAÇÃO DE TRANSAÇÃO EXTRAJUDICIAL ( L.E.; CPC )',1,111,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20255,'INICIAL - JUSTIFICAÇÃO ( CPC )',1,116,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20256,'INICIAL - AGRAVO DE INSTRUMENTO ( CPC )',1,117,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20257,'INICIAL - AGRAVO DE INSTRUMENTO EM RECURSO EXTRAORDINÁRIO ( CPC )',1,118,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20260,'INICIAL - IMPUGNAÇÃO AO CUMPRIMENTO DE SENTENÇA ( CPC )',1,121,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20263,'INICIAL - NOTÍCIA-CRIME ( CPP )',1,124,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20265,'INICIAL - PEDIDO DE ARQUIVAMENTO EM REPRESENTAÇÃO CRIMINAL ( CPP )',1,126,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20266,'INICIAL - NOTIFICAÇÃO PARA EXPLICAÇÕES ( CP )',1,127,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20267,'INICIAL - TERMO CIRCUNSTANCIADO ( LEI ESPARSA )',1,128,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20268,'INICIAL - INQUÉRITO POLICIAL ( CPP )',1,129,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20269,'INICIAL - AUTO DE PRISÃO EM FLAGRANTE ( CF )',1,130,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20270,'INICIAL - CRIMES DE RESPONSABILIDADE DOS FUNCIONÁRIOS PÚBLICOS ( CPP E L.E )',1,131,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20271,'INICIAL - CRIMES DE CALÚNIA, INJÚRIA E DIFAMAÇÃO DE COMPETÊNCIA DO JUIZ SINGULAR ( CPP )',1,132,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20273,'INICIAL - RESTAURAÇÃO DE AUTOS ( CPP )',1,134,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20277,'INICIAL - CRIMES DE IMPRENSA ( L.E )',1,138,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20278,'INICIAL - PROCEDIMENTO DO JUIZADO ESPECIAL CRIMINAL - SUMARIÍSSIMO ( L.E. )',1,139,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20279,'INICIAL - PROCEDIMENTO ESPECIAL DA LEI ANTITÓXICOS ( 11.343 )',1,140,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20280,'INICIAL - PROCEDIMENTO ESPECIAL DOS CRIMES DE ABUSO DE AUTORIDADE ( L.E )',1,141,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20281,'INICIAL - LIBERDADE PROVISÓRIA COM OU SEM FIANÇA ( CPP )',1,142,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20282,'INICIAL - RELAXAMENTO DE PRISÃO ( CPP )',1,143,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20283,'INICIAL - HABEAS CORPUS ( CF; CPP )',1,144,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20284,'INICIAL - PEDIDO DE BUSCA E APREENSÃO CRIMINAL ( CPP )',1,145,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20285,'INICIAL - PEDIDO DE PRISÃO PREVENTIVA ( CPP )',1,146,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20286,'INICIAL - EXCEÇÃO DE SUSPEIÇÃO ( CPP )',1,147,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20287,'INICIAL - EXCEÇÃO DE INCOMPETÊNCIA DE JUÍZO ( CPP )',1,148,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20288,'INICIAL - LITISPENDÊNCIA ( CPP )',1,149,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20289,'INICIAL - ILEGITIMIDADE DE PARTE ( CPP )',1,150,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20290,'INICIAL - COISA JULGADA ( CPP )',1,151,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20291,'INICIAL - EXCEÇÃO DE IMPEDIMENTO ( CPP )',1,152,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20292,'INICIAL - EXCEÇÃO DA VERDADE ( CPP )',1,153,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20294,'INICIAL - EMBARGOS DE TERCEIRO ( CPP )',1,155,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20295,'INICIAL - CARTA DE ORDEM ( CPC - APLICAÇÃO ANALÓGICA )',1,156,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20296,'INICIAL - CARTA PRECATÓRIA ( CPP )',1,157,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20297,'INICIAL - APELAÇÃO ( CPP E L.E )',1,158,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20300,'INICIAL - RECURSO DE SENTENÇA CRIMINAL ( LEI ESPARSA )',1,161,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20301,'INICIAL - PROCEDIMENTO DO JUIZADO ESPECIAL CÍVEL ( LEIS 9099/95 E 10259/01 )',1,162,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20306,'INICIAL - HABEAS CORPUS ( CF E LIVRO III, TÍTULO II, CAPÍTULO X DO CÓDIGO DE PROCESSO PENAL )',1,167,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20314,'INICIAL - PETIÇÃO',1,175,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20315,'INICIAL - PROCEDIMENTO INVESTIGATÓRIO DO MP (PEÇAS DE INFORMAÇÃO) ( CPP )',1,176,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20326,'INICIAL - MEDIDAS PROTETIVAS DE URGÊNCIA (LEI MARIA DA PENHA)',1,187,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20354,'INICIAL - AÇÃO CIVIL COLETIVA ( L.E. )',1,215,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20355,'INICIAL - AÇÃO CIVIL DE IMPROBIDADE ADMINISTRATIVA ( LEI 8.429/92   )',1,216,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20356,'INICIAL - AÇÃO CIVIL PÚBLICA ( L.E. )',1,217,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20357,'INICIAL - AÇÃO POPULAR ( L.E. )',1,218,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20373,'INICIAL - DÚVIDA ( L.E. )',1,234,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20376,'INICIAL - HABEAS DATA ( L.E. )',1,237,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20380,'INICIAL - INQUÉRITO EXTRAJUDICIAL ( L.E. )',1,241,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20381,'INICIAL - MANDADO DE SEGURANÇA COLETIVO ( CF; LEI 8437/92 )',1,242,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20395,'INICIAL - SUPRIMENTO DE IDADE E/OU CONSENTIMENTO ( CC )',1,256,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20423,'INICIAL - IMPUGNAÇÃO AO PEDIDO DE ASSISTÊNCIA LITISCONSORCIAL OU SIMPLES ( CPC )',1,284,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20432,'INICIAL - NOTIFICAÇÃO PARA EXPLICAÇÕES (LEI DE IMPRENSA) ( LEI ESPARSA )',1,293,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20433,'INICIAL - AÇÃO PENAL DE COMPETÊNCIA DO JÚRI ( CPP )',1,294,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20434,'INICIAL - AÇÃO PENAL - PROCEDIMENTO ORDINÁRIO ( CPP )',1,295,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20435,'INICIAL - PROCESSO SUMÁRIO (DETENÇÃO) ( CPP )',1,296,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20436,'INICIAL - PEDIDO DE QUEBRA DE SIGILO DE DADOS E/OU TELEFÔNICO ( L.E )',1,297,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20437,'INICIAL - MEDIDAS INVESTIGATÓRIAS SOBRE ORGANIZAÇÕES CRIMINOSAS ( LEI ESPARSA )',1,298,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20438,'INICIAL - PEDIDO DE PRISÃO TEMPORÁRIA ( L.E )',1,299,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20439,'INICIAL - SEQÜESTRO ( CPP )',1,300,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20440,'INICIAL - ARRESTO / HIPOTECA LEGAL ( CPP )',1,301,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20442,'INICIAL - INCIDENTE DE FALSIDADE ( CPP )',1,303,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20443,'INICIAL - INSANIDADE MENTAL DO ACUSADO ( CPP )',1,304,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20444,'INICIAL - EXECUÇÃO DA PENA ( LEI 7210 - LEP )',1,305,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20445,'INICIAL - CONVERSÃO DE PENA ( L.E )',1,306,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20448,'INICIAL - INDULTO ( L.E )',1,309,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20457,'INICIAL - UNIFICAÇÃO DE PENAS ( CP )',1,318,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20458,'INICIAL - TRANSFERÊNCIA ENTRE ESTABELECIMENTOS PENAIS ( LEP )',1,319,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20460,'INICIAL - REABILITAÇÃO ( CP  )',1,321,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20464,'INICIAL - REVISÃO JUDICIAL DE DECISÃO DO CONSELHO TUTELAR ( L. 8069/90 )',1,325,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20466,'INICIAL - APURAÇÃO DE INFRAÇÃO ADMINISTRATIVA ÀS NORMAS DE PROTEÇÃO À CRIANÇA OU ADOLESCENTE ( L. 8069/90 )',1,327,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20467,'INICIAL - TUTELA ( L. 8069/90 )',1,328,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20468,'INICIAL - TUTELA C/C DESTITUIÇÃO DO PODER FAMILIAR (  )',1,329,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20469,'INICIAL - ADOÇÃO ( L. 8069/90 )',1,330,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20470,'INICIAL - ADOÇÃO C/C DESTITUIÇÃO DO PODER FAMILIAR ( L. 8069/90 )',1,331,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20471,'INICIAL - SUPRIMENTO DE CAPACIDADE OU DE CONSENTIMENTO PARA CASAR ( L. 8069/90 )',1,332,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20475,'INICIAL - PROVIDÊNCIA  ( ECA )',1,336,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20479,'INICIAL - MEDIDAS DE PROTEÇÃO À CRIANÇA E ADOLESCENTE (  )',1,340,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20480,'INICIAL - EXECUÇÃO DE MULTA ( ECA )',1,341,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20483,'INICIAL - CARTA DE ORDEM (  )',1,344,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20485,'INICIAL - PROCEDIMENTOS INVESTIGATÓRIOS ( ECA )',1,346,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20486,'INICIAL - AUTO DE APREENSÃO EM FLAGRANTE ( ECA )',1,347,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20487,'INICIAL - RELATÓRIO DE INVESTIGAÇÕES (  )',1,348,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20488,'INICIAL - BOLETIM DE OCORRÊNCIA CIRCUNSTANCIADA ( ECA )',1,349,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20489,'INICIAL - PROCESSO DE APURAÇÃO DE ATO INFRACIONAL ( ECA )',1,350,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20491,'INICIAL - INTERNAÇÃO SEM ATIVIDADES EXTERNAS ( ECA )',1,352,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20492,'INICIAL - SEMILIBERDADE ( ECA )',1,353,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20493,'INICIAL - LIBERDADE ASSISTIDA ( ECA )',1,354,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20494,'INICIAL - PRESTAÇÃO DE SERVIÇOS A COMUNIDADE ( ECA )',1,355,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20496,'INICIAL - ADVERTÊNCIA  ( ECA )',1,357,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20497,'INICIAL - CARTA DE ORDEM (  )',1,358,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20500,'INICIAL - AÇÃO CIVIL PÚBLICA ( L. 8069/90 )',1,361,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20507,'INICIAL - EMBARGOS DO ACUSADO ( CPP )',1,368,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20513,'INICIAL - AÇÃO PENAL - PROCEDIMENTO SUMÁRIO ( CP )',1,374,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20514,'INICIAL - AÇÃO PENAL - PROCEDIMENTO SUMARÍSSIMO ( CPP )',1,375,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20515,'INICIAL - ARGUIÇÃO DE INCONSTITUCIONALIDADE',1,376,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20516,'INICIAL - RECURSO ESPECIAL',1,377,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20517,'INICIAL - RECURSO EXTRAORDINÁRIO',1,378,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20519,'INICIAL - CONFLITO DE COMPETÊNCIA',1,380,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20520,'INICIAL - REEXAME NECESSÁRIO',1,381,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20521,'INICIAL - PROCESSO FÍSICO - CÁLCULO DE LIQUIDAÇÃO DE PENA',1,382,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20522,'INICIAL - APELAÇÃO / REEXAME NECESSÁRIO ',1,383,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20525,'INICIAL - AÇÃO RESCISÓRIA',1,386,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (20527,'INICIAL - DIRETA DE INCONSTITUCIONALIDADE',1,388,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (21434,'INICIAL - Ação Direta de Inconstitucionalidade',1,1303,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (21436,'INICIAL - Carta Rogatória Cível',1,1316,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (21437,'INICIAL - Homologação de Transação Extrajudicial ( L.E. CPC )',1,865,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (21440,'INICIAL - Mandado de Segurança Coletivo ( CF, Lei 8437/92 )',1,978,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (21444,'INICIAL - Direta de Inconstitucionalidade',1,1226,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (21447,'INICIAL - Comunicação',1,1229,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (21450,'INICIAL - Agravo Regimental',1,1232,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (21451,'INICIAL - Argüição de Inconstitucionalidade',1,1233,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (21453,'INICIAL - Habeas Corpus',1,1235,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (21454,'INICIAL - Conflito de Jurisdição',1,1236,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (21455,'INICIAL - Agravo de Execução Penal',1,1237,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (21456,'INICIAL - Carta Testemunhável',1,1238,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (21457,'INICIAL - Correição Parcial',1,1239,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (21458,'INICIAL - Embargos Infringentes e de Nulidade',1,1240,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (21459,'INICIAL - Recurso em Sentido Estrito',1,1241,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (21460,'INICIAL - Reexame Necessário',1,1242,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (21468,'INICIAL - Sindicância',1,1250,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (21475,'INICIAL - Declaratória de Constitucionalidade',1,1257,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (21478,'INICIAL - Carta Precatória Infracional',1,1260,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (21479,'INICIAL - Carta Precatória Infância E Juventude',1,1261,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (21480,'INICIAL - Correição Parcial',1,1262,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (21482,'INICIAL - Agravo de Instrumento em Recurso Especial',1,1264,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (21483,'INICIAL - Agravo de Instrumento em Recurso Extraordinário',1,1265,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (21484,'INICIAL - Investigação contra magistrado',1,1266,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (21487,'INICIAL - Justificação Criminal',1,1269,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (21488,'INICIAL - Restituição de Coisas Apreendidas - Infracional',1,1270,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (21491,'INICIAL - Cautelar Inominada Criminal',1,1273,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (21492,'INICIAL - Remição de Pena',1,1274,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (21493,'INICIAL - Pedido de Medida de Proteção',1,1275,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (21496,'INICIAL - Internação Provisória',1,1278,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (21497,'INICIAL - Pedido De Desinternação/Reavaliação/Substituição/Suspensão da Medida',1,1279,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (21507,'INICIAL - Renovação de Permanência em Estabelecimento Penal Federal',1,1289,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (21509,'INICIAL - Execução de Medida de Segurança',1,1291,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (21510,'INICIAL - Incidente de Sanidade Mental',1,1292,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (21511,'INICIAL - Medidas Protetivas - Estatuto do Idoso ',1,1293,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (21512,'INICIAL - Conflito de Competência',1,1294,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (21515,'INICIAL - Incidente de Falsidade',1,1297,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (21521,'INICIAL - Mandado de Injunção',1,1137,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (21524,'INICIAL - Incidente de Suspeição',1,1140,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (21529,'INICIAL - Execução de Medidas Sócio-Educativas',1,1317,1);
insert into projudi.guia_modelo (id_guia_modelo, guia_modelo, id_guia_tipo, id_proc_tipo, codigo_temp) values (21490,'INICIAL - Reclamação Pré-processual',1,1272,1);




insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21490, 190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21490, 9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21490, 9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21490, 9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20250,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20250,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20250,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20250,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20255,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20255,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20255,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20255,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20260,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20260,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20260,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20260,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20267,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20267,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20267,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20267,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20285,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20285,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20285,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20285,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20287,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20287,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20287,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20287,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20288,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20288,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20288,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20288,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20290,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20290,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20290,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20290,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20291,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20291,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20291,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20291,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20295,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20295,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20295,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20295,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20300,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20300,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20300,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20300,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20315,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20315,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20315,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20315,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20356,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20356,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20356,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20356,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20436,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20436,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20436,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20436,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20457,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20457,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20457,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20457,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20468,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20468,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20468,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20468,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20470,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20470,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20470,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20470,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20488,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20488,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20488,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20488,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21482,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21482,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21482,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21482,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20494,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20494,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20494,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20494,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20522,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20522,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20522,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20522,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21436,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21436,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21436,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21436,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21483,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21483,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21483,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21483,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20256,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20256,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20256,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20256,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20271,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20271,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20271,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20271,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20286,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20286,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20286,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20286,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20301,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20301,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20301,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20301,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20489,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20489,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20489,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20489,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20497,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20497,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20497,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20497,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20519,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20519,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20519,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20519,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20520,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20520,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20520,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20520,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21440,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21440,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21440,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21440,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21479,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21479,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21479,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21507,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21507,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21507,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21507,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21511,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21511,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21511,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21511,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20196,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20196,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20196,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20196,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20232,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20232,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20232,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20232,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20238,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20238,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20238,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20238,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20239,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20239,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20239,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20239,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20296,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20296,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20296,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20297,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20297,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20297,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20297,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20479,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20479,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20479,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20479,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20507,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20507,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20507,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20507,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20517,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20517,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20517,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20517,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21437,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21437,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21437,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21437,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21460,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21460,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21460,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21460,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21480,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21480,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21480,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21480,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21488,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21488,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21488,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21488,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21510,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21510,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21510,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21510,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20191,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20191,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20191,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20191,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20236,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20236,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20236,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20236,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20237,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20237,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20237,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20237,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20263,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20263,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20263,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20263,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20277,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20277,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20277,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20277,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20278,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20278,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20278,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20278,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20282,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20282,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20282,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20282,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20283,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20283,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20283,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20283,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20289,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20289,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20289,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20289,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20292,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20292,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20292,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20292,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20294,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20294,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20294,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20294,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20380,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20380,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20380,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20380,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20395,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20395,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20395,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20395,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20433,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20433,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20433,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20433,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20437,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20437,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20437,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20437,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20443,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20443,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20443,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20443,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20444,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20444,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20444,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20444,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20469,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20469,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20469,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20469,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20471,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20471,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20471,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20471,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20491,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20491,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20491,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20491,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20493,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20493,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20493,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20493,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20500,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20500,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20500,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20500,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21447,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21447,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21447,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21447,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21468,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21468,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21468,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21468,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21484,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21484,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21484,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21484,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21496,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21496,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21496,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21496,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21512,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21512,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21512,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21512,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21515,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21515,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21515,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21515,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20270,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20270,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20270,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20270,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20279,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20279,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20279,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20279,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20284,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20284,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20284,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20284,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20314,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20314,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20314,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20314,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20376,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20376,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20376,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20376,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20460,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20460,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20460,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20460,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20483,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20483,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20483,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20483,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20515,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20515,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20515,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20515,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20516,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20516,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20516,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20516,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21456,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21456,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21456,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21456,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20234,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20234,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20234,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20234,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20268,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20268,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20268,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20268,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20273,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20273,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20273,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20273,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20281,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20281,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20281,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20281,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20357,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20357,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20357,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20357,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20435,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20435,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20435,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20435,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20439,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20439,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20439,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20439,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20448,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20448,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20448,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20448,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20464,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20464,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20464,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20464,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20480,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20480,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20480,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20480,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20485,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20485,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20485,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20485,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20496,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20496,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20496,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20496,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20513,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20513,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20513,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20513,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20514,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20514,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20514,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20514,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21434,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21434,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21434,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21434,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21451,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21451,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21451,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21451,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21453,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21453,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21453,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21453,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21454,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21454,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21454,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21454,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21457,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21457,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21457,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21457,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21458,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21458,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21458,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21458,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21459,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21459,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21459,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21459,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20280,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20280,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20280,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20280,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20326,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20326,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20326,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20326,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20423,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20423,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20423,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20423,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20432,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20432,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20432,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20432,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20434,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20434,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20434,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20434,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20438,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20438,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20438,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20438,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20440,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20440,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20440,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20440,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20445,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20445,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20445,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20445,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20466,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20466,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20466,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20466,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20467,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20467,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20467,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20467,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20475,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20475,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20475,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20475,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20525,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20525,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20525,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20525,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20527,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20527,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20527,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20527,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21444,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21444,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21444,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21444,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21450,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21450,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21450,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21450,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21478,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21478,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21478,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21487,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21487,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21487,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21487,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21491,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21491,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21491,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21491,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21497,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21497,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21497,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21497,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20203,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20203,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20203,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20203,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20245,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20245,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20245,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20245,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20257,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20257,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20257,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20257,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20265,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20265,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20265,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20265,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20266,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20266,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20266,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20266,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20269,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20269,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20269,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20269,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20306,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20306,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20306,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20306,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20354,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20354,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20354,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20354,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20355,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20355,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20355,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20355,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20373,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20373,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20373,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20373,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20381,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20381,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20381,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20381,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20442,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20442,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20442,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20442,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20458,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20458,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20458,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20458,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20486,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20486,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20486,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20486,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20487,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20487,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20487,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20487,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20492,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20492,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20492,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20492,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20521,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20521,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20521,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (20521,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21455,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21455,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21455,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21455,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21475,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21475,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21475,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21475,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21492,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21492,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21492,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21492,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21493,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21493,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21493,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21493,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21509,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21509,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21509,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21509,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21529,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21529,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21529,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21529,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21521,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21521,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21521,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21521,9023);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21524,190);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21524,9018);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21524,9020);
insert into projudi.guia_custa_modelo (id_guia_modelo, id_custa) values (21524,9023);