CREATE OR REPLACE VIEW VIEW_PROC_PARTE_DEBITO_FISICO
AS SELECT PPD.ID_PROC_PARTE_DEBITO_FISICO AS ID_PROC_PARTE_DEBITO_FISICO,
	PPD.ID_PROC_DEBITO                   AS ID_PROC_DEBITO,
	PD.PROC_DEBITO                       AS PROC_DEBITO,
	PPD.PROC_NUMERO                      AS PROC_NUMERO,
	PPD.CODG_ESCRIVANIA                  AS CODG_ESCRIVANIA,
	PPD.DESC_ESCRIVANIA                  AS DESC_ESCRIVANIA,
	PPD.ISN_PARTE                        AS ISN_PARTE,
	PPD.NOME_PARTE                       AS NOME_PARTE,
	PPD.NOME_SIMPLIFICADO                AS NOME_SIMPLIFICADO,
	PPD.TIPO_PARTE                       AS TIPO_PARTE,
	PPD.CPF_CNPJ_PARTE                   AS CPF_CNPJ_PARTE,
	PPD.NUMERO_GUIA_COMPLETO             AS NUMERO_GUIA_COMPLETO,
	PPD.VALOR_GUIA                       AS VALOR_GUIA,
	PPD.NUMERO_PROAD                     AS NUMERO_PROAD,
	PPD.STATUS                           AS STATUS,
	PPD.DATA_BAIXA                       AS DATA_BAIXA,
	PPD.CODIGO_TEMP                      AS CODIGO_TEMP,
	PPD.ENDERECO_PARTE_PROAD             AS ENDERECO_PARTE_PROAD,
	PPD.DATA_VENCIMENTO_PROAD            AS DATA_VENCIMENTO_PROAD,
	PPD.VALOR_CREDITO_PROAD              AS VALOR_CREDITO_PROAD,
	PPD.LIBERADO_CADIN                   AS LIBERADO_CADIN
  FROM PROJUDI.PROC_PARTE_DEBITO_FISICO PPD
  INNER JOIN PROJUDI.PROC_DEBITO PD ON PD.ID_PROC_DEBITO = PPD.ID_PROC_DEBITO