ALTER TABLE PROC_PARTE_DEBITO RENAME COLUMN LIBERADO_CADIN TO DIVIDA_SOLIDARIA;

ALTER TABLE PROC_PARTE_DEBITO MODIFY DIVIDA_SOLIDARIA CHAR(1) DEFAULT '0';

CREATE OR REPLACE FORCE VIEW PROJUDI.VIEW_PROC_PARTE_DEBITO AS 
  SELECT PPD.ID_PROC_PARTE_DEBITO AS ID_PROC_PARTE_DEBITO,
    PPD.ID_PROC_DEBITO            AS ID_PROC_DEBITO,
    PD.PROC_DEBITO                AS PROC_DEBITO,
    PPD.ID_PROC_PARTE             AS ID_PROC_PARTE,
    PP.NOME                       AS NOME,
    PP.NOME_SIMPLIFICADO          AS NOME_SIMPLIFICADO,
    PPT.PROC_PARTE_TIPO_CODIGO    AS PROC_PARTE_TIPO_CODIGO,
    PPT.PROC_PARTE_TIPO           AS PROC_PARTE_TIPO,
    PPD.CODIGO_TEMP               AS CODIGO_TEMP,
    PP.CPF                        AS CPF,
    PP.CNPJ                       AS CNPJ,
    P.ID_PROC                     AS ID_PROC,
    (P.PROC_NUMERO
    || '.'
    || P.DIGITO_VERIFICADOR)      AS PROC_NUMERO,
    LPAD(P.PROC_NUMERO, 7, '0')
    || '.'
    || LPAD (P.DIGITO_VERIFICADOR, 2, '0') 
    || '.'
    || LPAD (P.ANO, 4, '0') 
    || '.'
    || '8' 
    || '.'
    || '09' 
    || '.'
    || LPAD (P.FORUM_CODIGO, 4, '0') AS PROC_NUMERO_COMPLETO,
    P.PROC_NUMERO                    AS PROCESSO_NUMERO,
    P.DIGITO_VERIFICADOR             AS DIGITO_VERIFICADOR,
    P.ID_SERV                        AS ID_SERV,
    S.SERV                           AS SERV,
    GE.ID_GUIA_EMIS                  AS ID_GUIA_EMIS,
    GE.NUMERO_GUIA_COMPLETO          AS NUMERO_GUIA_COMPLETO,
    GT.ID_GUIA_TIPO                  AS ID_GUIA_TIPO,
    GT.GUIA_TIPO                     AS GUIA_TIPO,
    GS.ID_GUIA_STATUS                AS ID_GUIA_STATUS,
    GS.GUIA_STATUS                   AS GUIA_STATUS,
    (SELECT SUM(VALOR_CALCULADO) 
        FROM PROJUDI.GUIA_ITEM GI
     WHERE GI.ID_GUIA_EMIS = GE.ID_GUIA_EMIS) AS VALOR_TOTAL_GUIA,
    PPD.NUMERO_PROAD                 AS NUMERO_PROAD,
    PPD.ID_PROC_DEBITO_STATUS        AS ID_PROC_DEBITO_STATUS,
    PDS.PROC_DEBITO_STATUS           AS PROC_DEBITO_STATUS,
    PPD.DATA_BAIXA                   AS DATA_BAIXA,
    PPD.DIVIDA_SOLIDARIA             AS DIVIDA_SOLIDARIA,
    ENDERECO_PARTE_PROAD             AS ENDERECO_PARTE_PROAD,
    DATA_VENCIMENTO_PROAD            AS DATA_VENCIMENTO_PROAD,
    VALOR_CREDITO_PROAD              AS VALOR_CREDITO_PROAD
  FROM PROJUDI.PROC_PARTE_DEBITO PPD
  INNER JOIN PROJUDI.PROC_DEBITO PD ON PD.ID_PROC_DEBITO = PPD.ID_PROC_DEBITO
  INNER JOIN PROJUDI.PROC_DEBITO_STATUS PDS ON PDS.ID_PROC_DEBITO_STATUS = PPD.ID_PROC_DEBITO_STATUS
  INNER JOIN PROJUDI.PROC_PARTE PP ON PP.ID_PROC_PARTE = PPD.ID_PROC_PARTE
  INNER JOIN PROJUDI.PROC_PARTE_TIPO PPT ON PPT.ID_PROC_PARTE_TIPO = PP.ID_PROC_PARTE_TIPO
  INNER JOIN PROJUDI.PROC P ON PP.ID_PROC = P.ID_PROC
  INNER JOIN PROJUDI.SERV S ON S.ID_SERV = P.ID_SERV
  LEFT JOIN (PROJUDI.GUIA_EMIS GE
  INNER JOIN PROJUDI.GUIA_MODELO GM ON GM.ID_GUIA_MODELO = GE.ID_GUIA_MODELO
  INNER JOIN PROJUDI.GUIA_TIPO GT ON GT.ID_GUIA_TIPO = GM.ID_GUIA_TIPO
  INNER JOIN PROJUDI.GUIA_STATUS GS ON GS.ID_GUIA_STATUS = GE.ID_GUIA_STATUS)
   ON GE.ID_GUIA_EMIS = PPD.ID_GUIA_EMIS;