ALTER TABLE PROJUDI.PROC_PARTE_DEBITO ADD ID_GUIA_EMIS NUMBER(24);

ALTER TABLE PROJUDI.PROC_PARTE_DEBITO ADD NUMERO_PROAD NUMBER(15);

ALTER TABLE PROJUDI.PROC_PARTE_DEBITO ADD STATUS NUMBER(5) DEFAULT 1 NOT NULL;

ALTER TABLE PROJUDI.PROC_PARTE_DEBITO ADD DATA_BAIXA DATE;

ALTER TABLE PROC_PARTE_DEBITO ADD CONSTRAINT PROCPARTEDEBITO_GUIAEMIS FOREIGN KEY (ID_GUIA_EMIS)
	  REFERENCES GUIA_EMIS (ID_GUIA_EMIS); 

CREATE OR REPLACE FORCE VIEW PROJUDI.VIEW_PROC_PARTE_DEBITO AS 
  SELECT PPD.ID_PROC_PARTE_DEBITO AS ID_PROC_PARTE_DEBITO,
    PPD.ID_PROC_DEBITO            AS ID_PROC_DEBITO,
    PD.PROC_DEBITO                AS PROC_DEBITO,
    PPD.ID_PROC_PARTE             AS ID_PROC_PARTE,
    PP.NOME                       AS NOME,
    PP.NOME_SIMPLIFICADO		  AS NOME_SIMPLIFICADO,
    PPD.CODIGO_TEMP               AS CODIGO_TEMP,
    PP.CPF                        AS CPF,
    PP.CNPJ                       AS CNPJ,
    P.ID_PROC                     AS ID_PROC,
    (P.PROC_NUMERO
    || '.'
    || P.DIGITO_VERIFICADOR)      AS PROC_NUMERO,
    LPAD(P.PROC_NUMERO, 7, '0')
    || '.'
    || LPAD (P.DIGITO_VERIFICADOR, 2, '0') 
    || '.'
    || LPAD (P.ANO, 4, '0') 
    || '.'
    || '8' 
    || '.'
    || '09' 
    || '.'
    || LPAD (P.FORUM_CODIGO, 4, '0') AS PROC_NUMERO_COMPLETO,
    P.PROC_NUMERO 				     AS PROCESSO_NUMERO,
    P.DIGITO_VERIFICADOR             AS DIGITO_VERIFICADOR,
    P.ID_SERV                        AS ID_SERV,
	S.SERV                           AS SERV,
	GE.ID_GUIA_EMIS                  AS ID_GUIA_EMIS,
	GE.NUMERO_GUIA_COMPLETO          AS NUMERO_GUIA_COMPLETO,
	GT.ID_GUIA_TIPO                  AS ID_GUIA_TIPO,
	GT.GUIA_TIPO                     AS GUIA_TIPO,
	GS.ID_GUIA_STATUS                AS ID_GUIA_STATUS,
	GS.GUIA_STATUS                   AS GUIA_STATUS,
	(SELECT SUM(VALOR_CALCULADO) 
	    FROM PROJUDI.GUIA_ITEM GI
	 WHERE GI.ID_GUIA_EMIS = GE.ID_GUIA_EMIS) AS VALOR_TOTAL_GUIA,
	PPD.NUMERO_PROAD                 AS NUMERO_PROAD,
	PPD.STATUS                       AS STATUS,
	PPD.DATA_BAIXA                   AS DATA_BAIXA
  FROM PROJUDI.PROC_PARTE_DEBITO PPD
  INNER JOIN PROJUDI.PROC_DEBITO PD ON PD.ID_PROC_DEBITO = PPD.ID_PROC_DEBITO
  INNER JOIN PROJUDI.PROC_PARTE PP ON PP.ID_PROC_PARTE = PPD.ID_PROC_PARTE
  INNER JOIN PROJUDI.PROC P ON PP.ID_PROC = P.ID_PROC
  INNER JOIN PROJUDI.SERV S ON S.ID_SERV = P.ID_SERV
  LEFT JOIN (PROJUDI.GUIA_EMIS GE
  INNER JOIN PROJUDI.GUIA_MODELO GM ON GM.ID_GUIA_MODELO = GE.ID_GUIA_MODELO
  INNER JOIN PROJUDI.GUIA_TIPO GT ON GT.ID_GUIA_TIPO = GM.ID_GUIA_TIPO
  INNER JOIN PROJUDI.GUIA_STATUS GS ON GS.ID_GUIA_STATUS = GE.ID_GUIA_STATUS)
   ON GE.ID_GUIA_EMIS = PPD.ID_GUIA_EMIS;