--------------------------------------------------------
--  Arquivo criado - Segunda-feira-Fevereiro-18-2013   
--------------------------------------------------------

--------------------------------------------------------
--  DDL for Sequence AFASTAMENTO_ID_AFASTAMENTO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."AFASTAMENTO_ID_AFASTAMENTO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."AFASTAMENTO_ID_AFASTAMENTO_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence AGENCIA_ID_AGENCIA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."AGENCIA_ID_AGENCIA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."AGENCIA_ID_AGENCIA_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence ALCUNHA_ID_ALCUNHA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."ALCUNHA_ID_ALCUNHA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 93 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."ALCUNHA_ID_ALCUNHA_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence AREADISTRIBUICAO_ID_AREADISTRI
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."AREADISTRIBUICAO_ID_AREADISTRI"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 578 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."AREADISTRIBUICAO_ID_AREADISTRI" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence AREA_ID_AREA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."AREA_ID_AREA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 4 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."AREA_ID_AREA_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence ARQUIVO_BANCO_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."ARQUIVO_BANCO_ID_SEQ"  MINVALUE 1 MAXVALUE 10000000000000000000000 INCREMENT BY 1 START WITH 22456 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ARQUIVO_ID_ARQUIVO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."ARQUIVO_ID_ARQUIVO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 12454901 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."ARQUIVO_ID_ARQUIVO_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence ARQUIVOPALAVRA_ID_ARQUIVOPALAV
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."ARQUIVOPALAVRA_ID_ARQUIVOPALAV"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 123391626 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."ARQUIVOPALAVRA_ID_ARQUIVOPALAV" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence ARQUIVOTIPO_ID_ARQUIVOTIPO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."ARQUIVOTIPO_ID_ARQUIVOTIPO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 150 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."ARQUIVOTIPO_ID_ARQUIVOTIPO_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence ARRECADACAOCUSTA_ID_ARRECADACA
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."ARRECADACAOCUSTA_ID_ARRECADACA"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 62 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."ARRECADACAOCUSTA_ID_ARRECADACA" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence ASSUNTO_ID_ASSUNTO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."ASSUNTO_ID_ASSUNTO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 2406 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."ASSUNTO_ID_ASSUNTO_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence ASSUNTOTEMP_ID_ASSUNTO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."ASSUNTOTEMP_ID_ASSUNTO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."ASSUNTOTEMP_ID_ASSUNTO_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence AUDIENCIA_ID_AUDIENCIA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."AUDIENCIA_ID_AUDIENCIA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 3315482 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."AUDIENCIA_ID_AUDIENCIA_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence AUDIENCIAPROCESSO_ID_AUDIENCIA
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."AUDIENCIAPROCESSO_ID_AUDIENCIA"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 3338518 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."AUDIENCIAPROCESSO_ID_AUDIENCIA" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence AUDIENCIAPROCESSORESPONSAVEL_I
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."AUDIENCIAPROCESSORESPONSAVEL_I"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 632737 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."AUDIENCIAPROCESSORESPONSAVEL_I" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence AUDIENCIAPROCESSOSTATUS_ID_AUD
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."AUDIENCIAPROCESSOSTATUS_ID_AUD"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 36 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."AUDIENCIAPROCESSOSTATUS_ID_AUD" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence AUDIENCIATIPO_ID_AUDIENCIATIPO
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."AUDIENCIATIPO_ID_AUDIENCIATIPO"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 17 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."AUDIENCIATIPO_ID_AUDIENCIATIPO" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence BAIRRO_BKP_06_05_2010_ID_BAIRR
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."BAIRRO_BKP_06_05_2010_ID_BAIRR"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."BAIRRO_BKP_06_05_2010_ID_BAIRR" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence BAIRRO_BKP_09_04_2010_ID_BAIRR
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."BAIRRO_BKP_09_04_2010_ID_BAIRR"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."BAIRRO_BKP_09_04_2010_ID_BAIRR" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence BAIRRO_ID_BAIRRO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."BAIRRO_ID_BAIRRO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 25921 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."BAIRRO_ID_BAIRRO_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence BANCO_ID_BANCO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."BANCO_ID_BANCO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."BANCO_ID_BANCO_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence CALCULOLIQUIDACAO_ID_CALCULOLI
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."CALCULOLIQUIDACAO_ID_CALCULOLI"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 11522 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."CALCULOLIQUIDACAO_ID_CALCULOLI" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence CARGOTIPO_ID_CARGOTIPO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."CARGOTIPO_ID_CARGOTIPO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 46 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."CARGOTIPO_ID_CARGOTIPO_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence CERTIDAOTIPO_ID_CERTIDAOTIPO_S
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."CERTIDAOTIPO_ID_CERTIDAOTIPO_S"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."CERTIDAOTIPO_ID_CERTIDAOTIPO_S" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence CERTIDAOTIPOPROCESSOTIPO_ID_CE
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."CERTIDAOTIPOPROCESSOTIPO_ID_CE"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 4 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."CERTIDAOTIPOPROCESSOTIPO_ID_CE" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence CERTIFICADOCONFIAVEL_ID_CERTIF
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."CERTIFICADOCONFIAVEL_ID_CERTIF"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 16 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."CERTIFICADOCONFIAVEL_ID_CERTIF" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence CERTIFICADO_ID_CERTIFICADO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."CERTIFICADO_ID_CERTIFICADO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 38371 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."CERTIFICADO_ID_CERTIFICADO_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence CIDADE_BKP_08_04_2010_ID_CIDAD
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."CIDADE_BKP_08_04_2010_ID_CIDAD"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."CIDADE_BKP_08_04_2010_ID_CIDAD" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence CIDADE_ID_CIDADE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."CIDADE_ID_CIDADE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 5941 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."CIDADE_ID_CIDADE_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence CIDADE_SSP_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."CIDADE_SSP_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 933002 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."CIDADE_SSP_ID_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence CIDADETEMP2_ID_CIDADE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."CIDADETEMP2_ID_CIDADE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."CIDADETEMP2_ID_CIDADE_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence CLASSIFICADOR_ID_CLASSIFICADOR
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."CLASSIFICADOR_ID_CLASSIFICADOR"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 13516 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."CLASSIFICADOR_ID_CLASSIFICADOR" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence COMARCACIDADE_ID_COMARCACIDADE
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."COMARCACIDADE_ID_COMARCACIDADE"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."COMARCACIDADE_ID_COMARCACIDADE" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence COMARCA_ID_COMARCA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."COMARCA_ID_COMARCA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 128 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."COMARCA_ID_COMARCA_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence CONDENACAOEXECUCAO_ID_CONDENAC
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."CONDENACAOEXECUCAO_ID_CONDENAC"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 48144 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."CONDENACAOEXECUCAO_ID_CONDENAC" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence CONDENACAOEXECUCAOSITUACAO_ID_
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."CONDENACAOEXECUCAOSITUACAO_ID_"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 4 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."CONDENACAOEXECUCAOSITUACAO_ID_" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence CONTAUSUARIO_ID_CONTAUSUARIO_S
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."CONTAUSUARIO_ID_CONTAUSUARIO_S"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."CONTAUSUARIO_ID_CONTAUSUARIO_S" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence CRIMEEXECUCAO_ID_CRIMEEXECUCAO
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."CRIMEEXECUCAO_ID_CRIMEEXECUCAO"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 2294 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."CRIMEEXECUCAO_ID_CRIMEEXECUCAO" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence CUSTA_ID_CUSTA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."CUSTA_ID_CUSTA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 208 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."CUSTA_ID_CUSTA_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence CUSTAVALOR_ID_CUSTAVALOR_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."CUSTAVALOR_ID_CUSTAVALOR_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 452 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."CUSTAVALOR_ID_CUSTAVALOR_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence DELEGACIATEMP_CODDELEGACIA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."DELEGACIATEMP_CODDELEGACIA_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."DELEGACIATEMP_CODDELEGACIA_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence EMPRESATIPO_ID_EMPRESATIPO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."EMPRESATIPO_ID_EMPRESATIPO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 12 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."EMPRESATIPO_ID_EMPRESATIPO_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence ENDERECO_ID_ENDERECO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."ENDERECO_ID_ENDERECO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 1494587 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."ENDERECO_ID_ENDERECO_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence ENDERECOTEMP_ENDERECO_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."ENDERECOTEMP_ENDERECO_ID_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."ENDERECOTEMP_ENDERECO_ID_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence ESCALA_ID_ESCALA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."ESCALA_ID_ESCALA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."ESCALA_ID_ESCALA_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence ESCOLARIDADE_ID_ESCOLARIDADE_S
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."ESCOLARIDADE_ID_ESCOLARIDADE_S"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 11 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."ESCOLARIDADE_ID_ESCOLARIDADE_S" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence ESTADOCIVIL_ID_ESTADOCIVIL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."ESTADOCIVIL_ID_ESTADOCIVIL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 7 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."ESTADOCIVIL_ID_ESTADOCIVIL_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence ESTADO_ID_ESTADO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."ESTADO_ID_ESTADO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 50 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."ESTADO_ID_ESTADO_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence ESTADOTEMP_ID_ESTADO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."ESTADOTEMP_ID_ESTADO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."ESTADOTEMP_ID_ESTADO_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence ESTATISTICARELATORIOESTPROITEN
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."ESTATISTICARELATORIOESTPROITEN"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 3628 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."ESTATISTICARELATORIOESTPROITEN" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence EVENTOEXECUCAO_ID_EVENTOEXECUC
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."EVENTOEXECUCAO_ID_EVENTOEXECUC"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 64 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."EVENTOEXECUCAO_ID_EVENTOEXECUC" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence EVENTOEXECUCAOSTATUS_ID_EVENTO
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."EVENTOEXECUCAOSTATUS_ID_EVENTO"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 5 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."EVENTOEXECUCAOSTATUS_ID_EVENTO" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence EVENTOEXECUCAOTIPO_ID_EVENTOEX
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."EVENTOEXECUCAOTIPO_ID_EVENTOEX"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 9 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."EVENTOEXECUCAOTIPO_ID_EVENTOEX" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence EVENTOLOCAL_ID_EVENTOLOCAL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."EVENTOLOCAL_ID_EVENTOLOCAL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 48105 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."EVENTOLOCAL_ID_EVENTOLOCAL_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence EVENTOREGIME_ID_EVENTOREGIME_S
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."EVENTOREGIME_ID_EVENTOREGIME_S"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 117971 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."EVENTOREGIME_ID_EVENTOREGIME_S" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence FINALIDADE_ID_FINALIDADE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."FINALIDADE_ID_FINALIDADE_SEQ"  MINVALUE 1 MAXVALUE 10000000000000000000000 INCREMENT BY 1 START WITH 68 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence FORUM_ID_FORUM_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."FORUM_ID_FORUM_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 203 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."FORUM_ID_FORUM_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence GOVERNOTIPO_ID_GOVERNOTIPO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."GOVERNOTIPO_ID_GOVERNOTIPO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 4 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."GOVERNOTIPO_ID_GOVERNOTIPO_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence GRUPOARQUIVOTIPO_ID_GRUPOARQUI
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."GRUPOARQUIVOTIPO_ID_GRUPOARQUI"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 709 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."GRUPOARQUIVOTIPO_ID_GRUPOARQUI" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence GRUPO_ID_GRUPO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."GRUPO_ID_GRUPO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 67 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."GRUPO_ID_GRUPO_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence GRUPOMOVIMENTACAOTIPO_ID_GRUPO
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."GRUPOMOVIMENTACAOTIPO_ID_GRUPO"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 2047 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."GRUPOMOVIMENTACAOTIPO_ID_GRUPO" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence GRUPOPENDENCIATIPO_ID_GRUPOPEN
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."GRUPOPENDENCIATIPO_ID_GRUPOPEN"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 572 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."GRUPOPENDENCIATIPO_ID_GRUPOPEN" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence GRUPOPERMISSAO_ID_GRUPOPERMISS
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."GRUPOPERMISSAO_ID_GRUPOPERMISS"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 23112 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."GRUPOPERMISSAO_ID_GRUPOPERMISS" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence GRUPOTIPO_ID_GRUPOTIPO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."GRUPOTIPO_ID_GRUPOTIPO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 43 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."GRUPOTIPO_ID_GRUPOTIPO_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence GUIACUSTAMODELO_ID_GUIACUSTAMO
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."GUIACUSTAMODELO_ID_GUIACUSTAMO"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 25931 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."GUIACUSTAMODELO_ID_GUIACUSTAMO" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence GUIAEMISSAO_ID_GUIAEMISSAO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."GUIAEMISSAO_ID_GUIAEMISSAO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 31774 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."GUIAEMISSAO_ID_GUIAEMISSAO_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence GUIAFINALIDADEMODELO_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."GUIAFINALIDADEMODELO_ID_SEQ"  MINVALUE 1 MAXVALUE 10000000000000000000000 INCREMENT BY 1 START WITH 68 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence GUIAFINALIDMODELOCUSTA_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."GUIAFINALIDMODELOCUSTA_ID_SEQ"  MINVALUE 1 MAXVALUE 10000000000000000000000 INCREMENT BY 1 START WITH 306 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence GUIAITEM_ID_GUIAITEM_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."GUIAITEM_ID_GUIAITEM_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 162201 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."GUIAITEM_ID_GUIAITEM_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence GUIAMODELO_ID_GUIAMODELO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."GUIAMODELO_ID_GUIAMODELO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 13348 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."GUIAMODELO_ID_GUIAMODELO_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence GUIANUMERO_ID_GUIANUMERO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."GUIANUMERO_ID_GUIANUMERO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 31026 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."GUIANUMERO_ID_GUIANUMERO_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence GUIASTATUS_ID_GUIASTATUS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."GUIASTATUS_ID_GUIASTATUS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 12 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."GUIASTATUS_ID_GUIASTATUS_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence GUIATIPO_ID_GUIATIPO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."GUIATIPO_ID_GUIATIPO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 26 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."GUIATIPO_ID_GUIATIPO_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence HISTORICOLOTACAO_ID_HISTORICOL
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."HISTORICOLOTACAO_ID_HISTORICOL"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."HISTORICOLOTACAO_ID_HISTORICOL" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence JUIZ_RECURSALTEMP_IDJUIZRECURS
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."JUIZ_RECURSALTEMP_IDJUIZRECURS"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."JUIZ_RECURSALTEMP_IDJUIZRECURS" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence LOCALCUMPRIMENTOPENA_ID_LOCALC
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."LOCALCUMPRIMENTOPENA_ID_LOCALC"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 19 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."LOCALCUMPRIMENTOPENA_ID_LOCALC" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence LOCOMOCAO_ID_LOCOMOCAO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."LOCOMOCAO_ID_LOCOMOCAO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 5936 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."LOCOMOCAO_ID_LOCOMOCAO_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence LOG_ERROS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."LOG_ERROS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 16 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."LOG_ERROS_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence LOG_ID_LOG_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."LOG_ID_LOG_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 104620234 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."LOG_ID_LOG_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence LOGTIPO_ID_LOGTIPO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."LOGTIPO_ID_LOGTIPO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 44 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MANDADOJUDICIAL_ID_MANDADOJUDI
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."MANDADOJUDICIAL_ID_MANDADOJUDI"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."MANDADOJUDICIAL_ID_MANDADOJUDI" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence MANDADOTIPO_ID_MANDADOTIPO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."MANDADOTIPO_ID_MANDADOTIPO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."MANDADOTIPO_ID_MANDADOTIPO_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence MAND_JUD_STATUS_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."MAND_JUD_STATUS_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."MAND_JUD_STATUS_ID_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence MODELO_ID_MODELO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."MODELO_ID_MODELO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 39897 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."MODELO_ID_MODELO_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence MOVIMENTACAOARQUIVO_ID_MOVIMEN
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."MOVIMENTACAOARQUIVO_ID_MOVIMEN"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 10774381 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."MOVIMENTACAOARQUIVO_ID_MOVIMEN" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence MOVIMENTACAO_ID_MOVIMENTACAO_S
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."MOVIMENTACAO_ID_MOVIMENTACAO_S"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 14316611 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."MOVIMENTACAO_ID_MOVIMENTACAO_S" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence MOVIMENTACAOTIPO_ID_MOVIMENTAC
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."MOVIMENTACAOTIPO_ID_MOVIMENTAC"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 671 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence NUCLEOMPTEMP_CODNUCLEO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."NUCLEOMPTEMP_CODNUCLEO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."NUCLEOMPTEMP_CODNUCLEO_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence OBJETOPEDIDO_ID_OBJETOPEDIDO_S
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."OBJETOPEDIDO_ID_OBJETOPEDIDO_S"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 5 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."OBJETOPEDIDO_ID_OBJETOPEDIDO_S" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence OCORRENCIA_INTERRUPCAO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."OCORRENCIA_INTERRUPCAO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 16 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."OCORRENCIA_INTERRUPCAO_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PAIS_ID_PAIS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PAIS_ID_PAIS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 18 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PAIS_ID_PAIS_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PALAVRA_ID_PALAVRA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PALAVRA_ID_PALAVRA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 489938 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PALAVRA_ID_PALAVRA_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PARAMETROCOMUTACAOEXE_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PARAMETROCOMUTACAOEXE_ID_SEQ"  MINVALUE 1 MAXVALUE 10000000000000000000000 INCREMENT BY 1 START WITH 23 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PARAMETROCRIMEEXECUCAO_ID_PARA
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PARAMETROCRIMEEXECUCAO_ID_PARA"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 118 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PARAMETROCRIMEEXECUCAO_ID_PARA" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PARTETEMP_CODPARTE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PARTETEMP_CODPARTE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PARTETEMP_CODPARTE_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PENAEXECUCAOTIPO_ID_PENAEXECUC
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PENAEXECUCAOTIPO_ID_PENAEXECUC"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 5 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PENAEXECUCAOTIPO_ID_PENAEXECUC" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PENDENCIAARQUIVO_ID_PENDENCIAA
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PENDENCIAARQUIVO_ID_PENDENCIAA"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 17081918 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PENDENCIAARQUIVO_ID_PENDENCIAA" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PENDENCIA_ID_PENDENCIA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PENDENCIA_ID_PENDENCIA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 10720164 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PENDENCIA_ID_PENDENCIA_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PENDENCIARESPONSAVEL_ID_PENDEN
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PENDENCIARESPONSAVEL_ID_PENDEN"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 15415380 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PENDENCIARESPONSAVEL_ID_PENDEN" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PENDENCIASTATUS_ID_PENDENCIAST
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PENDENCIASTATUS_ID_PENDENCIAST"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 14 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PENDENCIASTATUS_ID_PENDENCIAST" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PENDENCIATIPOCONCLUSAO_ID_PEND
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PENDENCIATIPOCONCLUSAO_ID_PEND"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PENDENCIATIPOCONCLUSAO_ID_PEND" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PENDENCIATIPO_ID_PENDENCIATIPO
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PENDENCIATIPO_ID_PENDENCIATIPO"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 99 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PENDENCIATIPO_ID_PENDENCIATIPO" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PENDENCIATIPORELACIONADA_ID_PE
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PENDENCIATIPORELACIONADA_ID_PE"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 1020 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PENDENCIATIPORELACIONADA_ID_PE" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PERMISSAOESPECIAL_ID_PERMISSAO
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PERMISSAOESPECIAL_ID_PERMISSAO"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 4 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PERMISSAOESPECIAL_ID_PERMISSAO" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PERMISSAO_ID_PERMISSAO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PERMISSAO_ID_PERMISSAO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 2350 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PRAZOSUSPENSO_ID_PRAZOSUSPENSO
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PRAZOSUSPENSO_ID_PRAZOSUSPENSO"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 158 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PRAZOSUSPENSO_ID_PRAZOSUSPENSO" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PRAZOSUSPENSOTIPO_ID_PRAZOSUSP
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PRAZOSUSPENSOTIPO_ID_PRAZOSUSP"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 6 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PRAZOSUSPENSOTIPO_ID_PRAZOSUSP" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PRESIDENTE_TURMA_RECURSALTEMP_
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PRESIDENTE_TURMA_RECURSALTEMP_"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PRESIDENTE_TURMA_RECURSALTEMP_" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PROCESSOASSUNTO_ID_PROCESSOASS
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PROCESSOASSUNTO_ID_PROCESSOASS"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 571873 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PROCESSOASSUNTO_ID_PROCESSOASS" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PROCESSOBENEFICIO_ID_PROCESSOB
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PROCESSOBENEFICIO_ID_PROCESSOB"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PROCESSOBENEFICIO_ID_PROCESSOB" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PROCESSODEBITO_ID_PROCESSODEBI
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PROCESSODEBITO_ID_PROCESSODEBI"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PROCESSODEBITO_ID_PROCESSODEBI" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PROCESSOEVENTOEXECUCAO_ID_PROC
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PROCESSOEVENTOEXECUCAO_ID_PROC"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 264498 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PROCESSOEVENTOEXECUCAO_ID_PROC" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PROCESSOEXECUCAO_ID_PROCESSOEX
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PROCESSOEXECUCAO_ID_PROCESSOEX"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 41931 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PROCESSOEXECUCAO_ID_PROCESSOEX" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PROCESSOFASE_ID_PROCESSOFASE_S
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PROCESSOFASE_ID_PROCESSOFASE_S"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 5 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PROCESSOFASE_ID_PROCESSOFASE_S" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PROCESSO_ID_PROCESSO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PROCESSO_ID_PROCESSO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 627724 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PROCESSO_ID_PROCESSO_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PROCESSONUMERO_ID_PROCESSONUME
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PROCESSONUMERO_ID_PROCESSONUME"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 5201496 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PROCESSOPARTEADVOGADO_ID_PROCE
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PROCESSOPARTEADVOGADO_ID_PROCE"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 815722 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PROCESSOPARTEADVOGADO_ID_PROCE" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PROCESSOPARTEALCUNHA_ID_PROCES
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PROCESSOPARTEALCUNHA_ID_PROCES"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 95 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PROCESSOPARTEALCUNHA_ID_PROCES" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PROCESSOPARTEAUSENCIA_ID_PROCE
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PROCESSOPARTEAUSENCIA_ID_PROCE"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PROCESSOPARTEAUSENCIA_ID_PROCE" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PROCESSOPARTEBENEFICIO_ID_PROC
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PROCESSOPARTEBENEFICIO_ID_PROC"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 11292 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PROCESSOPARTEBENEFICIO_ID_PROC" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PROCESSOPARTEDEBITO_ID_PROCESS
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PROCESSOPARTEDEBITO_ID_PROCESS"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 4958 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PROCESSOPARTEDEBITO_ID_PROCESS" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PROCESSOPARTE_ID_PROCESSOPARTE
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PROCESSOPARTE_ID_PROCESSOPARTE"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 1483336 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PROCESSOPARTE_ID_PROCESSOPARTE" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PROCESSOPARTESINAL_ID_PROCESSO
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PROCESSOPARTESINAL_ID_PROCESSO"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PROCESSOPARTESINAL_ID_PROCESSO" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PROCESSOPARTETEMP_ID_PROCESSOP
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PROCESSOPARTETEMP_ID_PROCESSOP"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PROCESSOPARTETEMP_ID_PROCESSOP" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PROCESSOPARTETIPO_ID_PROCESSOP
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PROCESSOPARTETIPO_ID_PROCESSOP"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 16 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PROCESSOPARTETIPO_ID_PROCESSOP" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PROCESSOPRIORIDADE_ID_PROCESSO
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PROCESSOPRIORIDADE_ID_PROCESSO"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 5 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PROCESSOPRIORIDADE_ID_PROCESSO" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PROCESSORESPONSAVEL_ID_PROCESS
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PROCESSORESPONSAVEL_ID_PROCESS"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 798370 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PROCESSORESPONSAVEL_ID_PROCESS" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PROCESSOSITUACAO_ID_PROCESSOSI
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PROCESSOSITUACAO_ID_PROCESSOSI"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 47 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PROCESSOSITUACAO_ID_PROCESSOSI" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PROCESSOSTATUS_ID_PROCESSOSTAT
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PROCESSOSTATUS_ID_PROCESSOSTAT"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 7 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PROCESSOSTATUS_ID_PROCESSOSTAT" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PROCESSOSUBTIPO_ID_PROCESSOSUB
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PROCESSOSUBTIPO_ID_PROCESSOSUB"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 5 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PROCESSOSUBTIPO_ID_PROCESSOSUB" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PROCESSOTEMP_ID_PROCESSO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PROCESSOTEMP_ID_PROCESSO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PROCESSOTEMP_ID_PROCESSO_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PROCESSOTIPO_ID_PROCESSOTIPO_S
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PROCESSOTIPO_ID_PROCESSOTIPO_S"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 387 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PROCESSOTIPO_ID_PROCESSOTIPO_S" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PROCESSOTIPOPROCESSOSUBTIPO_ID
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PROCESSOTIPOPROCESSOSUBTIPO_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 40 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PROCESSOTIPOPROCESSOSUBTIPO_ID" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PROFISSAO_ID_PROFISSAO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PROFISSAO_ID_PROFISSAO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 854 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PROFISSAO_ID_PROFISSAO_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PROJETO_ID_PROJETO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PROJETO_ID_PROJETO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PROJETO_ID_PROJETO_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PROJETOPARTICIPANTE_ID_PROJETO
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PROJETOPARTICIPANTE_ID_PROJETO"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 9 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PROJETOPARTICIPANTE_ID_PROJETO" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence PROPRIEDADE_ID_PROPRIEDADE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."PROPRIEDADE_ID_PROPRIEDADE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 43 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."PROPRIEDADE_ID_PROPRIEDADE_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence RECURSOASSUNTO_ID_RECURSOASSUN
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."RECURSOASSUNTO_ID_RECURSOASSUN"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 27962 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."RECURSOASSUNTO_ID_RECURSOASSUN" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence RECURSO_ID_RECURSO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."RECURSO_ID_RECURSO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 21167 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."RECURSO_ID_RECURSO_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence RECURSOPARTE_ID_RECURSOPARTE_S
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."RECURSOPARTE_ID_RECURSOPARTE_S"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 46283 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."RECURSOPARTE_ID_RECURSOPARTE_S" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence REGIAO_ID_REGIAO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."REGIAO_ID_REGIAO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."REGIAO_ID_REGIAO_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence REGIMEEXECUCAO_ID_REGIMEEXECUC
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."REGIMEEXECUCAO_ID_REGIMEEXECUC"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 18 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."REGIMEEXECUCAO_ID_REGIMEEXECUC" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence RELATORIOESTPRO_ID_RELATORIO_1
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."RELATORIOESTPRO_ID_RELATORIO_1"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 52 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."RELATORIOESTPRO_ID_RELATORIO_1" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence RELATORIOPERIODICO_ID_RELATORI
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."RELATORIOPERIODICO_ID_RELATORI"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 80 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."RELATORIOPERIODICO_ID_RELATORI" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence RGORGAOEXPEDIDOR_ID_RGORGAOEXP
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."RGORGAOEXPEDIDOR_ID_RGORGAOEXP"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 804 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."RGORGAOEXPEDIDOR_ID_RGORGAOEXP" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence SEQ_CERT
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."SEQ_CERT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 126110 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_EMENTA
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."SEQ_EMENTA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1081 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_MANDADO_PRISAO
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."SEQ_MANDADO_PRISAO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 17 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_MANDADO_PRISAO_ARQUIVO
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."SEQ_MANDADO_PRISAO_ARQUIVO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 14 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_MANDADO_PRISAO_ORIGEM
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."SEQ_MANDADO_PRISAO_ORIGEM"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_MANDADO_PRISAO_STATUS
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."SEQ_MANDADO_PRISAO_STATUS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_MOVI_TIPO_CLASSE
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."SEQ_MOVI_TIPO_CLASSE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 14 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."SEQ_MOVI_TIPO_CLASSE" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence SEQ_MOVI_TIPO_MOVI_TIPO_CLASSE
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."SEQ_MOVI_TIPO_MOVI_TIPO_CLASSE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 94 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."SEQ_MOVI_TIPO_MOVI_TIPO_CLASSE" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence SEQ_OFICIAL_CERT
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."SEQ_OFICIAL_CERT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 945 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PEND_RESP_HIST
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."SEQ_PEND_RESP_HIST"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 46034 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PRISAO_TIPO
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."SEQ_PRISAO_TIPO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PROC_CRIMINAL
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."SEQ_PROC_CRIMINAL"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 6485 NOCACHE  ORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."SEQ_PROC_CRIMINAL" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence SEQ_SERV_CARGO_SERV_GRUPO
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."SEQ_SERV_CARGO_SERV_GRUPO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_SERV_GRUPO
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."SEQ_SERV_GRUPO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 7 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SERVAREADIST_ID_SERVAREADIST_S
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."SERVAREADIST_ID_SERVAREADIST_S"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 676 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."SERVAREADIST_ID_SERVAREADIST_S" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence SERVENTIACARGO_ID_SERVENTIACAR
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."SERVENTIACARGO_ID_SERVENTIACAR"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 14183 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."SERVENTIACARGO_ID_SERVENTIACAR" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence SERVENTIACARGOTEMP_ID_SERVENTI
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."SERVENTIACARGOTEMP_ID_SERVENTI"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."SERVENTIACARGOTEMP_ID_SERVENTI" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence SERVENTIA_ID_SERVENTIA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."SERVENTIA_ID_SERVENTIA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 2001 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."SERVENTIA_ID_SERVENTIA_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence SERVENTIARELACIONADA_ID_SERVEN
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."SERVENTIARELACIONADA_ID_SERVEN"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 1427 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."SERVENTIARELACIONADA_ID_SERVEN" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence SERVENTIASUBTIPOASSUNTO_ID_SER
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."SERVENTIASUBTIPOASSUNTO_ID_SER"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 15399 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."SERVENTIASUBTIPOASSUNTO_ID_SER" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence SERVENTIASUBTIPO_ID_SERVENTIAS
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."SERVENTIASUBTIPO_ID_SERVENTIAS"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 32 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."SERVENTIASUBTIPO_ID_SERVENTIAS" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence SERVENTIASUBTIPOPROCESSOTIPO_I
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."SERVENTIASUBTIPOPROCESSOTIPO_I"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 1036 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."SERVENTIASUBTIPOPROCESSOTIPO_I" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence SERVENTIATIPO_ID_SERVENTIATIPO
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."SERVENTIATIPO_ID_SERVENTIATIPO"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 29 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."SERVENTIATIPO_ID_SERVENTIATIPO" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence SINAL_ID_SINAL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."SINAL_ID_SINAL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."SINAL_ID_SINAL_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence SISTEMA_ID_SISTEMA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."SISTEMA_ID_SISTEMA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 4 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."SISTEMA_ID_SISTEMA_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence TAREFA_ID_TAREFA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."TAREFA_ID_TAREFA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 74 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."TAREFA_ID_TAREFA_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence TAREFAPRIORIDADE_ID_TAREFAPRIO
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."TAREFAPRIORIDADE_ID_TAREFAPRIO"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 4 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."TAREFAPRIORIDADE_ID_TAREFAPRIO" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence TAREFASTATUS_ID_TAREFASTATUS_S
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."TAREFASTATUS_ID_TAREFASTATUS_S"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 6 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."TAREFASTATUS_ID_TAREFASTATUS_S" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence TAREFATIPO_ID_TAREFATIPO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."TAREFATIPO_ID_TAREFATIPO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 15 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."TAREFATIPO_ID_TAREFATIPO_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence TESTE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."TESTE_SEQ"  MINVALUE 0 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 3 CACHE 20 NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."TESTE_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence TRANSITOJULGADOEVENTO_ID_CO
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."TRANSITOJULGADOEVENTO_ID_CO"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 3724 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."TRANSITOJULGADOEVENTO_ID_CO" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence UFRVALOR_ID_UFR_VALOR_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."UFRVALOR_ID_UFR_VALOR_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 123 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."UFRVALOR_ID_UFR_VALOR_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence USUARIOAFASTAMENTO_ID_USUARIOA
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."USUARIOAFASTAMENTO_ID_USUARIOA"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."USUARIOAFASTAMENTO_ID_USUARIOA" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence USUARIOARQUIVO_ID_USUARIOARQUI
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."USUARIOARQUIVO_ID_USUARIOARQUI"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 20036 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."USUARIOARQUIVO_ID_USUARIOARQUI" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence USUARIO_ID_USUARIO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."USUARIO_ID_USUARIO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 24559 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."USUARIO_ID_USUARIO_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence USUARIOSERVENTIAESCALA_ID_USUA
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."USUARIOSERVENTIAESCALA_ID_USUA"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."USUARIOSERVENTIAESCALA_ID_USUA" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence USUARIOSERVENTIAESCALASTHIS_ID
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."USUARIOSERVENTIAESCALASTHIS_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."USUARIOSERVENTIAESCALASTHIS_ID" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence USUARIOSERVENTIAGRUPO_ID_USUAR
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."USUARIOSERVENTIAGRUPO_ID_USUAR"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 47997 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."USUARIOSERVENTIAGRUPO_ID_USUAR" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence USUARIOSERVENTIA_ID_USUARIOSER
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."USUARIOSERVENTIA_ID_USUARIOSER"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 48297 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."USUARIOSERVENTIA_ID_USUARIOSER" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence USUARIOSERVENTIAOAB_ID_USUARIO
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."USUARIOSERVENTIAOAB_ID_USUARIO"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 19020 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."USUARIOSERVENTIAOAB_ID_USUARIO" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence USUARIOSERVENTIAPERMISSAO_ID_U
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."USUARIOSERVENTIAPERMISSAO_ID_U"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."USUARIOSERVENTIAPERMISSAO_ID_U" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence USUARIOSERVENTIATEMP_ID_USUARI
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."USUARIOSERVENTIATEMP_ID_USUARI"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."USUARIOSERVENTIATEMP_ID_USUARI" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence USU_MOVI_TIPO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."USU_MOVI_TIPO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 233 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."USU_MOVI_TIPO_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence USU_SERV_ESC_STATUS_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."USU_SERV_ESC_STATUS_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."USU_SERV_ESC_STATUS_ID_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence ZONABAIRRO_ID_ZONABAIRRO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."ZONABAIRRO_ID_ZONABAIRRO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 42243 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."ZONABAIRRO_ID_ZONABAIRRO_SEQ" TO "PROJUDI_ALL";
--------------------------------------------------------
--  DDL for Sequence ZONA_ID_ZONA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROJUDI"."ZONA_ID_ZONA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 6427 NOCACHE  NOORDER  NOCYCLE ;
  GRANT ALTER, SELECT ON "PROJUDI"."ZONA_ID_ZONA_SEQ" TO "PROJUDI_ALL";
  