--------------------------------------------------------
--  Ref Constraints for Table AREA_DIST
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."AREA_DIST" ADD CONSTRAINT "AREADISTRIBUICAO_AREADISTRIBUI" FOREIGN KEY ("ID_AREA_DIST_RELACIONADA")
	  REFERENCES "PROJUDI"."AREA_DIST" ("ID_AREA_DIST") ENABLE;
 
  ALTER TABLE "PROJUDI"."AREA_DIST" ADD CONSTRAINT "AREADISTRIBUICAO_FORUM_FK" FOREIGN KEY ("ID_FORUM")
	  REFERENCES "PROJUDI"."FORUM" ("ID_FORUM") ENABLE;
 
  ALTER TABLE "PROJUDI"."AREA_DIST" ADD CONSTRAINT "AREADISTRIBUICAO_SERVENTIASUBT" FOREIGN KEY ("ID_SERV_SUBTIPO")
	  REFERENCES "PROJUDI"."SERV_SUBTIPO" ("ID_SERV_SUBTIPO") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."AREA_DIST" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."AREA_DIST" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."ARQ" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."ARQ" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table ARQ_PALAVRA
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."ARQ_PALAVRA" ADD CONSTRAINT "ARQUIVOPALAVRA_PALAVRA_1_FK" FOREIGN KEY ("ID_PALAVRA_1")
	  REFERENCES "PROJUDI"."PALAVRA" ("ID_PALAVRA") ENABLE;
 
  ALTER TABLE "PROJUDI"."ARQ_PALAVRA" ADD CONSTRAINT "ARQUIVOPALAVRA_PALAVRA_2_FK" FOREIGN KEY ("ID_PALAVRA_2")
	  REFERENCES "PROJUDI"."PALAVRA" ("ID_PALAVRA") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."ARQ_PALAVRA" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."ARQ_PALAVRA" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."ARQ_TIPO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."ARQ_TIPO" TO "ROLE_PROJUDI_CONSULTA";
GRANT DELETE, INSERT, SELECT, UPDATE ON "PROJUDI"."ARQUIVO_BANCO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."ARQUIVO_BANCO" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."ARRECADACAO_CUSTA" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."ARRECADACAO_CUSTA" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table ASSUNTO
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."ASSUNTO" ADD CONSTRAINT "ASSUNTO_ASSUNTO_PAI_FK" FOREIGN KEY ("ID_ASSUNTO_PAI")
	  REFERENCES "PROJUDI"."ASSUNTO" ("ID_ASSUNTO") ENABLE;
 
  ALTER TABLE "PROJUDI"."ASSUNTO" ADD CONSTRAINT "ASSUNTO_CNJASSUNTO_FK" FOREIGN KEY ("ID_CNJ_ASSUNTO")
	  REFERENCES "PROJUDI"."CNJ_ASSUNTO" ("ID_ASSUNTO") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."ASSUNTO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."ASSUNTO" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table AUDI
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."AUDI" ADD CONSTRAINT "AUDIENCIA_AUDIENCIATIPO_FK" FOREIGN KEY ("ID_AUDI_TIPO")
	  REFERENCES "PROJUDI"."AUDI_TIPO" ("ID_AUDI_TIPO") ENABLE;
 
  ALTER TABLE "PROJUDI"."AUDI" ADD CONSTRAINT "AUDIENCIA_SERVENTIA_FK" FOREIGN KEY ("ID_SERV")
	  REFERENCES "PROJUDI"."SERV" ("ID_SERV") ENABLE;
 
  ALTER TABLE "PROJUDI"."AUDI" ADD CONSTRAINT "AUDI_ARQ_FINALIZACAO" FOREIGN KEY ("ID_ARQ_FINALIZACAO")
	  REFERENCES "PROJUDI"."ARQ" ("ID_ARQ") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."AUDI" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."AUDI" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table AUDI_PROC
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."AUDI_PROC" ADD CONSTRAINT "AUDIENCIAPROCESSO_AUDIENCIAPRO" FOREIGN KEY ("ID_AUDI_PROC_STATUS")
	  REFERENCES "PROJUDI"."AUDI_PROC_STATUS" ("ID_AUDI_PROC_STATUS") ENABLE;
 
  ALTER TABLE "PROJUDI"."AUDI_PROC" ADD CONSTRAINT "AUDIENCIAPROCESSO_AUDIENCIA_FK" FOREIGN KEY ("ID_AUDI")
	  REFERENCES "PROJUDI"."AUDI" ("ID_AUDI") ENABLE;
 
  ALTER TABLE "PROJUDI"."AUDI_PROC" ADD CONSTRAINT "AUDIENCIAPROCESSO_PROCESSO_FK" FOREIGN KEY ("ID_PROC")
	  REFERENCES "PROJUDI"."PROC" ("ID_PROC") ENABLE;
 
  ALTER TABLE "PROJUDI"."AUDI_PROC" ADD CONSTRAINT "AUDIENCIAPROCESSO_SERVENTIACAR" FOREIGN KEY ("ID_SERV_CARGO")
	  REFERENCES "PROJUDI"."SERV_CARGO" ("ID_SERV_CARGO") ENABLE;
 
  ALTER TABLE "PROJUDI"."AUDI_PROC" ADD CONSTRAINT "AUDIPROC_ARQ_ATA" FOREIGN KEY ("ID_ARQ_ATA")
	  REFERENCES "PROJUDI"."ARQ" ("ID_ARQ") ENABLE;
 
  ALTER TABLE "PROJUDI"."AUDI_PROC" ADD CONSTRAINT "AUDIPROC_ARQ_ATA_ADIANTAMENTO" FOREIGN KEY ("ID_ARQ_ATA_ADIAMENTO")
	  REFERENCES "PROJUDI"."ARQ" ("ID_ARQ") ENABLE;
 
  ALTER TABLE "PROJUDI"."AUDI_PROC" ADD CONSTRAINT "AUDIPROC_ARQ_ATA_INICIADO" FOREIGN KEY ("ID_ARQ_ATA_INICIADO")
	  REFERENCES "PROJUDI"."ARQ" ("ID_ARQ") ENABLE;
 
  ALTER TABLE "PROJUDI"."AUDI_PROC" ADD CONSTRAINT "AUDIPROC_AUDIPROCSTATUS_ANA" FOREIGN KEY ("ID_AUDI_PROC_STATUS_ANA")
	  REFERENCES "PROJUDI"."AUDI_PROC_STATUS" ("ID_AUDI_PROC_STATUS") ENABLE;
 
  ALTER TABLE "PROJUDI"."AUDI_PROC" ADD CONSTRAINT "AUDI_ID_SERV_CARGO_PRES_FK" FOREIGN KEY ("ID_SERV_CARGO_PRESIDENTE")
	  REFERENCES "PROJUDI"."SERV_CARGO" ("ID_SERV_CARGO") ENABLE;
 
  ALTER TABLE "PROJUDI"."AUDI_PROC" ADD CONSTRAINT "ID_SERV_CARGO_MP_FK" FOREIGN KEY ("ID_SERV_CARGO_MP")
	  REFERENCES "PROJUDI"."SERV_CARGO" ("ID_SERV_CARGO") ENABLE;
 
  ALTER TABLE "PROJUDI"."AUDI_PROC" ADD CONSTRAINT "ID_SERV_CARGO_REDATOR_FK" FOREIGN KEY ("ID_SERV_CARGO_REDATOR")
	  REFERENCES "PROJUDI"."SERV_CARGO" ("ID_SERV_CARGO") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."AUDI_PROC" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."AUDI_PROC" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table AUDI_PROC_RESP
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."AUDI_PROC_RESP" ADD CONSTRAINT "AUDIENCIAPROCESSORESPONSAVEL_A" FOREIGN KEY ("ID_AUDI_PROC")
	  REFERENCES "PROJUDI"."AUDI_PROC" ("ID_AUDI_PROC") ENABLE;
 
  ALTER TABLE "PROJUDI"."AUDI_PROC_RESP" ADD CONSTRAINT "AUDIENCIAPROCESSORESPONSAVEL_C" FOREIGN KEY ("ID_CARGO_TIPO")
	  REFERENCES "PROJUDI"."CARGO_TIPO" ("ID_CARGO_TIPO") ENABLE;
 
  ALTER TABLE "PROJUDI"."AUDI_PROC_RESP" ADD CONSTRAINT "AUDIENCIAPROCESSORESPONSAVEL_U" FOREIGN KEY ("ID_USU_SERV")
	  REFERENCES "PROJUDI"."USU_SERV" ("ID_USU_SERV") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."AUDI_PROC_RESP" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."AUDI_PROC_RESP" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table AUDI_PROC_STATUS
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."AUDI_PROC_STATUS" ADD CONSTRAINT "AUDIENCIAPROCESSOSTATUS_SERVEN" FOREIGN KEY ("ID_SERV_TIPO")
	  REFERENCES "PROJUDI"."SERV_TIPO" ("ID_SERV_TIPO") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."AUDI_PROC_STATUS" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."AUDI_PROC_STATUS" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."AUDI_PUBLICADA" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."AUDI_PUBLICADA" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."AUDI_TIPO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."AUDI_TIPO" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table BAIRRO
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."BAIRRO" ADD CONSTRAINT "BAIRRO_CIDADE_FK" FOREIGN KEY ("ID_CIDADE")
	  REFERENCES "PROJUDI"."CIDADE" ("ID_CIDADE") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."BAIRRO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."BAIRRO" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."BANCO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."BANCO" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table CALCULO_LIQUIDACAO
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."CALCULO_LIQUIDACAO" ADD CONSTRAINT "CALCULOLIQUIDACAO_FK" FOREIGN KEY ("ID_PROC")
	  REFERENCES "PROJUDI"."PROC" ("ID_PROC") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."CALCULO_LIQUIDACAO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."CALCULO_LIQUIDACAO" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table CARGO_TIPO
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."CARGO_TIPO" ADD CONSTRAINT "CARGOTIPO_GRUPO_FK" FOREIGN KEY ("ID_GRUPO")
	  REFERENCES "PROJUDI"."GRUPO" ("ID_GRUPO") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."CARGO_TIPO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."CARGO_TIPO" TO "ROLE_PROJUDI_CONSULTA";
GRANT DELETE, INSERT, SELECT, UPDATE ON "PROJUDI"."CERT" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."CERT" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table CERTIFICADO
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."CERTIFICADO" ADD CONSTRAINT "CERTIFICADO_USUARIO_CERTIFICAD" FOREIGN KEY ("ID_USU_CERTIFICADO")
	  REFERENCES "PROJUDI"."USU" ("ID_USU") ENABLE;
 
  ALTER TABLE "PROJUDI"."CERTIFICADO" ADD CONSTRAINT "CERTIFICADO_USUARIO_LIBERADOR_" FOREIGN KEY ("ID_USU_LIBERADOR")
	  REFERENCES "PROJUDI"."USU" ("ID_USU") ENABLE;
 
  ALTER TABLE "PROJUDI"."CERTIFICADO" ADD CONSTRAINT "CERTIFICADO_USUARIO_REVOGADOR_" FOREIGN KEY ("ID_USU_REVOGADOR")
	  REFERENCES "PROJUDI"."USU" ("ID_USU") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."CERTIFICADO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."CERTIFICADO" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table CERTIFICADO_CONFIAVEL
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."CERTIFICADO_CONFIAVEL" ADD CONSTRAINT "CERTIFICADOCONFIAVEL_USUARIO_C" FOREIGN KEY ("ID_USU_CADASTRADOR")
	  REFERENCES "PROJUDI"."USU" ("ID_USU") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."CERTIFICADO_CONFIAVEL" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."CERTIFICADO_CONFIAVEL" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."CERT_TIPO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."CERT_TIPO" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."CERT_TIPO_PROC_TIPO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."CERT_TIPO_PROC_TIPO" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table CIDADE
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."CIDADE" ADD CONSTRAINT "CIDADE_ESTADO_FK" FOREIGN KEY ("ID_ESTADO")
	  REFERENCES "PROJUDI"."ESTADO" ("ID_ESTADO") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."CIDADE" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."CIDADE" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table CIDADE_SSP
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."CIDADE_SSP" ADD CONSTRAINT "CIDADESSP_CIDADE_FK" FOREIGN KEY ("ID_CIDADE_TJ")
	  REFERENCES "PROJUDI"."CIDADE" ("ID_CIDADE") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."CIDADE_SSP" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."CIDADE_SSP" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table CLASSIFICADOR
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."CLASSIFICADOR" ADD CONSTRAINT "CLASSIFICADOR_SERVENTIA_FK" FOREIGN KEY ("ID_SERV")
	  REFERENCES "PROJUDI"."SERV" ("ID_SERV") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."CLASSIFICADOR" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."CLASSIFICADOR" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."CNJ_ASSUNTO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."CNJ_ASSUNTO" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."CNJ_CLASSE" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."CNJ_CLASSE" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."CNJ_MOVI" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."CNJ_MOVI" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."COMARCA" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."COMARCA" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table COMARCA_CIDADE
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."COMARCA_CIDADE" ADD CONSTRAINT "COMARCACIDADE_CIDADE_FK" FOREIGN KEY ("ID_CIDADE")
	  REFERENCES "PROJUDI"."CIDADE" ("ID_CIDADE") ENABLE;
 
  ALTER TABLE "PROJUDI"."COMARCA_CIDADE" ADD CONSTRAINT "COMARCACIDADE_COMARCA_FK" FOREIGN KEY ("ID_COMARCA")
	  REFERENCES "PROJUDI"."COMARCA" ("ID_COMARCA") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."COMARCA_CIDADE" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."COMARCA_CIDADE" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table CONDENACAO_EXE
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."CONDENACAO_EXE" ADD CONSTRAINT "CONDENACAOEXECUCAO_SITUACAO_FK" FOREIGN KEY ("ID_CONDENACAO_EXE_SIT")
	  REFERENCES "PROJUDI"."CONDENACAO_EXE_SIT" ("ID_CONDENACAO_EXE_SIT") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."CONDENACAO_EXE" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."CONDENACAO_EXE" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."CONDENACAO_EXE_SIT" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."CONDENACAO_EXE_SIT" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table CONTA_USU
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."CONTA_USU" ADD CONSTRAINT "CONTAUSUARIO_AGENCIA_FK" FOREIGN KEY ("ID_AGENCIA")
	  REFERENCES "PROJUDI"."AGENCIA" ("ID_AGENCIA") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."CONTA_USU" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."CONTA_USU" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."CRIME_EXE" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."CRIME_EXE" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table CUSTA
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."CUSTA" ADD CONSTRAINT "CUSTA_ARRECADAOCUSTA_FK" FOREIGN KEY ("ID_ARRECADACAO_CUSTA")
	  REFERENCES "PROJUDI"."ARRECADACAO_CUSTA" ("ID_ARRECADACAO_CUSTA") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."CUSTA" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."CUSTA" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table CUSTA_VALOR
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."CUSTA_VALOR" ADD CONSTRAINT "CUSTAVALOR_CUSTA_FK" FOREIGN KEY ("ID_CUSTA")
	  REFERENCES "PROJUDI"."CUSTA" ("ID_CUSTA") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."CUSTA_VALOR" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."CUSTA_VALOR" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table EMENTA
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."EMENTA" ADD CONSTRAINT "EMENTA_ARQACORDAO_ARQ_FK" FOREIGN KEY ("ID_ARQ_ACORDAO")
	  REFERENCES "PROJUDI"."ARQ" ("ID_ARQ") ENABLE;
 
  ALTER TABLE "PROJUDI"."EMENTA" ADD CONSTRAINT "EMENTA_ARQEMENTA_ARQ_FK" FOREIGN KEY ("ID_ARQ_EMENTA")
	  REFERENCES "PROJUDI"."ARQ" ("ID_ARQ") ENABLE;
 
  ALTER TABLE "PROJUDI"."EMENTA" ADD CONSTRAINT "EMENTA_AUDI_PROC_FK" FOREIGN KEY ("ID_AUDI_PROC")
	  REFERENCES "PROJUDI"."AUDI_PROC" ("ID_AUDI_PROC") ENABLE;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "PROJUDI"."EMENTA" TO "PROJUDI_ALL";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."EMPRESA_TIPO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."EMPRESA_TIPO" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table ENDERECO
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."ENDERECO" ADD CONSTRAINT "ENDERECO_BAIRRO_FK" FOREIGN KEY ("ID_BAIRRO")
	  REFERENCES "PROJUDI"."BAIRRO" ("ID_BAIRRO") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."ENDERECO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."ENDERECO" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."ESC" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."ESC" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."ESCOLARIDADE" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."ESCOLARIDADE" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table ESTADO
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."ESTADO" ADD CONSTRAINT "ESTADO_PAIS_FK" FOREIGN KEY ("ID_PAIS")
	  REFERENCES "PROJUDI"."PAIS" ("ID_PAIS") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."ESTADO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."ESTADO" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."ESTADO_CIVIL" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."ESTADO_CIVIL" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."EST_PEND" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."EST_PEND" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."EST_PROC" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."EST_PROC" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."EST_PROD" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."EST_PROD" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."EST_PROD_ITEM" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."EST_PROD_ITEM" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table EST_RELATORIO_EST_PRO_ITEMS
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."EST_RELATORIO_EST_PRO_ITEMS" ADD CONSTRAINT "ESTATISTICARELATORIOESTPROITEN" FOREIGN KEY ("ID_RELATORIO_EST_PROD_ITENS")
	  REFERENCES "PROJUDI"."RELATORIO_EST_PRO" ("ID_RELATORIO_EST_PRO") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."EST_RELATORIO_EST_PRO_ITEMS" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."EST_RELATORIO_EST_PRO_ITEMS" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table EVENTO_EXE
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."EVENTO_EXE" ADD CONSTRAINT "EVENTOEXECUCAOSTATUS_FK" FOREIGN KEY ("ID_EVENTO_EXE_STATUS")
	  REFERENCES "PROJUDI"."EVENTO_EXE_STATUS" ("ID_EVENTO_EXE_STATUS") ENABLE;
 
  ALTER TABLE "PROJUDI"."EVENTO_EXE" ADD CONSTRAINT "EVENTOEXECUCAOTIPO_FK" FOREIGN KEY ("ID_EVENTO_EXE_TIPO")
	  REFERENCES "PROJUDI"."EVENTO_EXE_TIPO" ("ID_EVENTO_EXE_TIPO") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."EVENTO_EXE" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."EVENTO_EXE" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."EVENTO_EXE_STATUS" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."EVENTO_EXE_STATUS" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."EVENTO_EXE_TIPO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."EVENTO_EXE_TIPO" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."EVENTO_LOCAL" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."EVENTO_LOCAL" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."EVENTO_REGIME" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."EVENTO_REGIME" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, SELECT ON "PROJUDI"."EXT_ARQ" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."EXT_ARQ" TO "ROLE_PROJUDI_CONSULTA";
GRANT DELETE, INSERT, SELECT, UPDATE ON "PROJUDI"."FINALIDADE" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."FINALIDADE" TO "ROLE_PROJUDI_CONSULTA";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE ON "PROJUDI"."FINALIDADE" TO "ROLE_PROJUDI_GERENCIA";
--------------------------------------------------------
--  Ref Constraints for Table FORUM
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."FORUM" ADD CONSTRAINT "FORUM_COMARCA_FK" FOREIGN KEY ("ID_COMARCA")
	  REFERENCES "PROJUDI"."COMARCA" ("ID_COMARCA") ENABLE;
 
  ALTER TABLE "PROJUDI"."FORUM" ADD CONSTRAINT "FORUM_ENDERECO_FK" FOREIGN KEY ("ID_ENDERECO")
	  REFERENCES "PROJUDI"."ENDERECO" ("ID_ENDERECO") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."FORUM" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."FORUM" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."GOVERNO_TIPO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."GOVERNO_TIPO" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."GRUPO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."GRUPO" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table GRUPO_ARQ_TIPO
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."GRUPO_ARQ_TIPO" ADD CONSTRAINT "GRUPOARQUIVOTIPO_ARQUIVOTIPO_F" FOREIGN KEY ("ID_ARQ_TIPO")
	  REFERENCES "PROJUDI"."ARQ_TIPO" ("ID_ARQ_TIPO") ENABLE;
 
  ALTER TABLE "PROJUDI"."GRUPO_ARQ_TIPO" ADD CONSTRAINT "GRUPOARQUIVOTIPO_GRUPO_FK" FOREIGN KEY ("ID_GRUPO")
	  REFERENCES "PROJUDI"."GRUPO" ("ID_GRUPO") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."GRUPO_ARQ_TIPO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."GRUPO_ARQ_TIPO" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table GRUPO_MOVI_TIPO
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."GRUPO_MOVI_TIPO" ADD CONSTRAINT "GRUPOMOVIMENTACAOTIPO_GRUPO_FK" FOREIGN KEY ("ID_GRUPO")
	  REFERENCES "PROJUDI"."GRUPO" ("ID_GRUPO") ENABLE;
 
  ALTER TABLE "PROJUDI"."GRUPO_MOVI_TIPO" ADD CONSTRAINT "GRUPOMOVIMENTACAOTIPO_MOVIMENT" FOREIGN KEY ("ID_MOVI_TIPO")
	  REFERENCES "PROJUDI"."MOVI_TIPO" ("ID_MOVI_TIPO") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."GRUPO_MOVI_TIPO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."GRUPO_MOVI_TIPO" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table GRUPO_PEND_TIPO
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."GRUPO_PEND_TIPO" ADD CONSTRAINT "GRUPOPENDENCIATIPO_GRUPO_FK" FOREIGN KEY ("ID_GRUPO")
	  REFERENCES "PROJUDI"."GRUPO" ("ID_GRUPO") ENABLE;
 
  ALTER TABLE "PROJUDI"."GRUPO_PEND_TIPO" ADD CONSTRAINT "GRUPOPENDENCIATIPO_PENDENCIATI" FOREIGN KEY ("ID_PEND_TIPO")
	  REFERENCES "PROJUDI"."PEND_TIPO" ("ID_PEND_TIPO") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."GRUPO_PEND_TIPO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."GRUPO_PEND_TIPO" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table GRUPO_PERM
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."GRUPO_PERM" ADD CONSTRAINT "GRUPO11PERMISSAO_PERMISSAO_FK1" FOREIGN KEY ("ID_PERM")
	  REFERENCES "PROJUDI"."PERM" ("ID_PERM") ENABLE;
 
  ALTER TABLE "PROJUDI"."GRUPO_PERM" ADD CONSTRAINT "GRUPOPERMI11SSAO_GRUPO_FK1" FOREIGN KEY ("ID_GRUPO")
	  REFERENCES "PROJUDI"."GRUPO" ("ID_GRUPO") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."GRUPO_PERM" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."GRUPO_PERM" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."GRUPO_TIPO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."GRUPO_TIPO" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table GUIA_CUSTA_MODELO
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."GUIA_CUSTA_MODELO" ADD CONSTRAINT "GUIACUSTAMODELO_CUSTA_FK" FOREIGN KEY ("ID_CUSTA")
	  REFERENCES "PROJUDI"."CUSTA" ("ID_CUSTA") ENABLE;
 
  ALTER TABLE "PROJUDI"."GUIA_CUSTA_MODELO" ADD CONSTRAINT "GUIACUSTAMODELO_GUIAMODELO_FK" FOREIGN KEY ("ID_GUIA_MODELO")
	  REFERENCES "PROJUDI"."GUIA_MODELO" ("ID_GUIA_MODELO") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."GUIA_CUSTA_MODELO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."GUIA_CUSTA_MODELO" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table GUIA_EMIS
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."GUIA_EMIS" ADD CONSTRAINT "GUIAEMISSAO_COMARCA_FK" FOREIGN KEY ("ID_COMARCA")
	  REFERENCES "PROJUDI"."COMARCA" ("ID_COMARCA") ENABLE;
 
  ALTER TABLE "PROJUDI"."GUIA_EMIS" ADD CONSTRAINT "GUIAEMISSAO_GUIAEMISSAOPRINCIP" FOREIGN KEY ("ID_GUIA_EMIS_PRINC")
	  REFERENCES "PROJUDI"."GUIA_EMIS" ("ID_GUIA_EMIS") ENABLE;
 
  ALTER TABLE "PROJUDI"."GUIA_EMIS" ADD CONSTRAINT "GUIAEMISSAO_GUIAMODELO_FK" FOREIGN KEY ("ID_GUIA_MODELO")
	  REFERENCES "PROJUDI"."GUIA_MODELO" ("ID_GUIA_MODELO") ENABLE;
 
  ALTER TABLE "PROJUDI"."GUIA_EMIS" ADD CONSTRAINT "GUIAEMISSAO_GUIASTATUS_FK" FOREIGN KEY ("ID_GUIA_STATUS")
	  REFERENCES "PROJUDI"."GUIA_STATUS" ("ID_GUIA_STATUS") ENABLE;
 
  ALTER TABLE "PROJUDI"."GUIA_EMIS" ADD CONSTRAINT "GUIAEMISSAO_PROCESSOPARTERECOR" FOREIGN KEY ("ID_PROC_PARTE_RECORRENTE")
	  REFERENCES "PROJUDI"."PROC_PARTE" ("ID_PROC_PARTE") ENABLE;
 
  ALTER TABLE "PROJUDI"."GUIA_EMIS" ADD CONSTRAINT "GUIAEMISSAO_PROCESSOPARTEREC_1" FOREIGN KEY ("ID_PROC_PARTE_RECORRIDO")
	  REFERENCES "PROJUDI"."PROC_PARTE" ("ID_PROC_PARTE") ENABLE;
 
  ALTER TABLE "PROJUDI"."GUIA_EMIS" ADD CONSTRAINT "GUIAEMISSAO_PROCESSOTIPO_FK" FOREIGN KEY ("ID_PROC_TIPO")
	  REFERENCES "PROJUDI"."PROC_TIPO" ("ID_PROC_TIPO") ENABLE;
 
  ALTER TABLE "PROJUDI"."GUIA_EMIS" ADD CONSTRAINT "GUIAEMISSAO_PROCESSO_FK" FOREIGN KEY ("ID_PROC")
	  REFERENCES "PROJUDI"."PROC" ("ID_PROC") ENABLE;
 
  ALTER TABLE "PROJUDI"."GUIA_EMIS" ADD CONSTRAINT "GUIAEMISSAO_SERVENTIA_FK" FOREIGN KEY ("ID_SERV")
	  REFERENCES "PROJUDI"."SERV" ("ID_SERV") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."GUIA_EMIS" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."GUIA_EMIS" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table GUIA_FINALIDADE_MODELO
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."GUIA_FINALIDADE_MODELO" ADD CONSTRAINT "GUIA_FINALID_MODELO_FINALID" FOREIGN KEY ("ID_FINALIDADE")
	  REFERENCES "PROJUDI"."FINALIDADE" ("ID_FINALIDADE") ENABLE;
 
  ALTER TABLE "PROJUDI"."GUIA_FINALIDADE_MODELO" ADD CONSTRAINT "GUIA_FINALID_MODELO_GUIA_TIPO" FOREIGN KEY ("ID_GUIA_TIPO")
	  REFERENCES "PROJUDI"."GUIA_TIPO" ("ID_GUIA_TIPO") ENABLE;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "PROJUDI"."GUIA_FINALIDADE_MODELO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."GUIA_FINALIDADE_MODELO" TO "ROLE_PROJUDI_CONSULTA";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE ON "PROJUDI"."GUIA_FINALIDADE_MODELO" TO "ROLE_PROJUDI_GERENCIA";
--------------------------------------------------------
--  Ref Constraints for Table GUIA_FINALID_MODELO_CUSTA
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."GUIA_FINALID_MODELO_CUSTA" ADD CONSTRAINT "GUIA_FINALID_MOD_CUSTA_CUSTA" FOREIGN KEY ("ID_CUSTA")
	  REFERENCES "PROJUDI"."CUSTA" ("ID_CUSTA") ENABLE;
 
  ALTER TABLE "PROJUDI"."GUIA_FINALID_MODELO_CUSTA" ADD CONSTRAINT "GUIA_FINALID_MOD_CUSTA_MODELO" FOREIGN KEY ("ID_GUIA_FINALIDADE_MODELO")
	  REFERENCES "PROJUDI"."GUIA_FINALIDADE_MODELO" ("ID_GUIA_FINALIDADE_MODELO") ENABLE;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "PROJUDI"."GUIA_FINALID_MODELO_CUSTA" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."GUIA_FINALID_MODELO_CUSTA" TO "ROLE_PROJUDI_CONSULTA";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE ON "PROJUDI"."GUIA_FINALID_MODELO_CUSTA" TO "ROLE_PROJUDI_GERENCIA";
--------------------------------------------------------
--  Ref Constraints for Table GUIA_ITEM
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."GUIA_ITEM" ADD CONSTRAINT "GUIAITEM_CUSTA_FK" FOREIGN KEY ("ID_CUSTA")
	  REFERENCES "PROJUDI"."CUSTA" ("ID_CUSTA") ENABLE;
 
  ALTER TABLE "PROJUDI"."GUIA_ITEM" ADD CONSTRAINT "GUIAITEM_GUIAEMISSAO_FK" FOREIGN KEY ("ID_GUIA_EMIS")
	  REFERENCES "PROJUDI"."GUIA_EMIS" ("ID_GUIA_EMIS") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."GUIA_ITEM" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."GUIA_ITEM" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table GUIA_MODELO
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."GUIA_MODELO" ADD CONSTRAINT "GUIAMODELO_GUIATIPO_FK" FOREIGN KEY ("ID_GUIA_TIPO")
	  REFERENCES "PROJUDI"."GUIA_TIPO" ("ID_GUIA_TIPO") ENABLE;
 
  ALTER TABLE "PROJUDI"."GUIA_MODELO" ADD CONSTRAINT "GUIAMODELO_PROCESSOTIPO_FK" FOREIGN KEY ("ID_PROC_TIPO")
	  REFERENCES "PROJUDI"."PROC_TIPO" ("ID_PROC_TIPO") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."GUIA_MODELO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."GUIA_MODELO" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."GUIA_NUMERO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."GUIA_NUMERO" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."GUIA_STATUS" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."GUIA_STATUS" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."GUIA_TIPO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."GUIA_TIPO" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."HIS_LOTACAO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."HIS_LOTACAO" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."LOCAL_CUMP_PENA" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."LOCAL_CUMP_PENA" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table LOCOMOCAO
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."LOCOMOCAO" ADD CONSTRAINT "LOCOMOCAO_AREA_FK" FOREIGN KEY ("ID_AREA")
	  REFERENCES "PROJUDI"."AREA" ("ID_AREA") ENABLE;
 
  ALTER TABLE "PROJUDI"."LOCOMOCAO" ADD CONSTRAINT "LOCOMOCAO_BAIRRO_FK" FOREIGN KEY ("ID_BAIRRO")
	  REFERENCES "PROJUDI"."BAIRRO" ("ID_BAIRRO") ENABLE;
 
  ALTER TABLE "PROJUDI"."LOCOMOCAO" ADD CONSTRAINT "LOCOMOCAO_GUIAITEM_FK" FOREIGN KEY ("ID_GUIA_ITEM")
	  REFERENCES "PROJUDI"."GUIA_ITEM" ("ID_GUIA_ITEM") ENABLE;
 
  ALTER TABLE "PROJUDI"."LOCOMOCAO" ADD CONSTRAINT "LOCOMOCAO_MANDADOJUDICIAL_FK" FOREIGN KEY ("ID_MAND_JUD")
	  REFERENCES "PROJUDI"."MAND_JUD" ("ID_MAND_JUD") ENABLE;
 
  ALTER TABLE "PROJUDI"."LOCOMOCAO" ADD CONSTRAINT "LOCOMOCAO_ZONA_FK" FOREIGN KEY ("ID_ZONA")
	  REFERENCES "PROJUDI"."ZONA" ("ID_ZONA") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."LOCOMOCAO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."LOCOMOCAO" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table LOG
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."LOG" ADD CONSTRAINT "LOG_LOGTIPO_FK1" FOREIGN KEY ("ID_LOG_TIPO")
	  REFERENCES "PROJUDI"."LOG_TIPO" ("ID_LOG_TIPO") ENABLE;
 
  ALTER TABLE "PROJUDI"."LOG" ADD CONSTRAINT "LOG_USUARIO_FK1" FOREIGN KEY ("ID_USU")
	  REFERENCES "PROJUDI"."USU" ("ID_USU") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."LOG" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."LOG" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."LOG_ERROS" TO "PROJUDI_ALL";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."LOG_TIPO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."LOG_TIPO" TO "ROLE_PROJUDI_CONSULTA";
GRANT SELECT ON "PROJUDI"."LOG_2010" TO "PJ32GO";
 
  GRANT SELECT ON "PROJUDI"."LOG_2010" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."LOG_2010" TO "ROLE_PROJUDI_CONSULTA";
GRANT SELECT ON "PROJUDI"."LOG_2011" TO "PJ32GO";
 
  GRANT SELECT ON "PROJUDI"."LOG_2011" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."LOG_2011" TO "ROLE_PROJUDI_CONSULTA";

--------------------------------------------------------
--  Ref Constraints for Table MANDADO_PRISAO
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."MANDADO_PRISAO" ADD CONSTRAINT "FK_ID_PRISAO_TIPO" FOREIGN KEY ("ID_PRISAO_TIPO")
	  REFERENCES "PROJUDI"."PRISAO_TIPO" ("ID_PRISAO_TIPO") ENABLE;
 
  ALTER TABLE "PROJUDI"."MANDADO_PRISAO" ADD CONSTRAINT "FK_MANDADO_PRISAO_ORIGEM" FOREIGN KEY ("ID_MANDADO_PRISAO_ORIGEM")
	  REFERENCES "PROJUDI"."MANDADO_PRISAO_ORIGEM" ("ID_MANDADO_PRISAO_ORIGEM") ENABLE;
 
  ALTER TABLE "PROJUDI"."MANDADO_PRISAO" ADD CONSTRAINT "MANDADO_PRISAO_PROC_PARTE_FK1" FOREIGN KEY ("ID_PROC_PARTE")
	  REFERENCES "PROJUDI"."PROC_PARTE" ("ID_PROC_PARTE") ENABLE;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "PROJUDI"."MANDADO_PRISAO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."MANDADO_PRISAO" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table MANDADO_PRISAO_ARQUIVO
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."MANDADO_PRISAO_ARQUIVO" ADD CONSTRAINT "FK_ARQUIVO_FK1" FOREIGN KEY ("ID_ARQUIVO")
	  REFERENCES "PROJUDI"."ARQ" ("ID_ARQ") ENABLE;
 
  ALTER TABLE "PROJUDI"."MANDADO_PRISAO_ARQUIVO" ADD CONSTRAINT "FK_MANDADO_PRISAO_FK1" FOREIGN KEY ("ID_MANDADO_PRISAO")
	  REFERENCES "PROJUDI"."MANDADO_PRISAO" ("ID_MANDADO_PRISAO") ENABLE;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "PROJUDI"."MANDADO_PRISAO_ARQUIVO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."MANDADO_PRISAO_ARQUIVO" TO "ROLE_PROJUDI_CONSULTA";
GRANT DELETE, INSERT, SELECT, UPDATE ON "PROJUDI"."MANDADO_PRISAO_ORIGEM" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."MANDADO_PRISAO_ORIGEM" TO "ROLE_PROJUDI_CONSULTA";
GRANT DELETE, INSERT, SELECT, UPDATE ON "PROJUDI"."MANDADO_PRISAO_STATUS" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."MANDADO_PRISAO_STATUS" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."MAND_JUD" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."MAND_JUD" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."MAND_JUD_STATUS" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."MAND_JUD_STATUS" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."MAND_TIPO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."MAND_TIPO" TO "ROLE_PROJUDI_CONSULTA";
GRANT DELETE, INSERT, SELECT, UPDATE ON "PROJUDI"."MJLTESTE1" TO "ROLE_PROJUDI_CONSULTA";
GRANT DELETE, INSERT, SELECT, UPDATE ON "PROJUDI"."MJLTESTE2" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table MODELO
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."MODELO" ADD CONSTRAINT "MODELO_ARQUIVOTIPO_FK" FOREIGN KEY ("ID_ARQ_TIPO")
	  REFERENCES "PROJUDI"."ARQ_TIPO" ("ID_ARQ_TIPO") ENABLE;
 
  ALTER TABLE "PROJUDI"."MODELO" ADD CONSTRAINT "MODELO_SERVENTIA_FK" FOREIGN KEY ("ID_SERV")
	  REFERENCES "PROJUDI"."SERV" ("ID_SERV") ENABLE;
 
  ALTER TABLE "PROJUDI"."MODELO" ADD CONSTRAINT "MODELO_USUARIOSERVENTIA_FK" FOREIGN KEY ("ID_USU_SERV")
	  REFERENCES "PROJUDI"."USU_SERV" ("ID_USU_SERV") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."MODELO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."MODELO" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table MOVI
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."MOVI" ADD CONSTRAINT "MOVIMENTACAO_MOVIMENTACAOTIPO_" FOREIGN KEY ("ID_MOVI_TIPO")
	  REFERENCES "PROJUDI"."MOVI_TIPO" ("ID_MOVI_TIPO") ENABLE;
 
  ALTER TABLE "PROJUDI"."MOVI" ADD CONSTRAINT "MOVIMENTACAO_PROCESSOPRIORIDAD" FOREIGN KEY ("ID_PROC_PRIOR")
	  REFERENCES "PROJUDI"."PROC_PRIOR" ("ID_PROC_PRIOR") ENABLE;
 
  ALTER TABLE "PROJUDI"."MOVI" ADD CONSTRAINT "MOVIMENTACAO_PROCESSO_FK" FOREIGN KEY ("ID_PROC")
	  REFERENCES "PROJUDI"."PROC" ("ID_PROC") ENABLE;
 
  ALTER TABLE "PROJUDI"."MOVI" ADD CONSTRAINT "MOVIMENTACAO_USUARIOSERVENTIA_" FOREIGN KEY ("ID_USU_REALIZADOR")
	  REFERENCES "PROJUDI"."USU_SERV" ("ID_USU_SERV") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."MOVI" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."MOVI" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table MOVI_ARQ
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."MOVI_ARQ" ADD CONSTRAINT "MOVIMENTACAOARQUIVO_MOVIMENTAC" FOREIGN KEY ("ID_MOVI")
	  REFERENCES "PROJUDI"."MOVI" ("ID_MOVI") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."MOVI_ARQ" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."MOVI_ARQ" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table MOVI_TIPO
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."MOVI_TIPO" ADD CONSTRAINT "MOVIMENTACAOTIPO_CNJMOVIMENTAC" FOREIGN KEY ("ID_CNJ_MOVI")
	  REFERENCES "PROJUDI"."CNJ_MOVI" ("ID_MOVI") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."MOVI_TIPO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."MOVI_TIPO" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."MOVI_TIPO_CLASSE" TO "PROJUDI_ALL";
GRANT DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."MOVI_TIPO_MOVI_TIPO_CLASSE" TO "PROJUDI_ALL";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."OBJETO_PEDIDO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."OBJETO_PEDIDO" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."OCORRENCIA_INTERRUPCAO" TO "PROJUDI_ALL";
--------------------------------------------------------
--  Ref Constraints for Table OFICIAL_CERT
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."OFICIAL_CERT" ADD CONSTRAINT "OFICIAL_CERT_USU_SERV_FK1" FOREIGN KEY ("ID_USU_SERV")
	  REFERENCES "PROJUDI"."USU_SERV" ("ID_USU_SERV") ENABLE;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "PROJUDI"."OFICIAL_CERT" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."OFICIAL_CERT" TO "ROLE_PROJUDI_CONSULTA";
 
  GRANT SELECT ON "PROJUDI"."OFICIAL_CERT" TO "ROLE_PROJUDI_GERENCIA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."ORAMAN_PLAN_TABLE" TO "ROLE_PROJUDI_GERENCIA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PAIS" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PAIS" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PALAVRA" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PALAVRA" TO "ROLE_PROJUDI_CONSULTA";
GRANT DELETE, INSERT, SELECT, UPDATE ON "PROJUDI"."PARAMETRO_COMUTACAO_EXE" TO "PROJUDI_ALL";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PARAMETRO_CRIME_EXE" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PARAMETRO_CRIME_EXE" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PENA_EXE_TIPO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PENA_EXE_TIPO" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table PEND
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."PEND" ADD CONSTRAINT "PENDENCIA_MOVIMENTACAO_FK" FOREIGN KEY ("ID_MOVI")
	  REFERENCES "PROJUDI"."MOVI" ("ID_MOVI") ENABLE;
 
  ALTER TABLE "PROJUDI"."PEND" ADD CONSTRAINT "PENDENCIA_PENDENCIASTATUS_FK" FOREIGN KEY ("ID_PEND_STATUS")
	  REFERENCES "PROJUDI"."PEND_STATUS" ("ID_PEND_STATUS") ENABLE;
 
  ALTER TABLE "PROJUDI"."PEND" ADD CONSTRAINT "PENDENCIA_PENDENCIATIPO_FK" FOREIGN KEY ("ID_PEND_TIPO")
	  REFERENCES "PROJUDI"."PEND_TIPO" ("ID_PEND_TIPO") ENABLE;
 
  ALTER TABLE "PROJUDI"."PEND" ADD CONSTRAINT "PENDENCIA_PENDENCIA_PAI_FK" FOREIGN KEY ("ID_PEND_PAI")
	  REFERENCES "PROJUDI"."PEND" ("ID_PEND") ENABLE;
 
  ALTER TABLE "PROJUDI"."PEND" ADD CONSTRAINT "PENDENCIA_PROCESSOPARTE_FK" FOREIGN KEY ("ID_PROC_PARTE")
	  REFERENCES "PROJUDI"."PROC_PARTE" ("ID_PROC_PARTE") ENABLE;
 
  ALTER TABLE "PROJUDI"."PEND" ADD CONSTRAINT "PENDENCIA_PROCESSOPRIORIDADE_F" FOREIGN KEY ("ID_PROC_PRIOR")
	  REFERENCES "PROJUDI"."PROC_PRIOR" ("ID_PROC_PRIOR") ENABLE;
 
  ALTER TABLE "PROJUDI"."PEND" ADD CONSTRAINT "PENDENCIA_PROCESSO_FK" FOREIGN KEY ("ID_PROC")
	  REFERENCES "PROJUDI"."PROC" ("ID_PROC") ENABLE;
 
  ALTER TABLE "PROJUDI"."PEND" ADD CONSTRAINT "PENDENCIA_USUARIOSERVENTIA_CAD" FOREIGN KEY ("ID_USU_CADASTRADOR")
	  REFERENCES "PROJUDI"."USU_SERV" ("ID_USU_SERV") ENABLE;
 
  ALTER TABLE "PROJUDI"."PEND" ADD CONSTRAINT "PENDENCIA_USUARIOSERVENTIA_FIN" FOREIGN KEY ("ID_USU_FINALIZADOR")
	  REFERENCES "PROJUDI"."USU_SERV" ("ID_USU_SERV") ENABLE;
 
  ALTER TABLE "PROJUDI"."PEND" ADD FOREIGN KEY ("ID_CLASSIFICADOR")
	  REFERENCES "PROJUDI"."CLASSIFICADOR" ("ID_CLASSIFICADOR") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PEND" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PEND" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table PEND_ARQ
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."PEND_ARQ" ADD CONSTRAINT "PENDENCIAARQUIVO_PENDENCIA_FK" FOREIGN KEY ("ID_PEND")
	  REFERENCES "PROJUDI"."PEND" ("ID_PEND") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PEND_ARQ" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PEND_ARQ" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table PEND_RESP
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."PEND_RESP" ADD CONSTRAINT "PENDENCIARESPONSAVEL_PENDENCIA" FOREIGN KEY ("ID_PEND")
	  REFERENCES "PROJUDI"."PEND" ("ID_PEND") ENABLE;
 
  ALTER TABLE "PROJUDI"."PEND_RESP" ADD CONSTRAINT "PENDENCIARESPONSAVEL_SERVENTIA" FOREIGN KEY ("ID_SERV_CARGO")
	  REFERENCES "PROJUDI"."SERV_CARGO" ("ID_SERV_CARGO") ENABLE;
 
  ALTER TABLE "PROJUDI"."PEND_RESP" ADD CONSTRAINT "PENDENCIARESPONSAVEL_SERVENT_2" FOREIGN KEY ("ID_SERV")
	  REFERENCES "PROJUDI"."SERV" ("ID_SERV") ENABLE;
 
  ALTER TABLE "PROJUDI"."PEND_RESP" ADD CONSTRAINT "PENDENCIARESPONSAVEL_SERVENT_3" FOREIGN KEY ("ID_SERV_TIPO")
	  REFERENCES "PROJUDI"."SERV_TIPO" ("ID_SERV_TIPO") ENABLE;
 
  ALTER TABLE "PROJUDI"."PEND_RESP" ADD CONSTRAINT "PENDENCIARESPONSAVEL_USUARIOSE" FOREIGN KEY ("ID_USU_RESP")
	  REFERENCES "PROJUDI"."USU_SERV" ("ID_USU_SERV") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PEND_RESP" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PEND_RESP" TO "ROLE_PROJUDI_CONSULTA";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PEND_RESP" TO "ROLE_PROJUDI_GERENCIA";
--------------------------------------------------------
--  Ref Constraints for Table PEND_RESP_HIST
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."PEND_RESP_HIST" ADD CONSTRAINT "FK_ID_PEND" FOREIGN KEY ("ID_PEND")
	  REFERENCES "PROJUDI"."PEND" ("ID_PEND") ENABLE;
 
  ALTER TABLE "PROJUDI"."PEND_RESP_HIST" ADD CONSTRAINT "FK_ID_SERV_CARGO_PRH" FOREIGN KEY ("ID_SERV_CARGO")
	  REFERENCES "PROJUDI"."SERV_CARGO" ("ID_SERV_CARGO") ENABLE;
 
  ALTER TABLE "PROJUDI"."PEND_RESP_HIST" ADD CONSTRAINT "FK_ID_SERV_GRUPO_PRH" FOREIGN KEY ("ID_SERV_GRUPO")
	  REFERENCES "PROJUDI"."SERV_GRUPO" ("ID_SERV_GRUPO") ENABLE;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "PROJUDI"."PEND_RESP_HIST" TO "PROJUDI_ALL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "PROJUDI"."PEND_RESP_HIST" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PEND_STATUS" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PEND_STATUS" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table PEND_TIPO
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."PEND_TIPO" ADD CONSTRAINT "PENDENCIATIPO_ARQUIVOTIPO_FK" FOREIGN KEY ("ID_ARQ_TIPO")
	  REFERENCES "PROJUDI"."ARQ_TIPO" ("ID_ARQ_TIPO") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PEND_TIPO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PEND_TIPO" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PEND_TIPO_CONCLUSAO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PEND_TIPO_CONCLUSAO" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table PEND_TIPO_RELACIONADA
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."PEND_TIPO_RELACIONADA" ADD CONSTRAINT "PENDENCIATIPORELACIONADA_FK" FOREIGN KEY ("ID_PEND_TIPO_PRINC")
	  REFERENCES "PROJUDI"."PEND_TIPO" ("ID_PEND_TIPO") ENABLE;
 
  ALTER TABLE "PROJUDI"."PEND_TIPO_RELACIONADA" ADD CONSTRAINT "PENDENCIATIPORELACIONADA_FK1" FOREIGN KEY ("ID_PEND_TIPO_REL")
	  REFERENCES "PROJUDI"."PEND_TIPO" ("ID_PEND_TIPO") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PEND_TIPO_RELACIONADA" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PEND_TIPO_RELACIONADA" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table PERM
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."PERM" ADD CONSTRAINT "PERMISSAO_PERMISSAO_PAI_FK1" FOREIGN KEY ("ID_PERM_PAI")
	  REFERENCES "PROJUDI"."PERM" ("ID_PERM") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PERM" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PERM" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PERM_ESPECIAL" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PERM_ESPECIAL" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table PRAZO_SUSPENSO
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."PRAZO_SUSPENSO" ADD CONSTRAINT "PRAZOSUSPENSO_CIDADE_FK" FOREIGN KEY ("ID_CIDADE")
	  REFERENCES "PROJUDI"."CIDADE" ("ID_CIDADE") ENABLE;
 
  ALTER TABLE "PROJUDI"."PRAZO_SUSPENSO" ADD CONSTRAINT "PRAZOSUSPENSO_COMARCA_FK" FOREIGN KEY ("ID_COMARCA")
	  REFERENCES "PROJUDI"."COMARCA" ("ID_COMARCA") ENABLE;
 
  ALTER TABLE "PROJUDI"."PRAZO_SUSPENSO" ADD CONSTRAINT "PRAZOSUSPENSO_PRAZOSUSPENSOTIP" FOREIGN KEY ("ID_PRAZO_SUSPENSO_TIPO")
	  REFERENCES "PROJUDI"."PRAZO_SUSPENSO_TIPO" ("ID_PRAZO_SUSPENSO_TIPO") ENABLE;
 
  ALTER TABLE "PROJUDI"."PRAZO_SUSPENSO" ADD CONSTRAINT "PRAZOSUSPENSO_SERVENTIA_FK" FOREIGN KEY ("ID_SERV")
	  REFERENCES "PROJUDI"."SERV" ("ID_SERV") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PRAZO_SUSPENSO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PRAZO_SUSPENSO" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PRAZO_SUSPENSO_TIPO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PRAZO_SUSPENSO_TIPO" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE ON "PROJUDI"."PRISAO_TIPO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PRISAO_TIPO" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table PROC
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."PROC" ADD CONSTRAINT "PROCESSO_AREA_FK" FOREIGN KEY ("ID_AREA")
	  REFERENCES "PROJUDI"."AREA" ("ID_AREA") ENABLE;
 
  ALTER TABLE "PROJUDI"."PROC" ADD CONSTRAINT "PROCESSO_CLASSIFICADOR_FK" FOREIGN KEY ("ID_CLASSIFICADOR")
	  REFERENCES "PROJUDI"."CLASSIFICADOR" ("ID_CLASSIFICADOR") ENABLE;
 
  ALTER TABLE "PROJUDI"."PROC" ADD CONSTRAINT "PROCESSO_OBJETOPEDIDO_FK" FOREIGN KEY ("ID_OBJETO_PEDIDO")
	  REFERENCES "PROJUDI"."OBJETO_PEDIDO" ("ID_OBJETO_PEDIDO") ENABLE;
 
  ALTER TABLE "PROJUDI"."PROC" ADD CONSTRAINT "PROCESSO_PROCESSOFASE_FK" FOREIGN KEY ("ID_PROC_FASE")
	  REFERENCES "PROJUDI"."PROC_FASE" ("ID_PROC_FASE") ENABLE;
 
  ALTER TABLE "PROJUDI"."PROC" ADD CONSTRAINT "PROCESSO_PROCESSOPRIORIDADE_FK" FOREIGN KEY ("ID_PROC_PRIOR")
	  REFERENCES "PROJUDI"."PROC_PRIOR" ("ID_PROC_PRIOR") ENABLE;
 
  ALTER TABLE "PROJUDI"."PROC" ADD CONSTRAINT "PROCESSO_PROCESSOSITUACAO_FK" FOREIGN KEY ("ID_PROC_SIT")
	  REFERENCES "PROJUDI"."PROC_SIT" ("ID_PROC_SIT") ENABLE;
 
  ALTER TABLE "PROJUDI"."PROC" ADD CONSTRAINT "PROCESSO_PROCESSOSTATUS_FK" FOREIGN KEY ("ID_PROC_STATUS")
	  REFERENCES "PROJUDI"."PROC_STATUS" ("ID_PROC_STATUS") ENABLE;
 
  ALTER TABLE "PROJUDI"."PROC" ADD CONSTRAINT "PROCESSO_PROCESSOTIPO_FK" FOREIGN KEY ("ID_PROC_TIPO")
	  REFERENCES "PROJUDI"."PROC_TIPO" ("ID_PROC_TIPO") ENABLE;
 
  ALTER TABLE "PROJUDI"."PROC" ADD CONSTRAINT "PROCESSO_PROCESSO_DEPENDENTE_F" FOREIGN KEY ("ID_PROC_DEPENDENTE")
	  REFERENCES "PROJUDI"."PROC" ("ID_PROC") ENABLE;
 
  ALTER TABLE "PROJUDI"."PROC" ADD CONSTRAINT "PROCESSO_SERVENTIA_FK" FOREIGN KEY ("ID_SERV")
	  REFERENCES "PROJUDI"."SERV" ("ID_SERV") ENABLE;
 
  ALTER TABLE "PROJUDI"."PROC" ADD CONSTRAINT "PROCESSO_SERVENTIA_ORIGEM_FK" FOREIGN KEY ("ID_SERV_ORIGEM")
	  REFERENCES "PROJUDI"."SERV" ("ID_SERV") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PROC" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PROC" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table PROC_ASSUNTO
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."PROC_ASSUNTO" ADD CONSTRAINT "PROCESSOASSUNTO_ASSUNTO_FK" FOREIGN KEY ("ID_ASSUNTO")
	  REFERENCES "PROJUDI"."ASSUNTO" ("ID_ASSUNTO") ENABLE;
 
  ALTER TABLE "PROJUDI"."PROC_ASSUNTO" ADD CONSTRAINT "PROCESSOASSUNTO_PROCESSO_FK" FOREIGN KEY ("ID_PROC")
	  REFERENCES "PROJUDI"."PROC" ("ID_PROC") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PROC_ASSUNTO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PROC_ASSUNTO" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PROC_BENEFICIO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PROC_BENEFICIO" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table PROC_CRIMINAL
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."PROC_CRIMINAL" ADD CONSTRAINT "PROC_CRIMINAL_FK1" FOREIGN KEY ("ID_PROC")
	  REFERENCES "PROJUDI"."PROC" ("ID_PROC") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PROC_CRIMINAL" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PROC_CRIMINAL" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PROC_DEBITO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PROC_DEBITO" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table PROC_EVENTO_EXE
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."PROC_EVENTO_EXE" ADD CONSTRAINT "PROCESSOEVENTOEXECUCAO_ID_LIVR" FOREIGN KEY ("ID_LIV_CONDICIONAL")
	  REFERENCES "PROJUDI"."PROC_EVENTO_EXE" ("ID_PROC_EVENTO_EXE") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PROC_EVENTO_EXE" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PROC_EVENTO_EXE" TO "ROLE_PROJUDI_CONSULTA";
GRANT SELECT ON "PROJUDI"."PROC_EVENTO_EXE_NEW" TO "WCSILVA";
--------------------------------------------------------
--  Ref Constraints for Table PROC_EXE
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."PROC_EXE" ADD CONSTRAINT "PROCESSOEXECUCAO_CIDADE_ORIGEM" FOREIGN KEY ("ID_CIDADE_ORIGEM")
	  REFERENCES "PROJUDI"."CIDADE" ("ID_CIDADE") ENABLE;
 
  ALTER TABLE "PROJUDI"."PROC_EXE" ADD CONSTRAINT "PROCESSOEXECUCAO_PROCESSO_ACAO" FOREIGN KEY ("ID_PROC_ACAO_PENAL")
	  REFERENCES "PROJUDI"."PROC" ("ID_PROC") ENABLE;
 
  ALTER TABLE "PROJUDI"."PROC_EXE" ADD CONSTRAINT "PROCESSOEXECUCAO_PROCESSO_EXEC" FOREIGN KEY ("ID_PROC_EXE_PENAL")
	  REFERENCES "PROJUDI"."PROC" ("ID_PROC") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PROC_EXE" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PROC_EXE" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PROC_FASE" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PROC_FASE" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PROC_NUMERO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PROC_NUMERO" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table PROC_PARTE
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."PROC_PARTE" ADD CONSTRAINT "PROCESSOPARTE_CIDADE_NATURALID" FOREIGN KEY ("ID_NATURALIDADE")
	  REFERENCES "PROJUDI"."CIDADE" ("ID_CIDADE") ENABLE;
 
  ALTER TABLE "PROJUDI"."PROC_PARTE" ADD CONSTRAINT "PROCESSOPARTE_ENDERECO_FK" FOREIGN KEY ("ID_ENDERECO")
	  REFERENCES "PROJUDI"."ENDERECO" ("ID_ENDERECO") ENABLE;
 
  ALTER TABLE "PROJUDI"."PROC_PARTE" ADD CONSTRAINT "PROCESSOPARTE_ESCOLARIDADE_FK" FOREIGN KEY ("ID_ESCOLARIDADE")
	  REFERENCES "PROJUDI"."ESCOLARIDADE" ("ID_ESCOLARIDADE") ENABLE;
 
  ALTER TABLE "PROJUDI"."PROC_PARTE" ADD CONSTRAINT "PROCESSOPARTE_ESTADOCIVIL_FK" FOREIGN KEY ("ID_ESTADO_CIVIL")
	  REFERENCES "PROJUDI"."ESTADO_CIVIL" ("ID_ESTADO_CIVIL") ENABLE;
 
  ALTER TABLE "PROJUDI"."PROC_PARTE" ADD CONSTRAINT "PROCESSOPARTE_ESTADO_CTPSUF_FK" FOREIGN KEY ("ID_CTPS_UF")
	  REFERENCES "PROJUDI"."ESTADO" ("ID_ESTADO") ENABLE;
 
  ALTER TABLE "PROJUDI"."PROC_PARTE" ADD CONSTRAINT "PROCESSOPARTE_PROCESSOPARTEAUS" FOREIGN KEY ("ID_PROC_PARTE_AUS")
	  REFERENCES "PROJUDI"."PROC_PARTE_AUS" ("ID_PROC_PARTE_AUS") ENABLE;
 
  ALTER TABLE "PROJUDI"."PROC_PARTE" ADD CONSTRAINT "PROCESSOPARTE_PROCESSOPARTETIP" FOREIGN KEY ("ID_PROC_PARTE_TIPO")
	  REFERENCES "PROJUDI"."PROC_PARTE_TIPO" ("ID_PROC_PARTE_TIPO") ENABLE;
 
  ALTER TABLE "PROJUDI"."PROC_PARTE" ADD CONSTRAINT "PROCESSOPARTE_PROCESSO_FK" FOREIGN KEY ("ID_PROC")
	  REFERENCES "PROJUDI"."PROC" ("ID_PROC") ENABLE;
 
  ALTER TABLE "PROJUDI"."PROC_PARTE" ADD CONSTRAINT "PROCESSOPARTE_PROFISSAO_FK" FOREIGN KEY ("ID_PROFISSAO")
	  REFERENCES "PROJUDI"."PROFISSAO" ("ID_PROFISSAO") ENABLE;
 
  ALTER TABLE "PROJUDI"."PROC_PARTE" ADD CONSTRAINT "PROCESSOPARTE_RGORGAOEXPEDIDOR" FOREIGN KEY ("ID_RG_ORGAO_EXP")
	  REFERENCES "PROJUDI"."RG_ORGAO_EXP" ("ID_RG_ORGAO_EXP") ENABLE;
 
  ALTER TABLE "PROJUDI"."PROC_PARTE" ADD CONSTRAINT "PROCESSOPARTE_USUARIOSERVENTIA" FOREIGN KEY ("ID_USU_SERV")
	  REFERENCES "PROJUDI"."USU_SERV" ("ID_USU_SERV") ENABLE;
  GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON "PROJUDI"."PROC_PARTE" TO PUBLIC;
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PROC_PARTE" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PROC_PARTE" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table PROC_PARTE_ADVOGADO
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."PROC_PARTE_ADVOGADO" ADD CONSTRAINT "PROCESSOPARTEADVOGADO_PROCESSO" FOREIGN KEY ("ID_PROC_PARTE")
	  REFERENCES "PROJUDI"."PROC_PARTE" ("ID_PROC_PARTE") ENABLE;
 
  ALTER TABLE "PROJUDI"."PROC_PARTE_ADVOGADO" ADD CONSTRAINT "PROCESSOPARTEADVOGADO_USUARIOS" FOREIGN KEY ("ID_USU_SERV")
	  REFERENCES "PROJUDI"."USU_SERV" ("ID_USU_SERV") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PROC_PARTE_ADVOGADO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PROC_PARTE_ADVOGADO" TO "ROLE_PROJUDI_CONSULTA";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PROC_PARTE_ADVOGADO" TO "ROLE_PROJUDI_GERENCIA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PROC_PARTE_ALCUNHA" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PROC_PARTE_ALCUNHA" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PROC_PARTE_AUS" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PROC_PARTE_AUS" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table PROC_PARTE_BENEFICIO
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."PROC_PARTE_BENEFICIO" ADD CONSTRAINT "PROCESSOPARTEBENEFICIO_PROCESS" FOREIGN KEY ("ID_PROC_BENEFICIO")
	  REFERENCES "PROJUDI"."PROC_BENEFICIO" ("ID_PROC_BENEFICIO") ENABLE;
 
  ALTER TABLE "PROJUDI"."PROC_PARTE_BENEFICIO" ADD CONSTRAINT "PROCESSOPARTEBENEFICIO_PRO_178" FOREIGN KEY ("ID_PROC_PARTE")
	  REFERENCES "PROJUDI"."PROC_PARTE" ("ID_PROC_PARTE") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PROC_PARTE_BENEFICIO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PROC_PARTE_BENEFICIO" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table PROC_PARTE_DEBITO
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."PROC_PARTE_DEBITO" ADD CONSTRAINT "PROCESSOPARTEDEBITO_PROCESSODE" FOREIGN KEY ("ID_PROC_DEBITO")
	  REFERENCES "PROJUDI"."PROC_DEBITO" ("ID_PROC_DEBITO") ENABLE;
 
  ALTER TABLE "PROJUDI"."PROC_PARTE_DEBITO" ADD CONSTRAINT "PROCESSOPARTEDEBITO_PROCESSOPA" FOREIGN KEY ("ID_PROC_PARTE")
	  REFERENCES "PROJUDI"."PROC_PARTE" ("ID_PROC_PARTE") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PROC_PARTE_DEBITO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PROC_PARTE_DEBITO" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PROC_PARTE_SINAL" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PROC_PARTE_SINAL" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PROC_PARTE_TIPO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PROC_PARTE_TIPO" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PROC_PRIOR" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PROC_PRIOR" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table PROC_RESP
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."PROC_RESP" ADD CONSTRAINT "PROCESSORESPONSAVEL_FK" FOREIGN KEY ("ID_CARGO_TIPO")
	  REFERENCES "PROJUDI"."CARGO_TIPO" ("ID_CARGO_TIPO") ENABLE;
 
  ALTER TABLE "PROJUDI"."PROC_RESP" ADD CONSTRAINT "PROCESSORESPONSAVEL_PROCESSO_F" FOREIGN KEY ("ID_PROC")
	  REFERENCES "PROJUDI"."PROC" ("ID_PROC") ENABLE;
 
  ALTER TABLE "PROJUDI"."PROC_RESP" ADD CONSTRAINT "PROCESSORESPONSAVEL_SERVENTIAC" FOREIGN KEY ("ID_SERV_CARGO")
	  REFERENCES "PROJUDI"."SERV_CARGO" ("ID_SERV_CARGO") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PROC_RESP" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PROC_RESP" TO "ROLE_PROJUDI_CONSULTA";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PROC_RESP" TO "ROLE_PROJUDI_GERENCIA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PROC_SIT" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PROC_SIT" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PROC_STATUS" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PROC_STATUS" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PROC_SUBTIPO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PROC_SUBTIPO" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table PROC_TIPO
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."PROC_TIPO" ADD CONSTRAINT "PROCESSOTIPO_CNJCLASSE_FK" FOREIGN KEY ("ID_CNJ_CLASSE")
	  REFERENCES "PROJUDI"."CNJ_CLASSE" ("ID_CLASSE") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PROC_TIPO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PROC_TIPO" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table PROC_TIPO_PROC_SUBTIPO
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."PROC_TIPO_PROC_SUBTIPO" ADD CONSTRAINT "PROCESSOTIPOPROCESSOSUBTIPO_FK" FOREIGN KEY ("ID_PROC_TIPO")
	  REFERENCES "PROJUDI"."PROC_TIPO" ("ID_PROC_TIPO") ENABLE;
 
  ALTER TABLE "PROJUDI"."PROC_TIPO_PROC_SUBTIPO" ADD CONSTRAINT "PROCESSOTIPOPROCESSOSUBTIP_178" FOREIGN KEY ("ID_PROC_SUBTIPO")
	  REFERENCES "PROJUDI"."PROC_SUBTIPO" ("ID_PROC_SUBTIPO") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PROC_TIPO_PROC_SUBTIPO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PROC_TIPO_PROC_SUBTIPO" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PROFISSAO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PROFISSAO" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PROJETO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PROJETO" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table PROJETO_PARTICIPANTE
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."PROJETO_PARTICIPANTE" ADD CONSTRAINT "PROJETOPARTICIPANTE_FK" FOREIGN KEY ("ID_PROJETO")
	  REFERENCES "PROJUDI"."PROJETO" ("ID_PROJETO") ENABLE;
 
  ALTER TABLE "PROJUDI"."PROJETO_PARTICIPANTE" ADD CONSTRAINT "PROJETOPARTICIPANTE_FK1" FOREIGN KEY ("ID_SERV_CARGO")
	  REFERENCES "PROJUDI"."SERV_CARGO" ("ID_SERV_CARGO") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PROJETO_PARTICIPANTE" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PROJETO_PARTICIPANTE" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."PROPRIEDADE" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."PROPRIEDADE" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table RECURSO
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."RECURSO" ADD CONSTRAINT "RECURSO_PROCESSOTIPO_FK" FOREIGN KEY ("ID_PROC_TIPO")
	  REFERENCES "PROJUDI"."PROC_TIPO" ("ID_PROC_TIPO") ENABLE;
 
  ALTER TABLE "PROJUDI"."RECURSO" ADD CONSTRAINT "RECURSO_PROCESSO_FK" FOREIGN KEY ("ID_PROC")
	  REFERENCES "PROJUDI"."PROC" ("ID_PROC") ENABLE;
 
  ALTER TABLE "PROJUDI"."RECURSO" ADD CONSTRAINT "RECURSO_SERVENTIA_ORIGEM_FK" FOREIGN KEY ("ID_SERV_ORIGEM")
	  REFERENCES "PROJUDI"."SERV" ("ID_SERV") ENABLE;
 
  ALTER TABLE "PROJUDI"."RECURSO" ADD CONSTRAINT "RECURSO_SERVENTIA_RECURSO_FK" FOREIGN KEY ("ID_SERV_RECURSO")
	  REFERENCES "PROJUDI"."SERV" ("ID_SERV") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."RECURSO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."RECURSO" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table RECURSO_ASSUNTO
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."RECURSO_ASSUNTO" ADD CONSTRAINT "RECURSOASSUNTO_ASSUNTO_FK" FOREIGN KEY ("ID_ASSUNTO")
	  REFERENCES "PROJUDI"."ASSUNTO" ("ID_ASSUNTO") ENABLE;
 
  ALTER TABLE "PROJUDI"."RECURSO_ASSUNTO" ADD CONSTRAINT "RECURSOASSUNTO_RECURSO_FK" FOREIGN KEY ("ID_RECURSO")
	  REFERENCES "PROJUDI"."RECURSO" ("ID_RECURSO") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."RECURSO_ASSUNTO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."RECURSO_ASSUNTO" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table RECURSO_PARTE
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."RECURSO_PARTE" ADD CONSTRAINT "RECURSOPARTE_PROCESSOPARTETIPO" FOREIGN KEY ("ID_PROC_PARTE_TIPO")
	  REFERENCES "PROJUDI"."PROC_PARTE_TIPO" ("ID_PROC_PARTE_TIPO") ENABLE;
 
  ALTER TABLE "PROJUDI"."RECURSO_PARTE" ADD CONSTRAINT "RECURSOPARTE_PROCESSOPARTE_FK" FOREIGN KEY ("ID_PROC_PARTE")
	  REFERENCES "PROJUDI"."PROC_PARTE" ("ID_PROC_PARTE") ENABLE;
 
  ALTER TABLE "PROJUDI"."RECURSO_PARTE" ADD CONSTRAINT "RECURSOPARTE_RECURSO_FK" FOREIGN KEY ("ID_RECURSO")
	  REFERENCES "PROJUDI"."RECURSO" ("ID_RECURSO") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."RECURSO_PARTE" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."RECURSO_PARTE" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table REGIAO
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."REGIAO" ADD CONSTRAINT "REGIAO_COMARCA_FK" FOREIGN KEY ("ID_COMARCA")
	  REFERENCES "PROJUDI"."COMARCA" ("ID_COMARCA") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."REGIAO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."REGIAO" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table REGIME_EXE
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."REGIME_EXE" ADD CONSTRAINT "REGIMEEXECUCAO_FK" FOREIGN KEY ("ID_PROXIMO_REGIME_EXE")
	  REFERENCES "PROJUDI"."REGIME_EXE" ("ID_REGIME_EXE") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."REGIME_EXE" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."REGIME_EXE" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."RELATORIO_EST_PRO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."RELATORIO_EST_PRO" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."RELATORIO_PERIODICO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."RELATORIO_PERIODICO" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table RG_ORGAO_EXP
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."RG_ORGAO_EXP" ADD CONSTRAINT "RGORGAOEXPEDIDOR_ESTADO_FK" FOREIGN KEY ("ID_ESTADO")
	  REFERENCES "PROJUDI"."ESTADO" ("ID_ESTADO") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."RG_ORGAO_EXP" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."RG_ORGAO_EXP" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table SERV
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."SERV" ADD CONSTRAINT "SERVENTIA_AREADISTRIBUICAO_FK" FOREIGN KEY ("ID_AREA_DIST")
	  REFERENCES "PROJUDI"."AREA_DIST" ("ID_AREA_DIST") ENABLE;
 
  ALTER TABLE "PROJUDI"."SERV" ADD CONSTRAINT "SERVENTIA_AREA_FK" FOREIGN KEY ("ID_AREA")
	  REFERENCES "PROJUDI"."AREA" ("ID_AREA") ENABLE;
 
  ALTER TABLE "PROJUDI"."SERV" ADD CONSTRAINT "SERVENTIA_AUDIENCIATIPO_FK" FOREIGN KEY ("ID_AUDI_TIPO")
	  REFERENCES "PROJUDI"."AUDI_TIPO" ("ID_AUDI_TIPO") ENABLE;
 
  ALTER TABLE "PROJUDI"."SERV" ADD CONSTRAINT "SERVENTIA_COMARCA_FK" FOREIGN KEY ("ID_COMARCA")
	  REFERENCES "PROJUDI"."COMARCA" ("ID_COMARCA") ENABLE;
 
  ALTER TABLE "PROJUDI"."SERV" ADD CONSTRAINT "SERVENTIA_ENDERECO_FK" FOREIGN KEY ("ID_ENDERECO")
	  REFERENCES "PROJUDI"."ENDERECO" ("ID_ENDERECO") ENABLE;
 
  ALTER TABLE "PROJUDI"."SERV" ADD CONSTRAINT "SERVENTIA_ESTADO_REPRESENTACAO" FOREIGN KEY ("ID_ESTADO_REPRESENTACAO")
	  REFERENCES "PROJUDI"."ESTADO" ("ID_ESTADO") ENABLE;
 
  ALTER TABLE "PROJUDI"."SERV" ADD CONSTRAINT "SERVENTIA_SERVENTIASUBTIPO_FK" FOREIGN KEY ("ID_SERV_SUBTIPO")
	  REFERENCES "PROJUDI"."SERV_SUBTIPO" ("ID_SERV_SUBTIPO") ENABLE;
 
  ALTER TABLE "PROJUDI"."SERV" ADD CONSTRAINT "SERVENTIA_SERVENTIATIPO_FK" FOREIGN KEY ("ID_SERV_TIPO")
	  REFERENCES "PROJUDI"."SERV_TIPO" ("ID_SERV_TIPO") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."SERV" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."SERV" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table SERV_AREA_DIST
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."SERV_AREA_DIST" ADD CONSTRAINT "SERVAREDIST_FK" FOREIGN KEY ("ID_SERV")
	  REFERENCES "PROJUDI"."SERV" ("ID_SERV") ENABLE;
 
  ALTER TABLE "PROJUDI"."SERV_AREA_DIST" ADD CONSTRAINT "SERVAREDIST_FK1" FOREIGN KEY ("ID_AREA_DIST")
	  REFERENCES "PROJUDI"."AREA_DIST" ("ID_AREA_DIST") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."SERV_AREA_DIST" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."SERV_AREA_DIST" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table SERV_CARGO
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."SERV_CARGO" ADD CONSTRAINT "SERVENTIACARGO_CARGOTIPO_FK" FOREIGN KEY ("ID_CARGO_TIPO")
	  REFERENCES "PROJUDI"."CARGO_TIPO" ("ID_CARGO_TIPO") ENABLE;
 
  ALTER TABLE "PROJUDI"."SERV_CARGO" ADD CONSTRAINT "SERVENTIACARGO_SERVENTIA_FK" FOREIGN KEY ("ID_SERV")
	  REFERENCES "PROJUDI"."SERV" ("ID_SERV") ENABLE;
 
  ALTER TABLE "PROJUDI"."SERV_CARGO" ADD CONSTRAINT "SERVENTIACARGO_USUARIOSERVENTI" FOREIGN KEY ("ID_USU_SERV_GRUPO")
	  REFERENCES "PROJUDI"."USU_SERV_GRUPO" ("ID_USU_SERV_GRUPO") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."SERV_CARGO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."SERV_CARGO" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table SERV_CARGO_SERV_GRUPO
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."SERV_CARGO_SERV_GRUPO" ADD CONSTRAINT "FK_ID_SERV_CARGO" FOREIGN KEY ("ID_SERV_CARGO")
	  REFERENCES "PROJUDI"."SERV_CARGO" ("ID_SERV_CARGO") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "PROJUDI"."SERV_CARGO_SERV_GRUPO" ADD CONSTRAINT "FK_ID_SERV_GRUPO" FOREIGN KEY ("ID_SERV_GRUPO")
	  REFERENCES "PROJUDI"."SERV_GRUPO" ("ID_SERV_GRUPO") ENABLE;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "PROJUDI"."SERV_CARGO_SERV_GRUPO" TO "PROJUDI_ALL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "PROJUDI"."SERV_CARGO_SERV_GRUPO" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table SERV_GRUPO
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."SERV_GRUPO" ADD CONSTRAINT "FK_ID_SERV" FOREIGN KEY ("ID_SERV")
	  REFERENCES "PROJUDI"."SERV" ("ID_SERV") ENABLE;
 
  ALTER TABLE "PROJUDI"."SERV_GRUPO" ADD CONSTRAINT "FK_ID_SERV_GRUPO_AUTO" FOREIGN KEY ("ID_SERV_GRUPO")
	  REFERENCES "PROJUDI"."SERV_GRUPO" ("ID_SERV_GRUPO") ENABLE;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "PROJUDI"."SERV_GRUPO" TO "PROJUDI_ALL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "PROJUDI"."SERV_GRUPO" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table SERV_RELACIONADA
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."SERV_RELACIONADA" ADD CONSTRAINT "FK_SERVRELACIONADASUB_SERV" FOREIGN KEY ("ID_SERV_SUBSTITUICAO")
	  REFERENCES "PROJUDI"."SERV" ("ID_SERV") ENABLE;
 
  ALTER TABLE "PROJUDI"."SERV_RELACIONADA" ADD CONSTRAINT "SERVENTIARELACIONADA_SERVENTIA" FOREIGN KEY ("ID_SERV_PRINC")
	  REFERENCES "PROJUDI"."SERV" ("ID_SERV") ENABLE;
 
  ALTER TABLE "PROJUDI"."SERV_RELACIONADA" ADD CONSTRAINT "SERVENTIARELACIONADA_SERVE_178" FOREIGN KEY ("ID_SERV_REL")
	  REFERENCES "PROJUDI"."SERV" ("ID_SERV") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."SERV_RELACIONADA" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."SERV_RELACIONADA" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."SERV_SUBTIPO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."SERV_SUBTIPO" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table SERV_SUBTIPO_ASSUNTO
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."SERV_SUBTIPO_ASSUNTO" ADD CONSTRAINT "SERVENTIASUBTIPOASSUNTO_ASSUNT" FOREIGN KEY ("ID_ASSUNTO")
	  REFERENCES "PROJUDI"."ASSUNTO" ("ID_ASSUNTO") ENABLE;
 
  ALTER TABLE "PROJUDI"."SERV_SUBTIPO_ASSUNTO" ADD CONSTRAINT "SERVENTIASUBTIPOASSUNTO_SERVEN" FOREIGN KEY ("ID_SERV_SUBTIPO")
	  REFERENCES "PROJUDI"."SERV_SUBTIPO" ("ID_SERV_SUBTIPO") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."SERV_SUBTIPO_ASSUNTO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."SERV_SUBTIPO_ASSUNTO" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table SERV_SUBTIPO_PROC_TIPO
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."SERV_SUBTIPO_PROC_TIPO" ADD CONSTRAINT "SERVENTIASUBTIPOPROCESSOTIPO_P" FOREIGN KEY ("ID_PROC_TIPO")
	  REFERENCES "PROJUDI"."PROC_TIPO" ("ID_PROC_TIPO") ENABLE;
 
  ALTER TABLE "PROJUDI"."SERV_SUBTIPO_PROC_TIPO" ADD CONSTRAINT "SERVENTIASUBTIPOPROCESSOTIPO_S" FOREIGN KEY ("ID_SERV_SUBTIPO")
	  REFERENCES "PROJUDI"."SERV_SUBTIPO" ("ID_SERV_SUBTIPO") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."SERV_SUBTIPO_PROC_TIPO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."SERV_SUBTIPO_PROC_TIPO" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."SERV_TIPO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."SERV_TIPO" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."SINAL" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."SINAL" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."SISTEMA" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."SISTEMA" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table TAREFA
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."TAREFA" ADD CONSTRAINT "ID_PROJETO" FOREIGN KEY ("ID_PROJETO")
	  REFERENCES "PROJUDI"."PROJETO" ("ID_PROJETO") ENABLE;
 
  ALTER TABLE "PROJUDI"."TAREFA" ADD CONSTRAINT "ID_PROJETOPARTICIPANTERESPONSA" FOREIGN KEY ("ID_PROJ_PARTIC_RESPONSAVEL")
	  REFERENCES "PROJUDI"."PROJETO_PARTICIPANTE" ("ID_PROJETO_PARTICIPANTE") ENABLE;
 
  ALTER TABLE "PROJUDI"."TAREFA" ADD CONSTRAINT "ID_TAREFAPAI" FOREIGN KEY ("ID_TAREFA_PAI")
	  REFERENCES "PROJUDI"."TAREFA" ("ID_TAREFA") ENABLE;
 
  ALTER TABLE "PROJUDI"."TAREFA" ADD CONSTRAINT "ID_TAREFAPRIORIDADE" FOREIGN KEY ("ID_TAREFA_PRIOR")
	  REFERENCES "PROJUDI"."TAREFA_PRIOR" ("ID_TAREFA_PRIOR") ENABLE;
 
  ALTER TABLE "PROJUDI"."TAREFA" ADD CONSTRAINT "ID_TAREFATIPO" FOREIGN KEY ("ID_TAREFA_TIPO")
	  REFERENCES "PROJUDI"."TAREFA_TIPO" ("ID_TAREFA_TIPO") ENABLE;
 
  ALTER TABLE "PROJUDI"."TAREFA" ADD CONSTRAINT "ID_USUARIOCRIADOR" FOREIGN KEY ("ID_USU_CRIADOR")
	  REFERENCES "PROJUDI"."USU" ("ID_USU") ENABLE;
 
  ALTER TABLE "PROJUDI"."TAREFA" ADD CONSTRAINT "ID_USUARIOFINALIZADOR" FOREIGN KEY ("ID_USU_FINALIZADOR")
	  REFERENCES "PROJUDI"."USU" ("ID_USU") ENABLE;
 
  ALTER TABLE "PROJUDI"."TAREFA" ADD CONSTRAINT "TAREFA_FK" FOREIGN KEY ("ID_TAREFA_STATUS")
	  REFERENCES "PROJUDI"."TAREFA_STATUS" ("ID_TAREFA_STATUS") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."TAREFA" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."TAREFA" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."TAREFA_PRIOR" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."TAREFA_PRIOR" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."TAREFA_STATUS" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."TAREFA_STATUS" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."TAREFA_TIPO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."TAREFA_TIPO" TO "ROLE_PROJUDI_CONSULTA";






GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."TESTE_CASE" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."TESTE_CASE" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."TESTE_RETURNING" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."TESTE_RETURNING" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table TRANS_JULGADO_EVENTO
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."TRANS_JULGADO_EVENTO" ADD CONSTRAINT "ID_COMUTACAO_FK" FOREIGN KEY ("ID_EVENTO")
	  REFERENCES "PROJUDI"."PROC_EVENTO_EXE" ("ID_PROC_EVENTO_EXE") ENABLE;
 
  ALTER TABLE "PROJUDI"."TRANS_JULGADO_EVENTO" ADD CONSTRAINT "ID_TRANSITOJULGADO_FK" FOREIGN KEY ("ID_TRANS_JULGADO")
	  REFERENCES "PROJUDI"."PROC_EVENTO_EXE" ("ID_PROC_EVENTO_EXE") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."TRANS_JULGADO_EVENTO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."TRANS_JULGADO_EVENTO" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."TT" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."TT" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."UFR_VALOR" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."UFR_VALOR" TO "ROLE_PROJUDI_CONSULTA";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE ON "PROJUDI"."UFR_VALOR" TO "ROLE_PROJUDI_GERENCIA";
--------------------------------------------------------
--  Ref Constraints for Table USU
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."USU" ADD CONSTRAINT "USUARIO_CIDADE_NATURALIDADE_FK" FOREIGN KEY ("ID_NATURALIDADE")
	  REFERENCES "PROJUDI"."CIDADE" ("ID_CIDADE") ENABLE;
 
  ALTER TABLE "PROJUDI"."USU" ADD CONSTRAINT "USUARIO_ENDERECO_FK" FOREIGN KEY ("ID_ENDERECO")
	  REFERENCES "PROJUDI"."ENDERECO" ("ID_ENDERECO") ENABLE;
 
  ALTER TABLE "PROJUDI"."USU" ADD CONSTRAINT "USUARIO_ESTADO_CTPSUF_FK" FOREIGN KEY ("ID_CTPS_UF")
	  REFERENCES "PROJUDI"."ESTADO" ("ID_ESTADO") ENABLE;
 
  ALTER TABLE "PROJUDI"."USU" ADD CONSTRAINT "USUARIO_RGORGAOEXPEDIDOR_FK" FOREIGN KEY ("ID_RG_ORGAO_EXP")
	  REFERENCES "PROJUDI"."RG_ORGAO_EXP" ("ID_RG_ORGAO_EXP") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."USU" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."USU" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table USU_AFASTAMENTO
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."USU_AFASTAMENTO" ADD CONSTRAINT "USUARIOAFASTAMENTO_AFASTAMENTO" FOREIGN KEY ("ID_AFASTAMENTO")
	  REFERENCES "PROJUDI"."AFASTAMENTO" ("ID_AFASTAMENTO") ENABLE;
 
  ALTER TABLE "PROJUDI"."USU_AFASTAMENTO" ADD CONSTRAINT "USUARIOAFASTAMENTO_USUARIO_FK" FOREIGN KEY ("ID_USU")
	  REFERENCES "PROJUDI"."USU" ("ID_USU") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."USU_AFASTAMENTO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."USU_AFASTAMENTO" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table USU_ARQ
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."USU_ARQ" ADD CONSTRAINT "USUARIOARQUIVO_USUARIO_FK" FOREIGN KEY ("ID_USU")
	  REFERENCES "PROJUDI"."USU" ("ID_USU") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."USU_ARQ" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."USU_ARQ" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table USU_MOVI_TIPO
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."USU_MOVI_TIPO" ADD CONSTRAINT "USU_MOVI_TIPO_MOVI_TIPO_FK" FOREIGN KEY ("ID_MOVI_TIPO")
	  REFERENCES "PROJUDI"."MOVI_TIPO" ("ID_MOVI_TIPO") ENABLE;
 
  ALTER TABLE "PROJUDI"."USU_MOVI_TIPO" ADD CONSTRAINT "USU_MOVI_TIPO_USU_FK" FOREIGN KEY ("ID_USU")
	  REFERENCES "PROJUDI"."USU" ("ID_USU") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."USU_MOVI_TIPO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."USU_MOVI_TIPO" TO "WCSILVA";
--------------------------------------------------------
--  Ref Constraints for Table USU_SERV
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."USU_SERV" ADD CONSTRAINT "USUARIOSERVENTIA_SERVENTIA_FK" FOREIGN KEY ("ID_SERV")
	  REFERENCES "PROJUDI"."SERV" ("ID_SERV") ENABLE;
 
  ALTER TABLE "PROJUDI"."USU_SERV" ADD CONSTRAINT "USUARIOSERVENTIA_USUARIOSERVEN" FOREIGN KEY ("ID_USU_SERV_CHEFE")
	  REFERENCES "PROJUDI"."USU_SERV" ("ID_USU_SERV") ENABLE;
 
  ALTER TABLE "PROJUDI"."USU_SERV" ADD CONSTRAINT "USUARIOSERVENTIA_USUARIO_FK" FOREIGN KEY ("ID_USU")
	  REFERENCES "PROJUDI"."USU" ("ID_USU") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."USU_SERV" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."USU_SERV" TO "ROLE_PROJUDI_CONSULTA";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."USU_SERV" TO "ROLE_PROJUDI_GERENCIA";
--------------------------------------------------------
--  Ref Constraints for Table USU_SERV_ESC
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."USU_SERV_ESC" ADD CONSTRAINT "USUARIOSERVENTIAESCALA_ESCALA_" FOREIGN KEY ("ID_ESC")
	  REFERENCES "PROJUDI"."ESC" ("ID_ESC") ENABLE;
 
  ALTER TABLE "PROJUDI"."USU_SERV_ESC" ADD CONSTRAINT "USUARIOSERVENTIAESCALA_USUARIO" FOREIGN KEY ("ID_USU_SERV")
	  REFERENCES "PROJUDI"."USU_SERV" ("ID_USU_SERV") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."USU_SERV_ESC" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."USU_SERV_ESC" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."USU_SERV_ESC_STATUS" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."USU_SERV_ESC_STATUS" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table USU_SERV_ESC_STATUS_HIST
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."USU_SERV_ESC_STATUS_HIST" ADD CONSTRAINT "USU_SV_ESC_ST_HT_USU_SV_ESC_FK" FOREIGN KEY ("ID_USU_SERV_ESC")
	  REFERENCES "PROJUDI"."USU_SERV_ESC" ("ID_USU_SERV_ESC") ENABLE;
 
  ALTER TABLE "PROJUDI"."USU_SERV_ESC_STATUS_HIST" ADD CONSTRAINT "USU_SV_ES_ST_HS_US_SV_ES_ST_FK" FOREIGN KEY ("ID_USU_SERV_ESC_STATUS")
	  REFERENCES "PROJUDI"."USU_SERV_ESC_STATUS" ("ID_USU_SERV_ESC_STATUS") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."USU_SERV_ESC_STATUS_HIST" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."USU_SERV_ESC_STATUS_HIST" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table USU_SERV_GRUPO
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."USU_SERV_GRUPO" ADD CONSTRAINT "USUARIOSERVENTIAGRUPO_GRUPO_FK" FOREIGN KEY ("ID_GRUPO")
	  REFERENCES "PROJUDI"."GRUPO" ("ID_GRUPO") ENABLE;
 
  ALTER TABLE "PROJUDI"."USU_SERV_GRUPO" ADD CONSTRAINT "USUARIOSERVENTIAGRUPO_USUARIOS" FOREIGN KEY ("ID_USU_SERV")
	  REFERENCES "PROJUDI"."USU_SERV" ("ID_USU_SERV") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."USU_SERV_GRUPO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."USU_SERV_GRUPO" TO "ROLE_PROJUDI_CONSULTA";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."USU_SERV_GRUPO" TO "ROLE_PROJUDI_GERENCIA";
--------------------------------------------------------
--  Ref Constraints for Table USU_SERV_MOVI_TIPO
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."USU_SERV_MOVI_TIPO" ADD CONSTRAINT "USU_SERV_MOV_TIPO_MOVI_TIPO_FK" FOREIGN KEY ("ID_MOVI_TIPO")
	  REFERENCES "PROJUDI"."MOVI_TIPO" ("ID_MOVI_TIPO") ENABLE;
 
  ALTER TABLE "PROJUDI"."USU_SERV_MOVI_TIPO" ADD CONSTRAINT "USU_SERV_MOV_TIPO_USU_SERV_FK" FOREIGN KEY ("ID_USU_SERV")
	  REFERENCES "PROJUDI"."USU_SERV" ("ID_USU_SERV") ENABLE;
  GRANT ALTER, DELETE, INSERT, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."USU_SERV_MOVI_TIPO" TO "PROJUDI_ALL";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."USU_SERV_OAB" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."USU_SERV_OAB" TO "ROLE_PROJUDI_CONSULTA";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."USU_SERV_OAB" TO "ROLE_PROJUDI_GERENCIA";
--------------------------------------------------------
--  Ref Constraints for Table USU_SERV_PERM
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."USU_SERV_PERM" ADD CONSTRAINT "USUARIOSERVENTIAPERMISSAO_PERM" FOREIGN KEY ("ID_PERM")
	  REFERENCES "PROJUDI"."PERM" ("ID_PERM") ENABLE;
 
  ALTER TABLE "PROJUDI"."USU_SERV_PERM" ADD CONSTRAINT "USUARIOSERVENTIAPERMISSAO_USUA" FOREIGN KEY ("ID_USU_SERV")
	  REFERENCES "PROJUDI"."USU_SERV" ("ID_USU_SERV") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."USU_SERV_PERM" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."USU_SERV_PERM" TO "ROLE_PROJUDI_CONSULTA";
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."ZONA" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."ZONA" TO "ROLE_PROJUDI_CONSULTA";
--------------------------------------------------------
--  Ref Constraints for Table ZONA_BAIRRO
--------------------------------------------------------

  ALTER TABLE "PROJUDI"."ZONA_BAIRRO" ADD CONSTRAINT "ZONABAIRRO_BAIRRO_FK" FOREIGN KEY ("ID_BAIRRO")
	  REFERENCES "PROJUDI"."BAIRRO" ("ID_BAIRRO") ENABLE;
 
  ALTER TABLE "PROJUDI"."ZONA_BAIRRO" ADD CONSTRAINT "ZONABAIRRO_ZONA_FK" FOREIGN KEY ("ID_ZONA")
	  REFERENCES "PROJUDI"."ZONA" ("ID_ZONA") ENABLE;
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "PROJUDI"."ZONA_BAIRRO" TO "PROJUDI_ALL";
 
  GRANT SELECT ON "PROJUDI"."ZONA_BAIRRO" TO "ROLE_PROJUDI_CONSULTA";