CREATE OR REPLACE VIEW VIEW_AUDI_PROC_COMPLETA AS
  SELECT AP.ID_AUDI_PROC        AS ID_AUDI_PROC,
    VUS.ID_AUDI                 AS ID_AUDI,
    VUS.DATA_AGENDADA           AS DATA_AGENDADA,
    VUS.DATA_MOVI               AS DATA_MOVI_AUDI,
    VUS.ID_AUDI_TIPO            AS ID_AUDI_TIPO,
    AT.AUDI_TIPO                AS AUDI_TIPO,
    AT.AUDI_TIPO_CODIGO         AS AUDI_TIPO_CODIGO,
    AP.ID_AUDI_PROC_STATUS      AS ID_AUDI_PROC_STATUS,
    APS.AUDI_PROC_STATUS        AS AUDI_PROC_STATUS,
    APS.AUDI_PROC_STATUS_CODIGO AS AUDI_PROC_STATUS_CODIGO,
    AP.ID_SERV_CARGO            AS ID_SERV_CARGO,
    SC.SERV_CARGO               AS SERV_CARGO,
    AP.ID_PROC                  AS ID_PROC,
    (P.PROC_NUMERO
    || '.'
    || P.DIGITO_VERIFICADOR)     AS PROC_NUMERO,
    AP.DATA_MOVI                 AS DATA_MOVI_AUDI_PROC,
    APR.ID_AUDI_PROC_RESPONSAVEL AS ID_AUDI_PROC_RESPONSAVEL,
    US.ID_USU_SERV               AS ID_USU_SERV,
    U.ID_USU                     AS ID_USU,
    U.USU                        AS USU,
    AP.CODIGO_TEMP               AS CODIGO_TEMP,
    AP.ID_AUDI_PROC_STATUS_ANA   AS ID_AUDI_PROC_STATUS_ANA,
    AP.ID_ARQ_ATA                AS ID_ARQ_ATA,
    AP.DATA_AUDI_ORIGINAL        AS DATA_AUDI_ORIGINAL,
    AP.ID_ARQ_ATA_ADIAMENTO      AS ID_ARQ_ATA_ADIAMENTO,
    AP.ID_ARQ_ATA_INICIADO       AS ID_ARQ_ATA_INICIADO,
    VUS.ID_ARQ_FINALIZACAO       AS ID_ARQ_FINALIZACAO,
    AP.ID_SERV_CARGO_PRESIDENTE  AS ID_SERV_CARGO_PRESIDENTE,
    SCP.SERV_CARGO               AS SERV_CARGO_PRESIDENTE,
    UP.USU                       AS USU_PRESIDENTE,
    UP.NOME                      AS NOME_PRESIDENTE,
    SCP.ID_SERV                  AS ID_SERV_PRESIDENTE,
    SP.SERV                      AS SERV_PRESIDENTE,
    AP.ID_SERV_CARGO_MP          AS ID_SERV_CARGO_MP,
    SCMP.SERV_CARGO              AS SERV_CARGO_MP,
    UMP.USU                      AS USU_MP,
    UMP.NOME                     AS NOME_MP,
    SCMP.ID_SERV                 AS ID_SERV_MP,
    SMP.SERV                     AS SERV_MP,
    AP.ID_SERV_CARGO_REDATOR     AS ID_SERV_CARGO_REDATOR,
    SCR.SERV_CARGO               AS SERV_CARGO_REDATOR,
    UR.USU                       AS USU_REDATOR,
    UR.NOME                      AS NOME_REDATOR,
    SCR.ID_SERV                  AS ID_SERV_REDATOR,
    SR.SERV                      AS SERV_REDATOR,
    AP.ID_PROC_TIPO              AS ID_PROC_TIPO_AUDIENCIA,
    PTAP.PROC_TIPO               AS PROC_TIPO_AUDIENCIA,
    PTAP.POLO_ATIVO              AS POLO_ATIVO,
    PTAP.POLO_PASSIVO            AS POLO_PASSIVO,
    AP.ID_PEND_VOTO              AS ID_PEND_VOTO,
    AP.ID_PEND_EMENTA            AS ID_PEND_EMENTA,
    AP.ID_PEND_VOTO_REDATOR      AS ID_PEND_VOTO_REDATOR,
    AP.ID_PEND_EMENTA_REDATOR    AS ID_PEND_EMENTA_REDATOR,
    VUS.VIRTUAL                  AS VIRTUAL,
    VUS.SESSAO_INICIADA          AS SESSAO_INICIADA,
	AP.ID_AUDI_PROC_ORIGEM       AS ID_AUDI_PROC_ORIGEM
  FROM ((((((((((((((((((((((((AUDI_PROC AP
  JOIN AUDI VUS
  ON((AP.ID_AUDI = VUS.ID_AUDI)))
  JOIN AUDI_TIPO AT
  ON((VUS.ID_AUDI_TIPO = AT.ID_AUDI_TIPO)))
  JOIN SERV_CARGO SC
  ON((AP.ID_SERV_CARGO = SC.ID_SERV_CARGO)))
  JOIN AUDI_PROC_STATUS APS
  ON((AP.ID_AUDI_PROC_STATUS = APS.ID_AUDI_PROC_STATUS)))
  LEFT JOIN PROC P
  ON((AP.ID_PROC = P.ID_PROC)))
  LEFT JOIN AUDI_PROC_RESP APR
  ON((AP.ID_AUDI_PROC = APR.ID_AUDI_PROC)))
  LEFT JOIN USU_SERV US
  ON((APR.ID_USU_SERV = US.ID_USU_SERV)))
  LEFT JOIN USU U
  ON((US.ID_USU = U.ID_USU)))
  LEFT JOIN SERV_CARGO SCP
  ON((AP.ID_SERV_CARGO_PRESIDENTE = SCP.ID_SERV_CARGO)))
  LEFT JOIN USU_SERV_GRUPO USGP
  ON((SCP.ID_USU_SERV_GRUPO = USGP.ID_USU_SERV_GRUPO)))
  LEFT JOIN USU_SERV USP
  ON((USGP.ID_USU_SERV = USP.ID_USU_SERV)))
  LEFT JOIN USU UP
  ON((USP.ID_USU = UP.ID_USU)))
  LEFT JOIN SERV SP
  ON((SCP.ID_SERV = SP.ID_SERV)))
  LEFT JOIN SERV_CARGO SCMP
  ON((AP.ID_SERV_CARGO_MP = SCMP.ID_SERV_CARGO)))
  LEFT JOIN USU_SERV_GRUPO USGMP
  ON((SCMP.ID_USU_SERV_GRUPO = USGMP.ID_USU_SERV_GRUPO)))
  LEFT JOIN USU_SERV USMP
  ON((USGMP.ID_USU_SERV = USMP.ID_USU_SERV)))
  LEFT JOIN USU UMP
  ON((USMP.ID_USU = UMP.ID_USU)))
  LEFT JOIN SERV SMP
  ON((SCMP.ID_SERV = SMP.ID_SERV)))
  LEFT JOIN SERV_CARGO SCR
  ON((AP.ID_SERV_CARGO_REDATOR = SCR.ID_SERV_CARGO)))
  LEFT JOIN USU_SERV_GRUPO USGR
  ON((SCR.ID_USU_SERV_GRUPO = USGR.ID_USU_SERV_GRUPO)))
  LEFT JOIN USU_SERV USR
  ON((USGR.ID_USU_SERV = USR.ID_USU_SERV)))
  LEFT JOIN USU UR
  ON((USR.ID_USU = UR.ID_USU)))
  LEFT JOIN SERV SR
  ON((SCR.ID_SERV = SR.ID_SERV)))
  LEFT JOIN PROC_TIPO PTAP
  ON((AP.ID_PROC_TIPO = PTAP.ID_PROC_TIPO)))
