-- Não é possível renderizar a DLL VIEW para o objeto PROJUDI.VIEW_PROX_AUDI_LIVRE_MANUAL com o DBMS_METADATA tentando um gerador interno.
CREATE VIEW PROJUDI.VIEW_PROX_AUDI_LIVRE_MANUAL
AS SELECT 
    VUS.ID_AUDI AS ID_AUDI,
    VUS.ID_AUDI_TIPO AS ID_AUDI_TIPO,
    AT.AUDI_TIPO AS AUDI_TIPO,
    AT.AUDI_TIPO_CODIGO AS AUDI_TIPO_CODIGO,
    VUS.DATA_AGENDADA AS DATA_AGENDADA,
    VUS.DATA_MOVI AS DATA_MOVI_AUDI,
    VUS.RESERVADA AS RESERVADA,
    AP.ID_AUDI_PROC AS ID_AUDI_PROC,
    AP.ID_AUDI_PROC_STATUS AS ID_AUDI_PROC_STATUS,
    AP.ID_SERV_CARGO AS ID_SERV_CARGO,
    SC.SERV_CARGO AS SERV_CARGO,
    SC.ID_CARGO_TIPO AS ID_CARGO_TIPO,
    CT.CARGO_TIPO AS CARGO_TIPO,
    SC.ID_SERV AS ID_SERV,
    S.SERV AS SERV,
    AP.ID_PROC AS ID_PROC,
    AP.DATA_MOVI AS DATA_MOVI_AUDI_PROC,
    VUS.CODIGO_TEMP AS CODIGO_TEMP 
  FROM 
    (((((AUDI VUS JOIN AUDI_TIPO AT ON((VUS.ID_AUDI_TIPO = AT.ID_AUDI_TIPO))) JOIN AUDI_PROC AP ON((VUS.ID_AUDI = AP.ID_AUDI))) JOIN SERV_CARGO SC ON((AP.ID_SERV_CARGO = SC.ID_SERV_CARGO))) JOIN CARGO_TIPO CT ON((SC.ID_CARGO_TIPO = CT.ID_CARGO_TIPO))) JOIN SERV S ON((SC.ID_SERV = S.ID_SERV))) 
  WHERE 
    ((AT.AUDI_TIPO_CODIGO <> 12) AND (AP.ID_AUDI_PROC_STATUS = 8) AND (VUS.DATA_MOVI IS NULL) AND (AP.DATA_MOVI IS NULL) AND (AP.ID_PROC IS NULL)) 
  ORDER BY 
    VUS.DATA_AGENDADA
