-- Não é possível renderizar a DLL VIEW para o objeto PROJUDI.VIEW_AUDI_COMPLETA com o DBMS_METADATA tentando um gerador interno.
CREATE VIEW PROJUDI.VIEW_AUDI_COMPLETA
AS SELECT VUS.ID_AUDI            AS ID_AUDI,
    VUS.ID_AUDI_TIPO            AS ID_AUDI_TIPO,
    AT.AUDI_TIPO                AS AUDI_TIPO,
    AT.AUDI_TIPO_CODIGO         AS AUDI_TIPO_CODIGO,
    VUS.DATA_AGENDADA           AS DATA_AGENDADA,
    VUS.DATA_MOVI               AS DATA_MOVI_AUDI,
    VUS.RESERVADA               AS RESERVADA,
    AP.ID_AUDI_PROC             AS ID_AUDI_PROC,
    AP.ID_AUDI_PROC_STATUS      AS ID_AUDI_PROC_STATUS,
    APS.AUDI_PROC_STATUS        AS AUDI_PROC_STATUS,
    APS.AUDI_PROC_STATUS_CODIGO AS AUDI_PROC_STATUS_CODIGO,
    AP.ID_SERV_CARGO            AS ID_SERV_CARGO,
    SC.SERV_CARGO               AS SERV_CARGO,
    U.USU                       AS USU,
    U.NOME                      AS NOME,
    S.ID_SERV                   AS ID_SERV,
    S.SERV                      AS SERV,
    AP.ID_PROC                  AS ID_PROC,
    P.PROC_NUMERO               AS PROC_NUMERO,
    P.DIGITO_VERIFICADOR        AS DIGITO_VERIFICADOR,
    (P.PROC_NUMERO
    || '.'
    || P.DIGITO_VERIFICADOR)     AS PROC_NUMERO_COMPLETO,
    AP.DATA_MOVI                 AS DATA_MOVI_AUDI_PROC,
    R.ID_RECURSO                 AS ID_RECURSO,
    R.DATA_RETORNO               AS DATA_RETORNO,
    VUS.CODIGO_TEMP              AS CODIGO_TEMP,
    AP.CODIGO_TEMP               AS CODIGO_TEMP_AUDI_PROC,
    AP.ID_AUDI_PROC_STATUS_ANA   AS ID_AUDI_PROC_STATUS_ANA,
    APS2.AUDI_PROC_STATUS        AS AUDI_PROC_STATUS_ANA,
    APS2.AUDI_PROC_STATUS_CODIGO AS AUDI_PROC_STATUS_CODIGO_ANA,
    AP.ID_ARQ_ATA                AS ID_ARQ_ATA,
    AP.DATA_AUDI_ORIGINAL        AS DATA_AUDI_ORIGINAL,
    AP.ID_ARQ_ATA_ADIAMENTO      AS ID_ARQ_ATA_ADIAMENTO,
    AP.ID_ARQ_ATA_INICIADO       AS ID_ARQ_ATA_INICIADO,
    PTP.ORDEM_2_GRAU             AS ORDEM_2_GRAU,
    PTP.ID_PROC_TIPO             AS ID_PROC_TIPO,
    PTP.PROC_TIPO_CODIGO         AS PROC_TIPO_CODIGO,
    PTP.PROC_TIPO                AS PROC_TIPO,
    VUS.ID_ARQ_FINALIZACAO       AS ID_ARQ_FINALIZACAO,
    AP.ID_SERV_CARGO_PRESIDENTE  AS ID_SERV_CARGO_PRESIDENTE,
    SCP.SERV_CARGO               AS SERV_CARGO_PRESIDENTE,
    UP.USU                       AS USU_PRESIDENTE,
    UP.NOME                      AS NOME_PRESIDENTE,
    SCP.ID_SERV                  AS ID_SERV_PRESIDENTE,
    SP.SERV                      AS SERV_PRESIDENTE,
    AP.ID_SERV_CARGO_MP          AS ID_SERV_CARGO_MP,
    SCMP.SERV_CARGO              AS SERV_CARGO_MP,
    UMP.USU                      AS USU_MP,
    UMP.NOME                     AS NOME_MP,
    SCMP.ID_SERV                 AS ID_SERV_MP,
    SMP.SERV                     AS SERV_MP,
    AP.ID_SERV_CARGO_REDATOR     AS ID_SERV_CARGO_REDATOR,
    SCR.SERV_CARGO               AS SERV_CARGO_REDATOR,
    UR.USU                       AS USU_REDATOR,
    UR.NOME                      AS NOME_REDATOR,
    SCR.ID_SERV                  AS ID_SERV_REDATOR,
    SR.SERV                      AS SERV_REDATOR,
    (SELECT PP.ID_PROC_PARTE
      || '__@--'
      || PP.NOME
      || '__@--'
      || PP.PROC_PARTE_TIPO
    FROM VIEW_PROC_PARTE PP
    WHERE PP.DATA_BAIXA           IS NULL
    AND PP.PROC_PARTE_TIPO_CODIGO IN (1, 5)
    AND PP.ID_PROC                 = AP.ID_PROC
    AND ROWNUM                     = 1
    ) AS PRIMEIRO_PROMOVENTE_RECORRENTE,
    (SELECT PP.ID_PROC_PARTE
      || '__@--'
      || PP.NOME
      || '__@--'
      || PP.PROC_PARTE_TIPO
    FROM VIEW_PROC_PARTE PP
    WHERE PP.DATA_BAIXA           IS NULL
    AND PP.PROC_PARTE_TIPO_CODIGO IN (0, 6)
    AND PP.ID_PROC                 = AP.ID_PROC
    AND ROWNUM                     = 1
    ) AS PRIMEIRO_PROMOVIDO_RECORRIDO
  FROM ((((((((((((((((((((((((((((AUDI VUS
  JOIN AUDI_TIPO AT
  ON((VUS.ID_AUDI_TIPO = AT.ID_AUDI_TIPO)))
  JOIN SERV S
  ON((VUS.ID_SERV = S.ID_SERV)))
  LEFT JOIN AUDI_PROC AP
  ON((VUS.ID_AUDI = AP.ID_AUDI)))
  LEFT JOIN AUDI_PROC_STATUS APS
  ON((AP.ID_AUDI_PROC_STATUS = APS.ID_AUDI_PROC_STATUS)))
  LEFT JOIN SERV_CARGO SC
  ON((AP.ID_SERV_CARGO = SC.ID_SERV_CARGO)))
  LEFT JOIN USU_SERV_GRUPO USG
  ON((SC.ID_USU_SERV_GRUPO = USG.ID_USU_SERV_GRUPO)))
  LEFT JOIN USU_SERV US
  ON((USG.ID_USU_SERV = US.ID_USU_SERV)))
  LEFT JOIN USU U
  ON((US.ID_USU = U.ID_USU)))
  LEFT JOIN PROC P
  ON((AP.ID_PROC = P.ID_PROC)))
  LEFT JOIN PROC_TIPO PTP
  ON((P.ID_PROC_TIPO = PTP.ID_PROC_TIPO)))
  LEFT JOIN RECURSO R
  ON((R.ID_PROC       = P.ID_PROC
  AND R.DATA_RETORNO IS NULL)))
  LEFT JOIN PROC_TIPO PTR
  ON((R.ID_PROC_TIPO = PTR.ID_PROC_TIPO)))
  LEFT JOIN AUDI_PROC_STATUS APS2
  ON((AP.ID_AUDI_PROC_STATUS_ANA = APS2.ID_AUDI_PROC_STATUS)))
  LEFT JOIN SERV_CARGO SCP
  ON((AP.ID_SERV_CARGO_PRESIDENTE = SCP.ID_SERV_CARGO)))
  LEFT JOIN USU_SERV_GRUPO USGP
  ON((SCP.ID_USU_SERV_GRUPO = USGP.ID_USU_SERV_GRUPO)))
  LEFT JOIN USU_SERV USP
  ON((USGP.ID_USU_SERV = USP.ID_USU_SERV)))
  LEFT JOIN USU UP
  ON((USP.ID_USU = UP.ID_USU)))
  LEFT JOIN SERV SP
  ON((SCP.ID_SERV = SP.ID_SERV)))
  LEFT JOIN SERV_CARGO SCMP
  ON((AP.ID_SERV_CARGO_MP = SCMP.ID_SERV_CARGO)))
  LEFT JOIN USU_SERV_GRUPO USGMP
  ON((SCMP.ID_USU_SERV_GRUPO = USGMP.ID_USU_SERV_GRUPO)))
  LEFT JOIN USU_SERV USMP
  ON((USGMP.ID_USU_SERV = USMP.ID_USU_SERV)))
  LEFT JOIN USU UMP
  ON((USMP.ID_USU = UMP.ID_USU)))
  LEFT JOIN SERV SMP
  ON((SCMP.ID_SERV = SMP.ID_SERV)))
  LEFT JOIN SERV_CARGO SCR
  ON((AP.ID_SERV_CARGO_REDATOR = SCR.ID_SERV_CARGO)))
  LEFT JOIN USU_SERV_GRUPO USGR
  ON((SCR.ID_USU_SERV_GRUPO = USGR.ID_USU_SERV_GRUPO)))
  LEFT JOIN USU_SERV USR
  ON((USGR.ID_USU_SERV = USR.ID_USU_SERV)))
  LEFT JOIN USU UR
  ON((USR.ID_USU = UR.ID_USU)))
  LEFT JOIN SERV SR
  ON((SCR.ID_SERV   = SR.ID_SERV)))
  WHERE ID_RECURSO IS NULL
  UNION ALL
  SELECT VUS.ID_AUDI            AS ID_AUDI,
    VUS.ID_AUDI_TIPO            AS ID_AUDI_TIPO,
    AT.AUDI_TIPO                AS AUDI_TIPO,
    AT.AUDI_TIPO_CODIGO         AS AUDI_TIPO_CODIGO,
    VUS.DATA_AGENDADA           AS DATA_AGENDADA,
    VUS.DATA_MOVI               AS DATA_MOVI_AUDI,
    VUS.RESERVADA               AS RESERVADA,
    AP.ID_AUDI_PROC             AS ID_AUDI_PROC,
    AP.ID_AUDI_PROC_STATUS      AS ID_AUDI_PROC_STATUS,
    APS.AUDI_PROC_STATUS        AS AUDI_PROC_STATUS,
    APS.AUDI_PROC_STATUS_CODIGO AS AUDI_PROC_STATUS_CODIGO,
    AP.ID_SERV_CARGO            AS ID_SERV_CARGO,
    SC.SERV_CARGO               AS SERV_CARGO,
    U.USU                       AS USU,
    U.NOME                      AS NOME,
    SC.ID_SERV                  AS ID_SERV,
    S.SERV                      AS SERV,
    AP.ID_PROC                  AS ID_PROC,
    P.PROC_NUMERO               AS PROC_NUMERO,
    P.DIGITO_VERIFICADOR        AS DIGITO_VERIFICADOR,
    (P.PROC_NUMERO
    || '.'
    || P.DIGITO_VERIFICADOR)     AS PROC_NUMERO_COMPLETO,
    AP.DATA_MOVI                 AS DATA_MOVI_AUDI_PROC,
    R.ID_RECURSO                 AS ID_RECURSO,
    R.DATA_RETORNO               AS DATA_RETORNO,
    VUS.CODIGO_TEMP              AS CODIGO_TEMP,
    AP.CODIGO_TEMP               AS CODIGO_TEMP_AUDI_PROC,
    AP.ID_AUDI_PROC_STATUS_ANA   AS ID_AUDI_PROC_STATUS_ANA,
    APS2.AUDI_PROC_STATUS        AS AUDI_PROC_STATUS_ANA,
    APS2.AUDI_PROC_STATUS_CODIGO AS AUDI_PROC_STATUS_CODIGO_ANA,
    AP.ID_ARQ_ATA                AS ID_ARQ_ATA,
    AP.DATA_AUDI_ORIGINAL        AS DATA_AUDI_ORIGINAL,
    AP.ID_ARQ_ATA_ADIAMENTO      AS ID_ARQ_ATA_ADIAMENTO,
    AP.ID_ARQ_ATA_INICIADO       AS ID_ARQ_ATA_INICIADO,
    PTR.ORDEM_2_GRAU             AS ORDEM_2_GRAU,
    PTR.ID_PROC_TIPO             AS ID_PROC_TIPO,
    PTR.PROC_TIPO_CODIGO         AS PROC_TIPO_CODIGO,
    PTR.PROC_TIPO                AS PROC_TIPO,
    VUS.ID_ARQ_FINALIZACAO       AS ID_ARQ_FINALIZACAO,
    AP.ID_SERV_CARGO_PRESIDENTE  AS ID_SERV_CARGO_PRESIDENTE,
    SCP.SERV_CARGO               AS SERV_CARGO_PRESIDENTE,
    UP.USU                       AS USU_PRESIDENTE,
    UP.NOME                      AS NOME_PRESIDENTE,
    SCP.ID_SERV                  AS ID_SERV_PRESIDENTE,
    SP.SERV                      AS SERV_PRESIDENTE,
    AP.ID_SERV_CARGO_MP          AS ID_SERV_CARGO_MP,
    SCMP.SERV_CARGO              AS SERV_CARGO_MP,
    UMP.USU                      AS USU_MP,
    UMP.NOME                     AS NOME_MP,
    SCMP.ID_SERV                 AS ID_SERV_MP,
    SMP.SERV                     AS SERV_MP,
    AP.ID_SERV_CARGO_REDATOR     AS ID_SERV_CARGO_REDATOR,
    SCR.SERV_CARGO               AS SERV_CARGO_REDATOR,
    UR.USU                       AS USU_REDATOR,
    UR.NOME                      AS NOME_REDATOR,
    SCR.ID_SERV                  AS ID_SERV_REDATOR,
    SR.SERV                      AS SERV_REDATOR,
    (SELECT RP.ID_PROC_PARTE
      || '__@--'
      || RP.NOME
      || '__@--'
      || RP.PROC_PARTE_TIPO
    FROM VIEW_RECURSO_PARTE RP
    WHERE RP.DATA_BAIXA           IS NULL
    AND RP.PROC_PARTE_TIPO_CODIGO IN (1, 5)
    AND RP.ID_PROC                 = AP.ID_PROC
    AND ROWNUM                     = 1
    ) AS PRIMEIRO_PROMOVENTE_RECORRENTE,
    (SELECT RP.ID_PROC_PARTE
      || '__@--'
      || RP.NOME
      || '__@--'
      || RP.PROC_PARTE_TIPO
    FROM VIEW_RECURSO_PARTE RP
    WHERE RP.DATA_BAIXA           IS NULL
    AND RP.PROC_PARTE_TIPO_CODIGO IN (0, 6)
    AND RP.ID_PROC                 = AP.ID_PROC
    AND ROWNUM                     = 1
    ) AS PRIMEIRO_PROMOVIDO_RECORRIDO
  FROM ((((((((((((((((((((((((((((AUDI VUS
  JOIN AUDI_TIPO AT
  ON((VUS.ID_AUDI_TIPO = AT.ID_AUDI_TIPO)))
  JOIN SERV S
  ON((VUS.ID_SERV = S.ID_SERV)))
  LEFT JOIN AUDI_PROC AP
  ON((VUS.ID_AUDI = AP.ID_AUDI)))
  LEFT JOIN AUDI_PROC_STATUS APS
  ON((AP.ID_AUDI_PROC_STATUS = APS.ID_AUDI_PROC_STATUS)))
  LEFT JOIN SERV_CARGO SC
  ON((AP.ID_SERV_CARGO = SC.ID_SERV_CARGO)))
  LEFT JOIN USU_SERV_GRUPO USG
  ON((SC.ID_USU_SERV_GRUPO = USG.ID_USU_SERV_GRUPO)))
  LEFT JOIN USU_SERV US
  ON((USG.ID_USU_SERV = US.ID_USU_SERV)))
  LEFT JOIN USU U
  ON((US.ID_USU = U.ID_USU)))
  LEFT JOIN PROC P
  ON((AP.ID_PROC = P.ID_PROC)))
  LEFT JOIN PROC_TIPO PTP
  ON((P.ID_PROC_TIPO = PTP.ID_PROC_TIPO)))
  LEFT JOIN RECURSO R
  ON((R.ID_PROC       = P.ID_PROC
  AND R.DATA_RETORNO IS NULL)))
  LEFT JOIN PROC_TIPO PTR
  ON((R.ID_PROC_TIPO = PTR.ID_PROC_TIPO)))
  LEFT JOIN AUDI_PROC_STATUS APS2
  ON((AP.ID_AUDI_PROC_STATUS_ANA = APS2.ID_AUDI_PROC_STATUS)))
  LEFT JOIN SERV_CARGO SCP
  ON((AP.ID_SERV_CARGO_PRESIDENTE = SCP.ID_SERV_CARGO)))
  LEFT JOIN USU_SERV_GRUPO USGP
  ON((SCP.ID_USU_SERV_GRUPO = USGP.ID_USU_SERV_GRUPO)))
  LEFT JOIN USU_SERV USP
  ON((USGP.ID_USU_SERV = USP.ID_USU_SERV)))
  LEFT JOIN USU UP
  ON((USP.ID_USU = UP.ID_USU)))
  LEFT JOIN SERV SP
  ON((SCP.ID_SERV = SP.ID_SERV)))
  LEFT JOIN SERV_CARGO SCMP
  ON((AP.ID_SERV_CARGO_MP = SCMP.ID_SERV_CARGO)))
  LEFT JOIN USU_SERV_GRUPO USGMP
  ON((SCMP.ID_USU_SERV_GRUPO = USGMP.ID_USU_SERV_GRUPO)))
  LEFT JOIN USU_SERV USMP
  ON((USGMP.ID_USU_SERV = USMP.ID_USU_SERV)))
  LEFT JOIN USU UMP
  ON((USMP.ID_USU = UMP.ID_USU)))
  LEFT JOIN SERV SMP
  ON((SCMP.ID_SERV = SMP.ID_SERV)))
  LEFT JOIN SERV_CARGO SCR
  ON((AP.ID_SERV_CARGO_REDATOR = SCR.ID_SERV_CARGO)))
  LEFT JOIN USU_SERV_GRUPO USGR
  ON((SCR.ID_USU_SERV_GRUPO = USGR.ID_USU_SERV_GRUPO)))
  LEFT JOIN USU_SERV USR
  ON((USGR.ID_USU_SERV = USR.ID_USU_SERV)))
  LEFT JOIN USU UR
  ON((USR.ID_USU = UR.ID_USU)))
  LEFT JOIN SERV SR
  ON((SCR.ID_SERV       = SR.ID_SERV)))
  WHERE NOT ID_RECURSO IS NULL
