INSERT INTO PROJUDI.AUDI_PROC_STATUS(ID_AUDI_PROC_STATUS, AUDI_PROC_STATUS_CODIGO, AUDI_PROC_STATUS, ID_SERV_TIPO) VALUES (41, 41, 'Cautelar Deferida', 15);

INSERT INTO PROJUDI.AUDI_PROC_STATUS(ID_AUDI_PROC_STATUS, AUDI_PROC_STATUS_CODIGO, AUDI_PROC_STATUS, ID_SERV_TIPO) VALUES (42, 42, 'Cautelar Indeferida', 15);

INSERT INTO PROJUDI.AUDI_PROC_STATUS(ID_AUDI_PROC_STATUS, AUDI_PROC_STATUS_CODIGO, AUDI_PROC_STATUS, ID_SERV_TIPO) VALUES (43, 43, 'Extinto sem Resolução do Mérito', 15);

INSERT INTO PROJUDI.MOVI_TIPO (MOVI_TIPO_CODIGO, MOVI_TIPO, ID_CNJ_MOVI) VALUES (40014, 'CAUTELAR DEFERIDA', 237);

INSERT INTO PROJUDI.MOVI_TIPO (MOVI_TIPO_CODIGO, MOVI_TIPO, ID_CNJ_MOVI) VALUES (40015, 'CAUTELAR INDEFERIDA', 239);

INSERT INTO PROJUDI.MOVI_TIPO (MOVI_TIPO_CODIGO, MOVI_TIPO, ID_CNJ_MOVI) VALUES (40016, 'EXTINTO SEM RESOLUÇÃO DO MÉRITO', 456);