ALTER TABLE CALCULO_LIQUIDACAO ADD DATA_HOMOLOGACAO DATE;

CREATE OR REPLACE FORCE VIEW "PROJUDI"."VIEW_CALCULO_LIQUIDACAO" ("ID_CALCULO_LIQUIDACAO", "ID_PROC", "DATA_CALCULO", "DATA_REQ_TEMPORAL_LIVRAMENTO", "DATA_REQ_TEMPORAL_PROGRESSAO", "DATA_TERMINO_PENA", "DATA_VALIDADE_MAND_PRISAO", "INFORMACAO_ADICIONAL", "RELATORIO", "DATA_HOMOLOGACAO", "ID_USU_SERV")
                                                    AS
  SELECT CALCULO_LIQUIDACAO.ID_CALCULO_LIQUIDACAO   AS ID_CALCULO_LIQUIDACAO,
    CALCULO_LIQUIDACAO.ID_PROC                      AS ID_PROC,
    CALCULO_LIQUIDACAO.DATA_CALCULO                 AS DATA_CALCULO,
    CALCULO_LIQUIDACAO.DATA_REQ_TEMPORAL_LIVRAMENTO AS DATA_REQ_TEMPORAL_LIVRAMENTO,
    CALCULO_LIQUIDACAO.DATA_REQ_TEMPORAL_PROGRESSAO AS DATA_REQ_TEMPORAL_PROGRESSAO,
    CALCULO_LIQUIDACAO.DATA_TERMINO_PENA            AS DATA_TERMINO_PENA,
    CALCULO_LIQUIDACAO.DATA_VALIDADE_MAND_PRISAO    AS DATA_VALIDADE_MAND_PRISAO,
    CALCULO_LIQUIDACAO.INFORMACAO_ADICIONAL         AS INFORMACAO_ADICIONAL,
    CALCULO_LIQUIDACAO.RELATORIO                    AS RELATORIO,
    CALCULO_LIQUIDACAO.DATA_HOMOLOGACAO             AS DATA_HOMOLOGACAO,
    CALCULO_LIQUIDACAO.ID_USU_SERV                  AS ID_USU_SERV
  FROM CALCULO_LIQUIDACAO;
