REM INSERTING into PERM
SET DEFINE OFF;
Insert into PERM (ID_PERM,PERM_CODIGO,PERM,ID_PERM_PAI,ID_PERM_ESPECIAL,E_MENU,LINK,IR_PARA,TITULO,ORDENACAO,CODIGO_TEMP) values ('24970','913','Partes Isentas','27',null,'1','PartesIsenta','userMainFrame','Partes Isentas','1000',null);
Insert into PERM (ID_PERM,PERM_CODIGO,PERM,ID_PERM_PAI,ID_PERM_ESPECIAL,E_MENU,LINK,IR_PARA,TITULO,ORDENACAO,CODIGO_TEMP) values ('24971','9130','Partes Isentas EXCLUIR','24970',null,'0','#','userMainFrame',' ','1000',null);
Insert into PERM (ID_PERM,PERM_CODIGO,PERM,ID_PERM_PAI,ID_PERM_ESPECIAL,E_MENU,LINK,IR_PARA,TITULO,ORDENACAO,CODIGO_TEMP) values ('24972','9131','Partes Isentas IMPRIMIR','24970',null,'0','#','userMainFrame',' ','1000',null);
Insert into PERM (ID_PERM,PERM_CODIGO,PERM,ID_PERM_PAI,ID_PERM_ESPECIAL,E_MENU,LINK,IR_PARA,TITULO,ORDENACAO,CODIGO_TEMP) values ('24973','9132','Partes Isentas LOCALIZAR','24970',null,'0','#','userMainFrame',' ','1000',null);
Insert into PERM (ID_PERM,PERM_CODIGO,PERM,ID_PERM_PAI,ID_PERM_ESPECIAL,E_MENU,LINK,IR_PARA,TITULO,ORDENACAO,CODIGO_TEMP) values ('24974','9133','Partes Isentas LOCALIZARDWR','24970',null,'0','#','userMainFrame',' ','1000',null);
Insert into PERM (ID_PERM,PERM_CODIGO,PERM,ID_PERM_PAI,ID_PERM_ESPECIAL,E_MENU,LINK,IR_PARA,TITULO,ORDENACAO,CODIGO_TEMP) values ('24975','9134','Partes Isentas NOVO','24970',null,'0','#','userMainFrame',' ','1000',null);
Insert into PERM (ID_PERM,PERM_CODIGO,PERM,ID_PERM_PAI,ID_PERM_ESPECIAL,E_MENU,LINK,IR_PARA,TITULO,ORDENACAO,CODIGO_TEMP) values ('24976','9135','Partes Isentas SALVAR','24970',null,'0','#','userMainFrame',' ','1000',null);
Insert into PERM (ID_PERM,PERM_CODIGO,PERM,ID_PERM_PAI,ID_PERM_ESPECIAL,E_MENU,LINK,IR_PARA,TITULO,ORDENACAO,CODIGO_TEMP) values ('24977','9136','Partes Isentas CURINGA6','24970',null,'0','#','userMainFrame',' ','1000',null);
Insert into PERM (ID_PERM,PERM_CODIGO,PERM,ID_PERM_PAI,ID_PERM_ESPECIAL,E_MENU,LINK,IR_PARA,TITULO,ORDENACAO,CODIGO_TEMP) values ('24978','9137','Partes Isentas CURINGA7','24970',null,'0','#','userMainFrame',' ','1000',null);
Insert into PERM (ID_PERM,PERM_CODIGO,PERM,ID_PERM_PAI,ID_PERM_ESPECIAL,E_MENU,LINK,IR_PARA,TITULO,ORDENACAO,CODIGO_TEMP) values ('24979','9138','Partes Isentas CURINGA8','24970',null,'0','#','userMainFrame',' ','1000',null);
Insert into PERM (ID_PERM,PERM_CODIGO,PERM,ID_PERM_PAI,ID_PERM_ESPECIAL,E_MENU,LINK,IR_PARA,TITULO,ORDENACAO,CODIGO_TEMP) values ('24980','9139','Partes Isentas CURINGA9','24970',null,'0','#','userMainFrame',' ','1000',null);
