package br.gov.go.tj.projudi.types;

import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public enum PendenciaTipo {
	CARTA_CITACAO(1), INTIMACAO(2), ALVARA(3), MANDADO(4), EDITAL(5), OFICIO(6), CARTA_PRECATORIA(7),
	CARTA_ADJUDICACAO(8), CUMPRIMENTO_GENERICO(9), VERIFICAR_NOVO_PROCESSO(10), CONCLUSO_DECISAO(11),
	CONCLUSO_DESPACHO(12), CONCLUSO_SENTENCA(13), CONCLUSO_GENERICO(14), PUBLICACAO_PUBLICA(15), VERIFICAR_PETICAO(16),
	VERIFICAR_PROCESSO(17), CONCLUSO_PRESIDENTE(18), CONCLUSO_RELATOR(19), CONCLUSO_DESPACHO_PRESIDENTE(20),
	CONCLUSO_DESPACHO_RELATOR(21), ENVIAR_INSTANCIA_SUPERIOR(22), MARCAR_SESSAO(23), ARQUIVAMENTO(24),
	DESARQUIVAMENTO(25), REMARCAR_SESSAO(26), DESMARCAR_SESSAO(27), RETORNAR_SERVENTIA_ORIGEM(28), OFICIO_DELEGACIA(29),
	PEDIDO_CONTADORIA(30), VERIFICAR_CONEXAO(31), SUSPENSAO_PROCESSO(32), CALCULAR_LIQUIDACAO_PENAS(33),
	PENHORA_ONLINE(46), AGUARDANDO_DECURSO_PRAZO(47), AGUARDANDO_PRAZO_DECADENCIAL(48),
	FINALIZAR_SUSPENSAO_PROCESSO(49), MARCAR_AUDIENCIA(50), REVELIA(51), CONTUMACIA(52),
	AGUARDANDO_CUMPRIMENTO_PENA(53), ARQUIVAMENTO_PROVISORIO(54), LIBERACAO_ACESSO(55), INFORMATIVO(56),
	PEDIDO_VISTA(57), RELATORIO(58), REVISAO(59), VERIFICAR_DISTRIBUICAO(60), PEDIDO_MANIFESTACAO(61),
	VERIFICAR_PARECER(62), PRE_ANALISE_PRECATORIA(63), PEDIDO_LAUDO(64), VERIFICAR_DOCUMENTO(65), EFETIVAR_EVENTO(66),
	CONCLUSO_EMENTA(67), CONCLUSO_VOTO(68), OFICIO_TURMA(69), OFICIO_SEGUNDO_GRAU(70), OFICIO_PRESIDENCIA(71),
	VERIFICAR_GUIA(72), CARTA_NOTIFICACAO(73), VERIFICAR_CALCULO(74), RENAJUD(75), VERIFICAR_DEVOLUCAO_PRECATORIA(76),
	VERIFICAR_NOVA_PRECATORIA(77), CONCLUSO_GENERICO_SEGUNDO_GRAU(78), VERIFICAR_PRECATORIA(79),
	MARCAR_SESSAO_EXTRA_PAUTA(83), TERMO(84), VERIFICAR_RECURSO_REPETITIVO(85), VERIFICAR_OFICIO_COMUNICATORIO(86),
	OFICIO_COMUNICATORIO(87), AGUARDANDO_DECURSO_PRAZO_PRISAO_CIVIL(88), CONCLUSO_PRESIDENTE_TJGO(89),
	CONCLUSO_VICE_PRESIDENTE_TJGO(90), INTIMACAO_VIA_TELEFONE(91), REQUISICAO_PEQUENO_VALOR(92),
	VERIFICAR_GUIA_PAGA(93), VERIFICAR_GUIA_PENDENTE(94), ELABORACAO_VOTO(95), MARCAR_AUDIENCIA_CONCILIACAO_CEJUSC(96),
	MARCAR_AUDIENCIA_MEDIACAO_CEJUSC(97), MARCAR_AUDIENCIA_CONCILIACAO_CEJUSC_DPVAT(98),
	VERIFICAR_CLASSE_PROCESSUAL(99), ALTERAR_VALOR_CAUSA(101), ALTERAR_CLASSE_PROCESSUAL(102), AGENDAMENTO_PERICIA(103),
	AVERBACAO_CUSTAS(108), PEDIDO_NATJUS_SEGUNDO_GRAU(109), VERIFICAR_RESPOSTA_CAMARA_SAUDE(110),
	VERIFICAR_RESPOSTA_PEDIDO_LAUDO_RELATORIO(111), VERIFICAR_REDISTRIBUICAO(112), CONFIRMAR_DISTRIBUICAO(113),
	ENCAMINHAR_PROCESSO(114), VERIFICAR_TEMA_TRANSITADO_JULGADO(115), TORNAR_SIGILOSO(190), RETIRAR_SIGILO(191),
	VERIFICAR_NOVO_PROCESSO_PEDIDO_ASSISTENCIA(192), CONCLUSO_DECISAO_PEDIDO_ASSISTENCIA(193), PEDIDO_CENOPES(194),
	VERIFICAR_RESPOSTA_PEDIDO_CENOPES(195), FINALIZAR_SUSPENSAO_PROCESSO_ACORDO_OUTROS(196), SOLICITACAO_CARGA(197),
	VERIFICAR_IMPEDIMENTO(198), VERIFICAR_IMPEDIMENTO_VOTANTES(199), VOTO_SESSAO(200),
	VERIFICAR_PEDIDO_SUSTENTACAO_ORAL(201), PROCLAMACAO_VOTO(202), SESSAO_CONHECIMENTO(203), RETIRAR_PAUTA(204),
	PEDIDO_VISTA_SESSAO(205), ADIAR_JULGAMENTO(206), RESULTADO_UNANIME(207), PEDIDO_SUSTENTACAO_ORAL_DEFERIDO(208),
	PEDIDO_SUSTENTACAO_ORAL_INDEFERIDA(209), VOTANTE_IMPEDIDO(210), ENVIAR_PROCESSO_PRESIDENTE_UNIDADE(211),
	RETORNAR_AUTOS_RELATOR_PROCESSO(212), ALVARA_SOLTURA(213), RESULTADO_VOTACAO(214), ADIADO_PELO_RELATOR(215),
	ATIVAR_PROCESSO_CALCULO(216), VERIFICAR_PROCESSO_HIBRIDO(217), APRECIADOS(218), VERIFICAR_IMPEDIMENTO_MP(219),
	VERIFICAR_RESULTADO_VOTACAO(221), PEDIDO_JUSTICA_RESTAURATIVA(225), VERIFICAR_AUDIENCIAS_REALIZADAS_CEJUSC(226);

	private int tipo;

	private PendenciaTipo(int tipo) {
		this.tipo = tipo;
	}

	public int getValue() {
		return tipo;
	}

	public static List<Integer> getAllValues() {
		return Stream.of(PendenciaTipo.values()).map(PendenciaTipo::getValue).collect(Collectors.toList());
	}
}