CREATE TABLE "PROJUDI"."GUIA_QUANT_MAX_PARCELAS" 
   (	"ID_GUIA_QUANT_MAX_PARCELAS" NUMBER(24,0) NOT NULL ENABLE, 
	"ID_GUIA_EMIS" NUMBER(24,0) NOT NULL ENABLE, 
	"QUANT_MAX_PARCELAS" INTEGER,
	 CONSTRAINT "PRIMARY_924" PRIMARY KEY ("ID_GUIA_QUANT_MAX_PARCELAS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROJUDI_DATA"  ENABLE, 
	 CONSTRAINT "GUIA_QUANT_GUIAEMISSAO_FK" FOREIGN KEY ("ID_GUIA_EMIS")
	  REFERENCES "PROJUDI"."GUIA_EMIS" ("ID_GUIA_EMIS") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROJUDI_DATA" ;

  CREATE INDEX "PROJUDI"."GUIA_QUANT_ID_GUIAEMISSAO" ON "PROJUDI"."GUIA_QUANT_MAX_PARCELAS" ("ID_GUIA_EMIS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROJUDI_DATA" ;
  
  CREATE SEQUENCE  "PROJUDI"."GUIA_QUANT_MAX_PARCELAS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

  CREATE OR REPLACE TRIGGER "PROJUDI"."GUIA_QUANT_MAX_PARCELAS_TRG" BEFORE INSERT OR UPDATE ON GUIA_QUANT_MAX_PARCELAS
FOR EACH ROW
DECLARE
v_newVal NUMBER(12) := 0;
v_incval NUMBER(12) := 0;
BEGIN
  IF INSERTING AND :new.ID_GUIA_QUANT_MAX_PARCELAS IS NULL THEN
    SELECT  GUIA_QUANT_MAX_PARCELAS_SEQ.NEXTVAL INTO v_newVal FROM DUAL;
    -- If this is the first time this table have been inserted into (sequence == 1)
    IF v_newVal = 1 THEN
      --get the max indentity value from the table
      SELECT NVL(max(ID_GUIA_QUANT_MAX_PARCELAS),0) INTO v_newVal FROM GUIA_QUANT_MAX_PARCELAS;
      v_newVal := v_newVal + 1;
      --set the sequence to that value
      LOOP
           EXIT WHEN v_incval>=v_newVal;
           SELECT GUIA_QUANT_MAX_PARCELAS_SEQ.nextval INTO v_incval FROM dual;
      END LOOP;
    END IF;
    --used to emulate LAST_INSERT_ID()
    --mysql_utilities.identity := v_newVal;
   -- assign the value from the sequence to emulate the identity column
   :new.ID_GUIA_QUANT_MAX_PARCELAS := v_newVal;
  END IF;
END;

commit;

ALTER TRIGGER "PROJUDI"."GUIA_QUANT_MAX_PARCELAS_TRG" ENABLE;

commit;