CREATE OR REPLACE VIEW VIEW_RECURSO_COMPLETO
AS SELECT
    R.ID_RECURSO AS ID_RECURSO,
    R.ID_PROC AS ID_PROC,
    P.PROC_NUMERO AS PROC_NUMERO,
    P.DIGITO_VERIFICADOR AS DIGITO_VERIFICADOR,
    (P.PROC_NUMERO || '.' || P.DIGITO_VERIFICADOR) AS PROC_NUMERO_COMPLETO,
    R.ID_SERV_ORIGEM AS ID_SERV_ORIGEM,
    R.ID_AREA_DIST_ORIGEM AS ID_AREA_DIST_ORIGEM,
    SO.SERV AS SERV_ORIGEM,
    R.ID_SERV_RECURSO AS ID_SERV_RECURSO,
    SR.SERV AS SERV_RECURSO,
    R.ID_PROC_TIPO AS ID_PROC_TIPO,
    PT.PROC_TIPO AS PROC_TIPO,
    R.DATA_ENVIO AS DATA_ENVIO,
    R.DATA_RECEBIMENTO AS DATA_RECEBIMENTO,
    R.DATA_RETORNO AS DATA_RETORNO,
    PT.PROC_TIPO_CODIGO AS PROC_TIPO_CODIGO,
    RP.ID_RECURSO_PARTE AS ID_RECURSO_PARTE,
    PPT.PROC_PARTE_TIPO_CODIGO AS PROC_PARTE_TIPO_CODIGO,
    PRP.ID_PROC_PARTE AS ID_PROC_PARTE,
    PRP.NOME AS NOME,
    PRP.CPF AS CPF,
    PRP.CNPJ AS CNPJ,
    PRP.DATA_BAIXA AS DATA_BAIXA,
    PRP.ID_ENDERECO AS ID_ENDERECO,
    EN.LOGRADOURO AS LOGRADOURO,
    EN.NUMERO AS NUMERO,
    EN.COMPLEMENTO AS COMPLEMENTO,
    EN.CEP AS CEP,
    EN.ID_BAIRRO AS ID_BAIRRO,
    B.BAIRRO AS BAIRRO,
    C2.ID_CIDADE AS ID_CIDADE,
    C2.CIDADE AS CIDADE,
    C2.ID_ESTADO AS ID_ESTADO,
    E2.ESTADO AS ESTADO,
    E2.UF AS UF,
    CC.POLO_ATIVO AS POLO_ATIVO,
    CC.POLO_PASSIVO AS POLO_PASSIVO,	
    RP.ID_PROC_TIPO AS ID_PROC_TIPO_RECURSO_PARTE,
    PTRP.PROC_TIPO AS PROC_TIPO_RECURSO_PARTE,
    CCRP.POLO_ATIVO AS POLO_ATIVO_RECURSO_PARTE,
    CCRP.POLO_PASSIVO AS POLO_PASSIVO_RECURSO_PARTE	 	
  FROM
    ((((((((((
    (RECURSO R JOIN PROC P ON((R.ID_PROC = P.ID_PROC)))
    JOIN SERV SO ON((SO.ID_SERV = R.ID_SERV_ORIGEM)))
    JOIN SERV SR ON((SR.ID_SERV = R.ID_SERV_RECURSO)))
    JOIN PROC_TIPO PT ON((PT.ID_PROC_TIPO = R.ID_PROC_TIPO)))	
    LEFT JOIN RECURSO_PARTE RP ON(((R.ID_RECURSO = RP.ID_RECURSO) AND (RP.DATA_BAIXA IS NULL))))
    LEFT JOIN PROC_PARTE PRP ON((RP.ID_PROC_PARTE = PRP.ID_PROC_PARTE)))
    LEFT JOIN PROC_PARTE_TIPO PPT ON((RP.ID_PROC_PARTE_TIPO = PPT.ID_PROC_PARTE_TIPO)))
    LEFT JOIN ENDERECO EN ON((PRP.ID_ENDERECO = EN.ID_ENDERECO)))
    LEFT JOIN BAIRRO B ON((EN.ID_BAIRRO = B.ID_BAIRRO)))
    LEFT JOIN CIDADE C2 ON((B.ID_CIDADE = C2.ID_CIDADE)))
    LEFT JOIN ESTADO E2 ON((C2.ID_ESTADO = E2.ID_ESTADO)))
    LEFT JOIN CNJ_CLASSE CC ON CC.ID_CLASSE = PT.ID_CNJ_CLASSE
	LEFT JOIN PROC_TIPO PTRP ON PTRP.ID_PROC_TIPO = RP.ID_PROC_TIPO
	LEFT JOIN CNJ_CLASSE CCRP ON CCRP.ID_CLASSE = PTRP.ID_CNJ_CLASSE
	
