CREATE OR REPLACE VIEW VIEW_AUDI_COMPLETA_PRIM_GRAU
AS SELECT VUS.ID_AUDI            AS ID_AUDI,
    VUS.ID_AUDI_TIPO            AS ID_AUDI_TIPO,
    AT.AUDI_TIPO                AS AUDI_TIPO,
    AT.AUDI_TIPO_CODIGO         AS AUDI_TIPO_CODIGO,
    VUS.DATA_AGENDADA           AS DATA_AGENDADA,
    VUS.DATA_MOVI               AS DATA_MOVI_AUDI,
    VUS.RESERVADA               AS RESERVADA,
    AP.ID_AUDI_PROC             AS ID_AUDI_PROC,
    AP.ID_AUDI_PROC_STATUS      AS ID_AUDI_PROC_STATUS,
    APS.AUDI_PROC_STATUS        AS AUDI_PROC_STATUS,
    APS.AUDI_PROC_STATUS_CODIGO AS AUDI_PROC_STATUS_CODIGO,
    AP.ID_SERV_CARGO            AS ID_SERV_CARGO,
    SC.SERV_CARGO               AS SERV_CARGO,
    U.USU                       AS USU,
    U.NOME                      AS NOME,
    S.ID_SERV                   AS ID_SERV,
    S.SERV                      AS SERV,
    AP.ID_PROC                  AS ID_PROC,
    P.PROC_NUMERO               AS PROC_NUMERO,
    P.DIGITO_VERIFICADOR        AS DIGITO_VERIFICADOR,
    CASE  WHEN   AP.ID_PROC IS NULL AND 
         NOT AP.CODIGO_TEMP     IS NULL THEN
          (SELECT TO_CHAR(PROC_NUMERO_COMPLETO)
           FROM AUDI_PROC_FISICO APF
           WHERE APF.ID_AUDI_PROC = AP.ID_AUDI_PROC
          )    
    ELSE 
          (P.PROC_NUMERO || '.' || P.DIGITO_VERIFICADOR)     
    END AS PROC_NUMERO_COMPLETO,
    AP.DATA_MOVI                 AS DATA_MOVI_AUDI_PROC,
    VUS.CODIGO_TEMP              AS CODIGO_TEMP,
    AP.CODIGO_TEMP               AS CODIGO_TEMP_AUDI_PROC,
    AP.ID_AUDI_PROC_STATUS_ANA   AS ID_AUDI_PROC_STATUS_ANA,
    APS2.AUDI_PROC_STATUS        AS AUDI_PROC_STATUS_ANA,
    APS2.AUDI_PROC_STATUS_CODIGO AS AUDI_PROC_STATUS_CODIGO_ANA,
    AP.ID_ARQ_ATA                AS ID_ARQ_ATA,
    AP.DATA_AUDI_ORIGINAL        AS DATA_AUDI_ORIGINAL,
    AP.ID_ARQ_ATA_ADIAMENTO      AS ID_ARQ_ATA_ADIAMENTO,
    AP.ID_ARQ_ATA_INICIADO       AS ID_ARQ_ATA_INICIADO,
    VUS.ID_ARQ_FINALIZACAO       AS ID_ARQ_FINALIZACAO,
    AP.ID_SERV_CARGO_PRESIDENTE  AS ID_SERV_CARGO_PRESIDENTE,
    SCP.SERV_CARGO               AS SERV_CARGO_PRESIDENTE,
    UP.USU                       AS USU_PRESIDENTE,
    UP.NOME                      AS NOME_PRESIDENTE,
    SCP.ID_SERV                  AS ID_SERV_PRESIDENTE,
    SP.SERV                      AS SERV_PRESIDENTE,
    AP.ID_SERV_CARGO_MP          AS ID_SERV_CARGO_MP,
    SCMP.SERV_CARGO              AS SERV_CARGO_MP,
    UMP.USU                      AS USU_MP,
    UMP.NOME                     AS NOME_MP,
    SCMP.ID_SERV                 AS ID_SERV_MP,
    SMP.SERV                     AS SERV_MP,
    AP.ID_SERV_CARGO_REDATOR     AS ID_SERV_CARGO_REDATOR,
    SCR.SERV_CARGO               AS SERV_CARGO_REDATOR,
    UR.USU                       AS USU_REDATOR,
    UR.NOME                      AS NOME_REDATOR,
    SCR.ID_SERV                  AS ID_SERV_REDATOR,
    SR.SERV                      AS SERV_REDATOR,
    CASE  WHEN   AP.ID_PROC IS NULL AND 
         NOT AP.CODIGO_TEMP     IS NULL THEN         
          (SELECT PROMOVENTE
            FROM AUDI_PROC_FISICO APF
            WHERE APF.ID_AUDI_PROC = AP.ID_AUDI_PROC
          )
    ELSE
          (SELECT PP.ID_PROC_PARTE || '__@--' || PP.NOME  || '__@--' || PP.PROC_PARTE_TIPO
             FROM VIEW_PROC_PARTE PP
            WHERE PP.DATA_BAIXA IS NULL
             AND PP.PROC_PARTE_TIPO_CODIGO IN (1, 5)
             AND PP.ID_PROC =  AP.ID_PROC
             AND ROWNUM = 1)
    END 
       AS PRIMEIRO_PROMOVENTE_RECORRENTE,
    CASE  WHEN   AP.ID_PROC IS NULL AND 
         NOT AP.CODIGO_TEMP     IS NULL THEN   
          (SELECT PROMOVIDO
          FROM AUDI_PROC_FISICO APF
          WHERE APF.ID_AUDI_PROC = AP.ID_AUDI_PROC
          )         
    ELSE     
          (SELECT PP.ID_PROC_PARTE || '__@--' || PP.NOME  || '__@--' || PP.PROC_PARTE_TIPO
             FROM VIEW_PROC_PARTE PP
            WHERE PP.DATA_BAIXA IS NULL
             AND PP.PROC_PARTE_TIPO_CODIGO IN (0, 6)
             AND PP.ID_PROC =  AP.ID_PROC
             AND ROWNUM = 1) 
    END AS PRIMEIRO_PROMOVIDO_RECORRIDO,
    AP.ACORDO AS ACORDO,
    AP.VALOR_ACORDO AS VALOR_ACORDO,
	AP.ID_PROC_TIPO              AS ID_PROC_TIPO_AUDIENCIA,
	PTAP.PROC_TIPO               AS PROC_TIPO_AUDIENCIA,
    CC.POLO_ATIVO                AS POLO_ATIVO,
    CC.POLO_PASSIVO              AS POLO_PASSIVO,
	AP.ID_PEND_VOTO              AS ID_PEND_VOTO,
	AP.ID_PEND_EMENTA            AS ID_PEND_EMENTA
  FROM (((((((((((((((((((((((((((AUDI VUS
  JOIN AUDI_TIPO AT
  ON((VUS.ID_AUDI_TIPO = AT.ID_AUDI_TIPO)))
  JOIN SERV S
  ON((VUS.ID_SERV = S.ID_SERV)))
  LEFT JOIN AUDI_PROC AP
  ON((VUS.ID_AUDI = AP.ID_AUDI)))
  LEFT JOIN AUDI_PROC_STATUS APS
  ON((AP.ID_AUDI_PROC_STATUS = APS.ID_AUDI_PROC_STATUS)))
  LEFT JOIN SERV_CARGO SC
  ON((AP.ID_SERV_CARGO = SC.ID_SERV_CARGO)))
  LEFT JOIN USU_SERV_GRUPO USG
  ON((SC.ID_USU_SERV_GRUPO = USG.ID_USU_SERV_GRUPO)))
  LEFT JOIN USU_SERV US
  ON((USG.ID_USU_SERV = US.ID_USU_SERV)))
  LEFT JOIN USU U
  ON((US.ID_USU = U.ID_USU)))
  LEFT JOIN PROC P
  ON((AP.ID_PROC = P.ID_PROC)))
  LEFT JOIN AUDI_PROC_STATUS APS2
  ON((AP.ID_AUDI_PROC_STATUS_ANA = APS2.ID_AUDI_PROC_STATUS)))
  LEFT JOIN SERV_CARGO SCP
  ON((AP.ID_SERV_CARGO_PRESIDENTE = SCP.ID_SERV_CARGO)))
  LEFT JOIN USU_SERV_GRUPO USGP
  ON((SCP.ID_USU_SERV_GRUPO = USGP.ID_USU_SERV_GRUPO)))
  LEFT JOIN USU_SERV USP
  ON((USGP.ID_USU_SERV = USP.ID_USU_SERV)))
  LEFT JOIN USU UP
  ON((USP.ID_USU = UP.ID_USU)))
  LEFT JOIN SERV SP
  ON((SCP.ID_SERV = SP.ID_SERV)))
  LEFT JOIN SERV_CARGO SCMP
  ON((AP.ID_SERV_CARGO_MP = SCMP.ID_SERV_CARGO)))
  LEFT JOIN USU_SERV_GRUPO USGMP
  ON((SCMP.ID_USU_SERV_GRUPO = USGMP.ID_USU_SERV_GRUPO)))
  LEFT JOIN USU_SERV USMP
  ON((USGMP.ID_USU_SERV = USMP.ID_USU_SERV)))
  LEFT JOIN USU UMP
  ON((USMP.ID_USU = UMP.ID_USU)))
  LEFT JOIN SERV SMP
  ON((SCMP.ID_SERV = SMP.ID_SERV)))
  LEFT JOIN SERV_CARGO SCR
  ON((AP.ID_SERV_CARGO_REDATOR = SCR.ID_SERV_CARGO)))
  LEFT JOIN USU_SERV_GRUPO USGR
  ON((SCR.ID_USU_SERV_GRUPO = USGR.ID_USU_SERV_GRUPO)))
  LEFT JOIN USU_SERV USR
  ON((USGR.ID_USU_SERV = USR.ID_USU_SERV)))
  LEFT JOIN USU UR
  ON((USR.ID_USU = UR.ID_USU)))
  LEFT JOIN SERV SR
  ON((SCR.ID_SERV             = SR.ID_SERV)))
  LEFT JOIN PROC_TIPO PTAP
  ON((AP.ID_PROC_TIPO = PTAP.ID_PROC_TIPO)))
  LEFT JOIN CNJ_CLASSE CC
  ON((CC.ID_CLASSE = PTAP.ID_CNJ_CLASSE)))
  WHERE (AT.AUDI_TIPO_CODIGO <> 12)