
  CREATE TABLE "PROJUDI"."GUIA_ITEM_DISPONIVEL" 
   (	"ID_GUIA_ITEM_DISPONIVEL" NUMBER(24,0) NOT NULL ENABLE, 
	"ID_GUIA_ITEM" NUMBER(24,0) NOT NULL ENABLE, 
	"ID_PEND" NUMBER(10,0), 
	"ID_MOVI" NUMBER(10,0), 
	"DATA_PENDENCIA" DATE,
	"DATA_MOVIMENTACAO" DATE,
	 CONSTRAINT "PK_GUIA_ITEM_DISPONIVEL" PRIMARY KEY ("ID_GUIA_ITEM_DISPONIVEL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROJUDI_DATA"  ENABLE, 
	 CONSTRAINT "GUIAITEMDISPONIVEL_GUIAITEM_FK" FOREIGN KEY ("ID_GUIA_ITEM")
	  REFERENCES "PROJUDI"."GUIA_ITEM" ("ID_GUIA_ITEM") ENABLE, 
	 CONSTRAINT "GUIAITEMDISPONIVEL_MOVI_FK" FOREIGN KEY ("ID_MOVI")
	  REFERENCES "PROJUDI"."MOVI" ("ID_MOVI") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROJUDI_DATA" ;

  CREATE INDEX "PROJUDI"."GUIA_ITEM_DISPONIVEL_IDX1" ON "PROJUDI"."GUIA_ITEM_DISPONIVEL" ("ID_GUIA_ITEM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROJUDI_DATA" ;

  CREATE INDEX "PROJUDI"."GUIA_ITEM_DISPONIVEL_IDX2" ON "PROJUDI"."GUIA_ITEM_DISPONIVEL" ("ID_PEND") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROJUDI_DATA" ;

  CREATE INDEX "PROJUDI"."GUIA_ITEM_DISPONIVEL_IDX3" ON "PROJUDI"."GUIA_ITEM_DISPONIVEL" ("ID_MOVI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROJUDI_DATA" ;
  
  CREATE SEQUENCE  "PROJUDI"."GUIA_ITEM_DISPONIVEL_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

  CREATE OR REPLACE TRIGGER "PROJUDI"."GUIA_ITEM_DISPONIVEL_ID_TRG" BEFORE INSERT OR UPDATE ON GUIA_ITEM_DISPONIVEL
FOR EACH ROW
DECLARE
v_newVal NUMBER(12) := 0;
v_incval NUMBER(12) := 0;
BEGIN
  IF INSERTING AND :new.ID_GUIA_ITEM_DISPONIVEL IS NULL THEN
    SELECT GUIA_ITEM_DISPONIVEL_ID_SEQ.NEXTVAL INTO v_newVal FROM DUAL;
   
   :new.ID_GUIA_ITEM_DISPONIVEL := v_newVal;
  END IF;
END;

/
ALTER TRIGGER "PROJUDI"."GUIA_ITEM_DISPONIVEL_ID_TRG" ENABLE;

commit;
