CREATE TABLE PROJUDI.PROC_PARTE_ADVOGADO_SPG (
    ID_PROC                   NUMBER(24,0)  NOT NULL, 
    ID_PROC_PARTE             NUMBER(24,0)  NOT NULL,
    OAB_NUMERO                NUMBER(24,0)  NOT NULL,
    OAB_UF                    CHAR(2)       NOT NULL,
    NOME_COMPLETO             VARCHAR2(255) NOT NULL,
    NOME_SIMPLIFICADO         VARCHAR2(30)  NOT NULL,
    DATA_IMPORTACAO           DATE          NOT NULL,
    OAB_COMPLEMENTO           VARCHAR2(20),
    CPF                       VARCHAR2(30),
    EMAIL                     VARCHAR2(70)
);

ALTER TABLE PROJUDI.PROC_PARTE_ADVOGADO_SPG ADD CONSTRAINT PROCPARTEADVSPG_PROC_FK FOREIGN KEY (ID_PROC) REFERENCES PROJUDI.PROC (ID_PROC);

ALTER TABLE PROJUDI.PROC_PARTE_ADVOGADO_SPG ADD CONSTRAINT PROCPARTEADVSPG_PROCPARTE_FK FOREIGN KEY (ID_PROC_PARTE) REFERENCES PROJUDI.PROC_PARTE (ID_PROC_PARTE);
