
  CREATE TABLE "PROJUDI"."USU_CAND" 
   (	"ID_USU_CAND" NUMBER(24,0) NOT NULL ENABLE, 
	"CURRICULO" CLOB NOT NULL ENABLE, 
	"DATA_INSCRICAO" DATE NOT NULL ENABLE, 
	"NUMERO_CONTA" VARCHAR2(100 BYTE), 
	"NUMERO_AGENCIA" VARCHAR2(100 BYTE), 
	"CODIGO_BANCO" VARCHAR2(100 BYTE), 
	"OBSERVACAO_STATUS" CLOB, 
	"CODIGO_STATUS_ATUAL" NUMBER(10,0), 
	"DATA_STATUS_ATUAL" DATE, 
	"ID_USU" NUMBER(10,0), 
	"CODIGO_STATUS_ANTERIOR" NUMBER(10,0), 
	"DATA_STATUS_ANTERIOR" DATE, 
	 CONSTRAINT "PRIMARY_1578" PRIMARY KEY ("ID_USU_CAND")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROJUDI_DATA"  ENABLE, 
	 CONSTRAINT "USUCAND_USU_FK" FOREIGN KEY ("ID_USU")
	  REFERENCES "PROJUDI"."USU" ("ID_USU") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROJUDI_DATA" 
 LOB ("CURRICULO") STORE AS BASICFILE (
  TABLESPACE "PROJUDI_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("OBSERVACAO_STATUS") STORE AS BASICFILE (
  TABLESPACE "PROJUDI_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

  CREATE OR REPLACE TRIGGER "PROJUDI"."USU_CAND_ID_USU_CANDIDATO_TRG" BEFORE INSERT OR UPDATE ON "USU_CAND"
FOR EACH ROW
DECLARE
v_newVal NUMBER(12) := 0;
v_incval NUMBER(12) := 0;
BEGIN
  IF INSERTING AND :new.ID_USU_CAND IS NULL THEN
    SELECT  ID_USU_CAND_SEQ.NEXTVAL INTO v_newVal FROM DUAL;
    -- If this is the first time this table have been inserted into (sequence == 1)
    IF v_newVal = 1 THEN
      --get the max indentity value from the table
      SELECT NVL(max(ID_USU_CAND),0) INTO v_newVal FROM USU_CAND;
      v_newVal := v_newVal + 1;
      --set the sequence to that value
      LOOP
           EXIT WHEN v_incval>=v_newVal;
           SELECT ID_USU_CAND_SEQ.nextval INTO v_incval FROM dual;
      END LOOP;
    END IF;
    --used to emulate LAST_INSERT_ID()
    --mysql_utilities.identity := v_newVal;
   -- assign the value from the sequence to emulate the identity column
   :new.ID_USU_CAND := v_newVal;
  END IF;
END;
/
ALTER TRIGGER "PROJUDI"."USU_CAND_ID_USU_CANDIDATO_TRG" ENABLE;
